### ISSUE TITLE
Enum extension Required on Page 306, 347, 385, 5754 and 5932

### ISSUE THREAD

**Issue by anwar0206** [microsoft/ALAppExtensions#10059]
Hi,
Report usage selection enum extension is available but not referred on the following pages
Page No. 306, 347, 385, 5754 and 5932. Extending this enum does not show the new enum extensions when the pages are used the user. Making extending the report selection usage enum of no use.

Either the above pages should use Report selection usage enum so the extended enum can be displayed for user to select or there should be a way to extend the Report selection usage of the pages which is currently Option field so those can be extended and used by the partners in their App's.

**Comment by miljance** [comment]
Use case as I see it is:
Report Selection for Sales should be extended with additional report for printing out from Posted Sales Invoice.

I would have following suggestions in order to solve this problem.

1.  Quick solution: Replace the OptionCaption with an extensible Enum. In this case in order for a developer to achieve desired effect he/she should normally extend two enums. Good about this solution is also that no breaking changes have to be introduced nor objects obsoleted. This solution is however not clean as one main Enum would exist and multiple smaller ones that have to fit each other.
2. Cleaner solution: Separate Report Selection to different areas so that a developer normally need to extend only one Enum per area. That would however mean that upgrade routines may need to be implemented and objects obsoleted at some point and current customers would be affected. As an alternative similar approach could be taken as in the case of Price Calculation two mechanisms coexist.
3. Not so pretty solution - officially recommend the developers to create new objects (both tables and pages?) in order to cover the custom Report selection

**Comment by anwar0206** [comment]
2nd suggestion looks generic and more cleaner while developing Apps.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
