### ISSUE TITLE
Business Central stacks on large invoice posting.

### ISSUE THREAD

**Issue by vrough** [Microsoft/ALAppExtensions#103]
**Describe the bug**
Hi. We faced the issue with posting Sales Invoices with large numbers of lines in PROD environment of our client AppXite.
After October'18 release of Business Central process of posting Invoices takes much more times than earlier.
For example Invoice with 400-600 line is processed about 4 hours.
Invoice with 1500-2000 lines was processing more than 12 hours and after that was not posted at all.
But no any errors message appear.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Generate Sales Invoice with 1000 or more lines
2. Try to post it.

**Expected behavior**
The invoice should be posted within a reasonable amount of time. Previously it took up to 15 minutes.

**Versions:**
Business Central: NL Dynamics NAV 13.0 (24813)

We know that Microsoft is fixing this issue now and we are ready AppXite to be an early trial of the fix.
As it is very important and critical for us.

**Comment by mazhelez** [comment]
Hi, @vrough!
Thanks for reaching out!
We at Microsoft value customer engagement when it comes to improving Business Central.

**I have proceeded and _opened an issue on your behalf_ explaining the problem you came across.**

However, please note that If you run into an issue in the future, _you need to open a regular support case yourself_.  This in needed so that the team working on it knows whom to contact if they need further explanations and details.
The idea behind this repository is targeting AL extensions and topics regarding extensibility in Business Central exclusively. 
We do not intend for it to become an _easy_ customer support site. 

You can open _Support Request_ to CSS through _PartnerSource_ portal or contact your _Service Account Manager (SAM)_ in the local subsidiary to understand what is included in your contract as of support incident and _PAH (Partner Advisory Hours)_. Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you or your company.

Finally,

**Comment by vrough** [comment]
Thanks, Maria for your advice!
But could you completely clarify one question for me?
There is no section related to the Business Central cloud-hosted product in the New Support Request section of PartnerSource portal.
Should I create request under “Dynamics 365 Business Central on-premises” section?



Thanks,
Valentyn Khutornyi

Sent from Mail for Windows 10
