### ISSUE TITLE
[Function expose] Table 370 "Excel Buffer"

### ISSUE THREAD

**Issue by Tharangac** [Microsoft/ALAppExtensions#104]
able 370 "Excel Buffer"

It would be nice to have "OpenBook" function available global/external.

**Comment by JesperSchulz** [comment]
Thank you very much for your request. I'm happy to inform you, that an "extension compatible" version of OpenBook already exists! It has the name OpenBookStream, and uses a stream instead of a file as input parameter - seeing that files aren't supported in extension development. I hope that resolves your issue! If not, please reopen the case! Thanks again!
