### ISSUE TITLE
[Event Modification] Codeunit 80 Sales.-Post - OnBeforeInsertShipmentHeader

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10463]
Hi, would it be possible to modify the event OnBeforeInsertShipmentHeader in codeunit 80 SalesPost to insert a SalesHeader parameter, like this :
![image](https://user-images.githubusercontent.com/76153139/103668573-88d07f00-4f77-11eb-9ff9-149f1959b9de.png)
![image](https://user-images.githubusercontent.com/76153139/103668669-a1d93000-4f77-11eb-94ce-f543d962aa51.png)
Thanks!

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

There is no OnBeforeInsertShipmentHeader event.  If you want to add it with SalesCommentLine parameter it makes sense to put it after             
    `if SalesSetup."Copy Comments Order to Shpt." then begin `
where SalesCommentLine  is only used.
