### ISSUE TITLE
needed new event codeunit 1008

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10884]
Hi

Please add the next events to CU 1008
BC 17 CU 3

1) At the end of the function JTCalculateCommonFilters

position:
![image](https://user-images.githubusercontent.com/20538979/106895878-7887fd00-66f9-11eb-9459-4423d25885dc.png)

2) At the end of the function JobCalculateCommonFilters

position:
![image](https://user-images.githubusercontent.com/20538979/106896782-b33e6500-66fa-11eb-8989-2d3306b99e97.png)

3) In the function ReportAnalysis (at the end of FOR cycle)

position:
![image](https://user-images.githubusercontent.com/20538979/106897448-9d7d6f80-66fb-11eb-8c93-65cbaa45baab.png)
![image](https://user-images.githubusercontent.com/20538979/106897497-ae2de580-66fb-11eb-8423-42643798f248.png)

4) In function ReportAnalysis, after GetPriceAmounts(P);

position:
![image](https://user-images.githubusercontent.com/20538979/106899614-3ca36680-66fe-11eb-9f84-947df4928a8b.png)

5) At the end of the function CalculateAmounts

position:
![image](https://user-images.githubusercontent.com/20538979/106899786-72484f80-66fe-11eb-8f4b-c4fb82e1600d.png)

6) Change standard parameter AmountField from Option to Enum (it used in many functions in this codeunit)

![image](https://user-images.githubusercontent.com/20538979/106900588-5beec380-66ff-11eb-9ca0-c5a56abf1646.png)
![image](https://user-images.githubusercontent.com/20538979/106900601-5ee9b400-66ff-11eb-8054-6ac83e877899.png)

**Comment by StanPesotskiy** [comment]
Please do not mix different type of requests into one. Have 6 separate requests. It gives you better chances to get all of them done.

Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place. 
See https://github.com/microsoft/ALAppExtensions/issues/10924 for example.
