### ISSUE TITLE
Exposing functions GetApplicationAreaBuffer and TrySaveApplicationAreaCurrentCompany through CU 9179 Application Area Mgmt. Facade

### ISSUE THREAD

**Issue by wdet** [microsoft/ALAppExtensions#11150]
Hi,

Is it possible to make the functions GetApplicationAreaBuffer and TrySaveApplicationAreaCurrentCompany externally available via CU 9179?

We have made a custom page on the "Application Area Buffer" table to display our application areas and made it possible to enable these via this page.

**Comment by grobyns** [comment]
Hi,
While we originally intended for application areas to be individually enabled/disabled that idea was abandoned and we introduced experience tiers instead. Experience tiers control groups of application areas that belong together.

Instead of building a mechanism that controls application areas directly, you should build an experience tier, and have that control the application areas. _(Maybe you can build an experience tier that enables application areas selected by the user?)_

If you edit the application areas without the experience tier, you risk the experience tier being reset at some point and the application areas will be reset to what matches the experience tier losing what the users selected.

While much of the code to control application areas remains, I don't want to expose it in the cloud as we don't want to support the scenarios that come with it.

**If you do insist on controlling the application areas:** 
The buffer table is only used to convert columns to rows. If you have a fixed set of application areas then you don't need the buffer. You could just create a card page on top of the application area setup record.
If you want it as a list page, you'd also have to copy the buffer table and the two functions but as I said, you risk the areas getting reset on an update...
