### ISSUE TITLE
Withholding Tax calculation con Item with type Service (IT localization)

### ISSUE THREAD

**Issue by gpintaudi** [microsoft/ALAppExtensions#11191]
Hi,
in codeunit 12101 Withholding  - Contribution, function CalculateWithholdingTax, the calculation is performed only for G/L Accounts.
Since in BC Items with Type=Service are available, it should be possible to calculate Withholding Tax also with this type of line.
![C12101](https://user-images.githubusercontent.com/64265795/108703800-65ec3100-750b-11eb-92d7-bbb5b0fd5b8e.png)

Also an event after apply purchaseline filters would be fine, such as OnAfterApplyPurchaseLineFiltersOnWithholdingTaxCalc.

**Comment by StanPesotskiy** [comment]
1. Regarding service items - For the new features please submit a product suggestion on https://aka.ms/bcideas
2. Regarding a new event:
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by gpintaudi** [comment]
This is the event requested on Codeunit 12101 Withholding - Contribution:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterApplyPurchLineFiltersOnCalculateWithholdingTax(var PurchaseLine: Record "Purchase Line"; PurchaseHeader: Record "Purchase Header")
    begin
    end;
```

and where it should be placed in procedure CalculateWithholdingTax

```
    procedure CalculateWithholdingTax(var PurchHeader: Record "Purchase Header"; Recalculate: Boolean)
    var
        PurchWithSoc: Record "Purch. Withh. Contribution";
        PurchLine: Record "Purchase Line";
        TotalAmount: Decimal;
    begin
        PurchLine.Reset();
        PurchLine.SetRange("Document Type", PurchHeader."Document Type");
        PurchLine.SetRange("Document No.", PurchHeader."No.");
        PurchLine.SetRange(Type, PurchLine.Type::"G/L Account");

        OnAfterApplyPurchLineFiltersOnCalculateWithholdingTax(PurchLine, PurchHeader);

        TotalAmount := 0;
        if PurchLine.FindSet then
            repeat
                TotalAmount := TotalAmount + PurchLine."VAT Base Amount";
            until PurchLine.Next = 0;
```
