### ISSUE TITLE
[Publisher] Report 840 "Suggest Worksheet Lines" - OnBeforeNoOptionsChosen

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#11573]
Please make procedure NoOptionsChosen extensible by adding a OnBeforeNoOptionsChosen publisher with Handled pattern and var access to the boolean return value to overrule the error.

![image](https://user-images.githubusercontent.com/25268332/110473978-6e359600-80df-11eb-9ea1-a853db80aba1.png)

Already raised in #5103 but it was never fixed.

We want to extend report 840 by adding additional entities / data items to be included in the cash flow forecast (conditional by new options added to the 'options' requestpage) . This alows us to avoid the Text002 error in case we want to test on our custom options / booleans (if hopefully report extensions would allow us extending the cash flow forecast report).

**Comment by fvet** [comment]
@StanPesotskiy, what kind of info are you missing?

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
