### ISSUE TITLE
[Protection Level] Page "Item Tracking Lines" Function "WriteToDatabase" make global

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11769]
We need to access it from "OnCodeOnBeforeModifyHeader" - Event of "Release Purchase Document"-Codeunit.

**Comment by SweconThomasH** [comment]
Hi Alexander, we have the necessity to pre-assign serial numbers and reservations for certain items, like machine attachments. This is to allow to start preparations further down the procurement process as early as possible. The "WriteToDatabase" function does exactly what we need, as it calls RegisterChange->CreateReserveEntry.CreateEntry and so on. We have had the call to "WriteToDatabase" in the Release Purchase CU since 2010, it works well, and we would rather continue using it this way than to code-duplicate whole functions, which is error-prone at future updates. Thank you!

**Comment by AlexanderYakunin** [comment]
Sounds good, can you provide code sample to demonstrate how you are using this procedure from outside of Item Tracking Lines page? Looks like you only need subset of code from this procedure, which can be isolated as separate public procedure.

**Comment by SWE-Tina** [comment]
Sure - Is this sufficient?

`                Item_loc.Get(PurchLine_loc."No.");
                if (Item_loc."Serial Nos." <> '') and
                  (PurchLine_loc.Quantity = PurchLine_loc."Qty. to Receive") then begin
                    ResEntry_loc.SetRange("Source Type", DATABASE::"Purchase Line");
                    ResEntry_loc.SetRange("Source Subtype", PurchLine_loc."Document Type");
                    ResEntry_loc.SetRange("Source ID", PurchLine_loc."Document No.");
                    ResEntry_loc.SetRange("Source Ref. No.", PurchLine_loc."Line No.");
                    if ResEntry_loc.IsEmpty then begin
                        Clear(ItemTrackingForm);
                        TempTrackingSpec_loc.InitFromPurchLine(PurchLine_loc);  
                        ItemTrackingForm.SetSourceSpec(TempTrackingSpec_loc, PurchLine_loc."Expected Receipt Date");
                        ItemTrackingForm.SetRecord(TempTrackingSpec_loc);
                        **ItemTrackingForm.AssignSerialNoBatch(1, false);**
                        **ItemTrackingForm.WriteToDatabase();**
                    end;
                end;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
