### ISSUE TITLE
[Extensibility enhancements] Purchase Credit Memo API page (`table 124 "Purch. Cr. Memo Hdr."` and `table 125 "Purch. Cr. Memo Line"`)

### ISSUE THREAD

**Issue by kyrylkov** [microsoft/ALAppExtensions#12003]
Expose `table 124 "Purch. Cr. Memo Hdr."` and `table 125 "Purch. Cr. Memo Line"` via separate API pages.

Similar to `SalesCreditMemLines.Page.al` on the sales side and taking into account `location code` issue https://github.com/microsoft/ALAppExtensions/issues/11818

**Comment by kyrylkov** [comment]
@JesperSchulz @onbuyuka Could this be added in a minor release also?  How often are minor releases?

**Comment by JesperSchulz** [comment]
Extensibility Enhancement request sent to our application integration experts. They will get back to you :-)

**Comment by AndersLarsen65** [comment]
Please vote for this idea https://dev.azure.com/dynamicssmb2/Dynamics%20SMB/_workitems/edit/303135

**Comment by JesperSchulz** [comment]
I don't think that link is accessible to our community. I believe the link Anders meant to post, was the following ideas link: https://experience.dynamics.com/ideas/idea/?ideaid=19bfce36-533f-e911-867a-0003ff68cb2d

However, that idea seems to be in status "declined" and I'm hence not sure if that's the link either. @AndersLarsen65, could you revisit this issue please?

**Comment by JesperSchulz** [comment]
Regardless of the above, this doesn't seem like an issue we want to do as an extensibility enhancement. Please use bcideas instead. Closing issue.

**Comment by kyrylkov** [comment]
@JesperSchulz Many items in that issue were already implemented since 2019.  Like `Reading and creating Sales Documents`.  So how is it that sales documents can be created, sales credit memos can be created, purchase documents can be creates, but purchase credit memos cannot be created?

**Comment by kyrylkov** [comment]
@JesperSchulz  @onbuyuka Guys, please address this.  This really doesn't make any sense.  

You just added `APIV2Locations.Page.al` in 18.1 

Also `APIV2SalesInvoices.Page.al`, `APIV2SalesCreditMemos.Page.al`, and `APIV2PurchaseInvoices.Page.al` exist for a long time.

Yet you refuse to add ` APIV2PurchaseCreditMemos.Page.al`.  What the logic behind this?

**Comment by onbuyuka** [comment]
@kyrylkov Sales and purchase documents are different in design than locations API. You can check the code yourself, in contrast to locations, purchase document APIs require more work and cannot be handled through a simple bug fix. That's why we kindly ask you to create an idea through https://experience.dynamics.com/ideas/, and if we see that idea gets enough attraction we can add it to our scope and future plans. 
In the meantime if you have an urgent need for Purchase Credit Memos APIs you can consider developing your custom API. Here is the documentation for that: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-custom-api

**Comment by kyrylkov** [comment]
@onbuyuka Onat, thank you for your comments.  You didn't address my main point.   You do have purchase documents already.  Namely Purchase Invoice `APIV2PurchaseInvoices.Page.al`.   The only one which is missing is its reversal - Purchase Credit Memo.  

I don't understand how it is signifincantly complex than adding a complete new locations page.  Both are non-breaking changes extending existing functionality.

**Comment by onbuyuka** [comment]
@kyrylkov You can check how the Sales Credit Memo API is implemented and how it is different from Sales Invoice API. You'd notice that source table is a buffer table, and there is a logic behind it since it combines Sales Header and Sales Credit Memo Header. We'd need to use the same design for Purchase Credit Memo API too, which requires upgrade code to copy records from Purchase Header and Purchase Credit Memo Header.
 This not a question of breaking, it is a question of time and investment.

**Comment by kyrylkov** [comment]
@onbuyuka Onat, I really appreaciate the explanation.  

Let me add where we stand here.  I hope we both agree Purchase Credit Memo is one of the most basic pieces of functionality. 

We integrate with multiple accounting and ERP solutions and in ALL, but D365BC, creating a vendor credit memo, means calling a REST endpoint or a SOAP op.   In D365BC, unfortunately, it means becoming **experts** in proprietary language - AL, creating pages, tables, writing AL code, deploying it to customer, and maintaining all that over time.   In short, the barrier of entry is extremely high, which discourages developers from building D365BC solutions.

At the same time D365BC probably has tens of thousands of clients and hundreds of companies interested in integrating with D365BC.  A large share of these clients and integrators probably require such basic functionality as Purchase Credit Memo via API.

It would take Microsoft x days (less than a week I assume) to implement this feature into the API.  But refusing to do it, means forcing hundreds of these clients and integrators spending disproportianately more time in total to re-implement the same basic functionality over and over again.

When our clients plan upgrades from Xero or QuickBooks to an ERP, we cannot recommend D365BC to them because the barrier of entry to implement basic functionality using API is so high.

I understand that this is a business matter of allocating time and resources, but it looks to me that this will greatly benefit D365BC ecosystem.  I cannot speak for others, but we will have to stop development of our D365BC integration, until the API is improved.

I hope you can draw attention of your program manager to this issue.

Thank you for your support.
