### ISSUE TITLE
[Event Request] Codeunit 7324 - Code

### ISSUE THREAD

**Issue by spookymattress** [Microsoft/ALAppExtensions#1203]
Please add events to the Code function in Codeunit 7324

```
LOCAL Code()
// NEW EVENT >>
OnBeforeWhseActivityPost(WhseActivLine);
// NEW EVENT <<
PostingReference := WhseSetup.GetNextReference;

WITH WhseActivHeader DO BEGIN
  WhseActivLine.SETRANGE("Activity Type",WhseActivLine."Activity Type");
  WhseActivLine.SETRANGE("No.",WhseActivLine."No.");
  WhseActivLine.SETFILTER("Qty. to Handle",'<>0');
  IF NOT WhseActivLine.FIND('-') THEN
    ERROR(Text003);
```

And second event in the bottom of Code function.

  ```
IF NOT HideDialog THEN
    Window.CLOSE;

  IF PrintDoc THEN
    CASE "Source Document" OF
      "Source Document"::"Purchase Order",
      "Source Document"::"Purchase Return Order":
        PurchPostPrint.GetReport(PurchHeader);
      "Source Document"::"Sales Order",
      "Source Document"::"Sales Return Order":
        SalesPostPrint.GetReport(SalesHeader);
      "Source Document"::"Inbound Transfer":
        TransferOrderPostPrint.PrintReport(TransHeader,Selection::Receipt);
      "Source Document"::"Outbound Transfer":
        TransferOrderPostPrint.PrintReport(TransHeader,Selection::Shipment);
    END;

  // NEW EVENT >>
  OnAfterWhseActivityPost(WhseActivLine);
  // NEW EVENT <<

  COMMIT;
  CLEAR(WhseJnlRegisterLine);
END;
```

**Comment by salgiza** [comment]
I was going to ask just the same events 😄

For coherence, though, they should probably be called OnBeforeRun and OnAfterRun, and be included in the Run procedure (which is basically the same as @spookymattress requested, because the only thing that Run does is call the local Code procedure).

Note that I think that the event names that @spookymattress suggested are much, much, better, but the events in the *5763 Whse.-Post Shipment* and *5760 Whse.-Post Receipt* codeunits are already defined as OnBeforeRun and OnAfterRun, so it seems logical that all follow the same naming criteria...

**Comment by spookymattress** [comment]
@salgiza I actually disagree that we should keep the same naming convention. It would be much better to refactor the events in 5763 Whse.-Post Shipment and 5760 Whse.-Post Receipt as these are hopeless names  - OnBeforeRun/OnAfterRun

**Comment by salgiza** [comment]
Actually, we don't disagree. I'd also prefer if Microsoft renamed the events in code units 5763 and 5760. 

I only suggested to do it the other way around because I don't think that Microsoft wants to break compatibility with existing extensions, but I'd be happy if someone at Microsoft proved me wrong.

Bonus points if the event passed the Header as the param and not a Line, because the existing OnBeforeRun/OnAfterRun events can easily lead to confusion as to *when* the are raised, unless you know the existing code...

**Comment by AlexanderYakunin** [comment]
We cannot rename events, this is breaking change for our partners and their extensions.

**Comment by spookymattress** [comment]
I know it is a breaking change, but that's why it is important to give the integration event meaningful names in the first place instead of `OnBeforeRun` etc...
