### ISSUE TITLE
Event Request - EmailEditor, OnValidate To/Cc/Bcc

### ISSUE THREAD

**Issue by quadfin** [microsoft/ALAppExtensions#12115]
We need to perform customized validation of email addresses (To/Cc/Bcc) when input in the Email Editor (Page 13).
As currently designed it is not possible to intercept the input address prior to use.
Request for Integration Events in the OnValidate trigger for those fields
e.g.,

ToField::OnValidate trigger
    trigger OnValidate()
    begin
        OnValidateRecipient(Enum::"Email Recipient Type"::"To", ToRecipient);
        EmailMessage.SetRecipients(Enum::"Email Recipient Type"::"To", ToRecipient);
    end;

    [IntegrationEvent(true, ture)]
    procedure OnValidateRecipient(sender: Page "Email Dialog"; RecipientType: Enum::"Email Recipient Type"; var Recipient: Text);
    begin
    end;

**Comment by mazhelez** [comment]
Hey @quadfin 

Thanks for submitting this request.

Is there a particular reason to not want validation to run in other cases (e.g. sending an email in the background)?
Isn't it better to raise an event in `ValidateRecipients` from codeunit "Email Message Impl." where email addresses are already split?

Also, since your request affects only _System Application_, how do you feel about creating a pull request of your own? :)

**Comment by quadfin** [comment]
Hi Maria,

In this particular case I wish to provide feedback to the user at the point of data entry - so raising the event in the email message codeunit is 'too late' for the functionality targeted.  However your point is noted, there are other features that could be enabled by a more general event.

And your other point is noted -- show me..  
OK, I will create a pull and a prototype.
Will do asap.

**Comment by mazhelez** [comment]
Awesome, @quadfin 

We'll be waiting for your PR. Meanwhile, I will close this issue.
In case you have questions, feel free to ask them!
