### ISSUE TITLE
Error when extending "Printer Management" page for cloud development

### ISSUE THREAD

**Issue by wdet** [microsoft/ALAppExtensions#12219]
When we try to extend the "Printer Management" page then we get the following error: "The type or method 'Printer Management' cannot be used for 'Cloud' development'.
We tried this on Business Central 17 and 18.

This should be allowed according this yammer post (https://www.yammer.com/dynamicsnavdev/#/threads/show?threadId=391013287624704)

@JesperSchulz

**Comment by JesperSchulz** [comment]
We'll investigate. Stay tuned!

**Comment by JesperSchulz** [comment]
I've transferred the issue to our compiler team. I can't quite make sense of the error.

**Comment by qutreson** [comment]
The Printer Management page uses the virtual table Printer (2000000039) as source table and this table is marked with Scope OnPrem. When creating a page extension in AL, you get access to the source table (Rec) which is why the AL compiler does not allow to extend a page that has an OnPrem source table within a Cloud extension.

We have created repair items for improving the error message from the compiler and to update the online documentation about the Scope attributes and properties to mention this scenario.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
