### ISSUE TITLE
[Event Request] Codeunit Item Templ. Mgt. - function InsertTemplateFromItem

### ISSUE THREAD

**Issue by pieter-kok** [microsoft/ALAppExtensions#12545]
Dear team,

To be able to also use the action 'Save as Template' on the Item Card for custom fields, I would like to ask you to add a new event in codeunit 1336 "Item Templ. Mgt." in function InsertTemplateFromItem. I was thinking about something like:

![image](https://user-images.githubusercontent.com/34770900/119650441-22fc6b00-be24-11eb-8e60-4551d5be19e8.png)

Thanks in advance.

Pieter

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
