### ISSUE TITLE
Possibility to get target record from "Price Calculation Buffer Mgt." (Price Calculation V16)

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#12898]
We need the possibility to get the record for which the price is calculated in codeunit "Price Calculation Buffer Mgt.".
For this, we have added a field in table "Price Calculation Buffer" to get the record. This looks like this:
![image](https://user-images.githubusercontent.com/34675109/122423455-38316900-cf8e-11eb-8b96-a25aac5e41c2.png)
But maybe it is better to have a global procedure in "Price Calculation Buffer Mgt." to get the record.
Or are there better ways to get the target record id in Price Calculation V16?

**Comment by StanPesotskiy** [comment]
Price Calculation V16 is supposed to work with any record that needs a price/discount calculation and all logic that is unique for a certain record should be in codeunits that  are between the initial record and price calculation buffer, e.g.  Table 37 Sales Line - codeunit 7020 "Sales Line - Price" - table 7007 "Price Calculation Buffer". Price Calculation V16 works with "Price Calculation Buffer" not knowing what was the actual source for it. In order to extend calculation you need to go this way as well, you add fields to "Price Calculation Buffer" and fill them by subscribing to OnAfterFillBuffer(). Ask for more events if this is not enough.

Why do you need the target record in Price Calculation V16? What would you do with it? Can you share a mock of the code that would work for you?
