### ISSUE TITLE
[Event Request] Preview Posting

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/ALAppExtensions#1301]
Hi!

In some cases, I need to run preview posting without show Preview Posting Page so that I can check posting transaction before real posting.

**1.** So, please public the **RunPreview** function of **Codeunit 19 Gen. Jnl.-Post Preview** for extension.
![image](https://user-images.githubusercontent.com/24407031/53064286-d796dc00-34f9-11e9-94bd-836f4427824e.png)

   And provide a function to GetEntries from Codeunit 20 Posting Preview Event Handler for extension.
   Ex: GetEntries(TableNo: Integer, ReturnEntry: RecordRef);

OR

**2.** Another solution, please provide a function to run preview and get Posting Transaction without show Preview posting page.

**Comment by StanPesotskiy** [comment]
We added the call of Preview() into Codeunit 19 "Gen. Jnl.-Post Preview" OnRun() trigger.
It requires COD19.SetContext() and call 'IF COD19.Run() THEN' to suppress the empty error message and then get access to entry buffers via the preview handler.
It is also possible to activate ErrorMessageMgt to collect error messages.
```
    ErrorMessageMgt.Activate(ErrorMessageHandler);
    BindSubscription(SalesPostYesNo);
    GenJnlPostPreview.SetContext(SalesPostYesNo, SalesHeader);
```
Run() always returns false due to the empty error in the end to revert the transaction, but IsSuccess() helps identify if it was an expected failure or not :
`     IF NOT GenJnlPostPreview.Run() AND GenJnlPostPreview.IsSuccess() THEN ...`
After the run get content of the buffers stored in the preview handler:
```
    GenJnlPostPreview.GetPreviewHandler(PostingPreviewEventHandler);
    PostingPreviewEventHandler.GetEntries(Database::"Cust. Ledger Entry", RecRef);
```
and get an actual error message:
`    ErrorMessageMgt.GetLastError(ErrorMsg);`
