### ISSUE TITLE
Bulk insert during posting documents

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#13042]
codeunit 20 "Posting Preview Event Handler"
Has OnAfterInsertEvent subscribers on entry tables:
Item Ledger Entry
Value Entry
G/L Entry

codeunit 5152 "API - Update Referenced Fields"
Has OnAfterInsertEvent subscribers  on line tables:
Sales Shipment Line
Purch. Rcpt. Line

does this means the bulkinsert posibility is killed during posting documents?

what if both these codeunits would use Manual binding of subscriptions, would this restore the bulkinsert posibility during posting documents?

**Comment by nikolakukrika** [comment]
does this means the bulkinsert posibility is killed during posting documents?
Correct, the bulk inserts will not be used during posting documents

what if both these codeunits would use Manual binding of subscriptions, would this restore the bulkinsert posibility during posting documents?
We cannot do that because it would lead to data inconsistencies. Also if we would flip these two codeunits to manual binding it would not help much. There are many extensions that subscribe to the tables above, we also raise events during the posting, thus the bulk inserts would be disabled. 

If you have the issue OnPrem, you can change the code to manual binding or delete it.
