### ISSUE TITLE
[Event Request] table 18 Customer - OnAfterOnInsert

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13122]
We would like to add a new event OnAfterOnInsert in the following trigger:

    trigger OnInsert()
.
.
.
        UpdateReferencedIds;
        SetLastModifiedDateTime;
        OnAfterOnInsert(Rec, xRec); //A108F0020.Event

Event signature:

local procedure OnAfterOnInsert(var Customer: Record Customer; var xCustomer: Record Customer)
    begin
        //A108F0020.Event
    end;

**Comment by db-bc** [comment]
I'm curious why anyone would need a new event publisher, when system table events `OnBeforeInsertEvent` and `OnAfterInsertEvent` exist?

I guess it makes a little more sense here, since a new 'custom' event would only be fired if the custom `OnBeforeInsert()` did not `exit` from `IsHandled`. But I wonder if it's really strictly required.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
