### ISSUE TITLE
[Event Request] table 5407 "Prod. Order Component" - OnValidateExpectedQuantityOnAfterCalcRemainingQty

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13350]
We would like to add a new event OnValidateExpectedQuantityOnAfterCalcRemainingQty in the following trigger:

            trigger OnValidate()
            begin
                if Item.Get("Item No.") then
                    if Item."Rounding Precision" > 0 then
                        RoundExpectedQuantity();

                if not ExpectedQtyBaseCalculated then //A200F0000.n
                    "Expected Qty. (Base)" := Round("Expected Quantity" * "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
                if (Status in [Status::Released, Status::Finished]) and
                   (xRec."Item No." <> '') and
                   ("Line No." <> 0)
                then
                    CalcFields("Act. Consumption (Qty)");

                OnValidateExpectedQuantityOnAfterCalcActConsumptionQty(Rec, xRec);
                "Remaining Quantity" := "Expected Quantity" - "Act. Consumption (Qty)" / "Qty. per Unit of Measure";
                if ("Remaining Quantity" * "Expected Quantity") <= 0 then
                    "Remaining Quantity" := 0;
                OnValidateExpectedQuantityOnAfterCalcRemainingQty(Rec, xRec); //A200F0000.Event
                "Remaining Qty. (Base)" := Round("Remaining Quantity" * "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
                "Completely Picked" := "Qty. Picked" >= "Expected Quantity";

                ProdOrderCompReserve.VerifyQuantity(Rec, xRec);

                "Cost Amount" := Round("Expected Quantity" * "Unit Cost");
                "Overhead Amount" :=
                  Round(
                    "Expected Quantity" *
                    (("Direct Unit Cost" * "Indirect Cost %" / 100) + "Overhead Rate"));
                "Direct Cost Amount" := Round("Expected Quantity" * "Direct Unit Cost");
            end;

Event Signature: 

    [IntegrationEvent(false, false)]
    local procedure OnValidateExpectedQuantityOnAfterCalcRemainingQty(var ProdOrderComponent: Record "Prod. Order Component"; xProdOrderComp: Record "Prod. Order Component")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by Duizy1971** [comment]
Hi Jesper and Co.,

I finally found out what was done differently with my request. Instead of the requested
OnValidateExpectedQuantityOnAfterCalcRemainingQty(Rec, xRec)
I got a 
local procedure OnBeforeCalcBaseQty(ProdOrderComponent: Record "Prod. Order Component"; CurrentFieldNo: integer; Qty: Decimal; FromFieldName: Text; ToFieldName: Text; var Result: Decimal; var IsHandled: Boolean)

I have a couple of issues with this:
1. Parameter ProdOrderComponent is not var
2. Missing xRec
3. FromFieldName and ToFieldName are actually FromFieldCaption and ToFieldCaption. Quite confusing
4.  Same request in table 5406 "Prod. Order Line" is done with an OnAfterCalcBaseQty event. Why the different signature?
