### ISSUE TITLE
[Even Request] CU5817 Function CheckItemLedgEntries

### ISSUE THREAD

**Issue by TristanKuesters** [microsoft/ALAppExtensions#13563]
We would like to enable with our ISV solution the possibility to undo/cancel an item ledger entry when a charge item is assigned to it. We can already cancel an invoice with a charge item.

The undo / cancel of the item ledger entry is currently not possible due to a check in the CU 5817, function CheckItemLedgEntries which prevent this. And there is no event or similar to avoid the check.

Please make an adjustment possible.

Kind regards,
Tristan Küsters

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.
