### ISSUE TITLE
[Event Request]T5900::Bill-to Customer No. - OnValidateEvent

### ISSUE THREAD

**Issue by Lukoey** [microsoft/ALAppExtensions#13587]
Please add a Event with a ishandeld at the beginning of the OnValidate from the field Bill-to Customer No.

We made several changes to the OnValidate.

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.
