### ISSUE TITLE
[Function-Expose] TAB1173 Document Attachment - SaveAttachment

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#1393]
Can the `SaveAttachment` function be made external please in TAB1173 Document Attachment ?

`SaveAttachment(RecRef : RecordRef;FileName : Text;TempBlob : Record TempBlob)`

**Comment by RomanZanizdra** [comment]
Hi. We don't have plans to make this function externally available for AL development.

**Comment by SirBETE** [comment]
Unfortunately ...
Our client would like to add attachments to Sales orders quicker.
Therefore I could create an 'upload' action, where the chosen document would be uploaded and saved.
But can't do it without that function.

Perhaps do you know another way?

**Comment by RomanZanizdra** [comment]
Let me think a little about this.

**Comment by SirBETE** [comment]
Thank you :)
Or if MS could provide an 'Add attachment' button on sales order list and card that directly opens the 'upload file' screen and saves it, would also be very nice :D

**Comment by RomanZanizdra** [comment]
The first thing I want to mention, attachments are already on the order card (picture below). For the reasons (which I don't know) this factbox is not visible by default on order list page but it's also there (you can manage visibility of controls via extensions).

![Capture](https://user-images.githubusercontent.com/43471583/61934597-60c2ab00-af91-11e9-8d72-05a2da3f605e.JPG)

The next thing is that we can try to discuss with you the redesign of the SaveAttachment function. I mean it can be actually split into two function: one is for file open and upload into stream (this function will not be available for AL development), second function which is actually SaveAttachment will take stream instead of file and blob and do what it does now. But I'm afraid second variant cannot be processed via "request for external", this should be kind of "extensibility" request. Let me know your thoughts on that.

**Comment by SirBETE** [comment]
Ah yes, we overlooked on that fact box.

The function split would be very interesting and would help us a lot. :)
It would be very kind of you if you could implement that.
