### ISSUE TITLE
Price Interface - Cannot use it to find vendor with the lowest price

### ISSUE THREAD

**Issue by MajorBarf** [microsoft/ALAppExtensions#13950]
There does not seem to be any way to use the price interface to answer the question "which vendor can offer me the lowest price on this item". I have setup a requisition line for the item, with a quantity/UOM/date etc. but no vendor number. I then push it into the price interface to find the prices but no purchase prices are returned. On debug, it sets a filter for the vendor no. - which is blank - and so no prices are found.

It is possible to go straight to the tables/codeunits and work this out, but the purpose of the price interface is that this should not be required.

**Comment by StanPesotskiy** [comment]
Does this scenario work with the old price implementation? If so could you put more details about reprosteps?

If not, then in the scope of the new implementation this scenario wasn't included and it is not a natural thing that would become available because of the new implementation. Our goal was to give at least the same abilities as in old pricing, bringing some more due to unification of data structure (e.g. starting/ending dates work for all now), and allow extending it easier. 
If you cannot achieve your goal by adjusting price sources list using the existing events you could ask for an event in CopyLinesBySource of codeunit 7002 "Price Calculation - V16" to be able to correct filters just before price lines are collected.
