### ISSUE TITLE
Extend field length to be able to handle more complex production order scenarios

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#14443]
Hi Team, is it possible to extend the field length of both fields "Next Operation No."(ID 5) and "Previous Operation No," (ID 6) in tables "Routing Line" (99000764), "Prod. Order Routing Line" (ID5409) and "Planning Routing Line" () 99000830 from Code30 to at least Code80 or better Code100. 
In more complex production scenarios with parallel operations the code30 fields limits the max no of parallel routings with typical "3-Digit operation no." to a maximum of 7 parallel operations.

With extending the fields to Code80 or better Code100 this limit will no longer hurt these complex production scenarios.

Best Regards
Andre

**Comment by AlexanderYakunin** [comment]
Unfortunately we cannot make this extensibility request. Any change of field name is breaking change and we are not allowed to do that. The only way is to obsolete existing fields, add new fields with larger length and refactor whole code to use new fields instead of old ones. This is possible in principle, but effect on existing partner's solutions will be significant, and our internal engineering cost will be quite high. My recommendation for you is to create and idea on aka/ms/bcideas site and try to get many votes for this ask. In this case we will be able to add this to our backlog and work this out.
