### ISSUE TITLE
Pitfalls of IsHandled pattern

### ISSUE THREAD

**Issue by gntpet** [microsoft/ALAppExtensions#15037]
Recently we fall into the trap of IsHandled pattern with 3rd party development company that does development for the same customer.

As an example I use standard codeunit "Job Queue - Send Notification". There the 'Run' method has two events OnBeforeRun, & OnAfterRun. Our functionality subscribes to the OnAfterRun event and implements some logic there. Another extension subscribes to OnBeforeRun and uses IsHandled pattern to completely override standard code. It leads to the situation, that event OnAfterRun is never triggered. 
![image](https://user-images.githubusercontent.com/16342128/139601346-5d5ec68d-0af8-4f45-9b46-056089d04989.png)

There are multiple ways to mitigate this problem, which were discussed on Yammer [discussion](https://www.yammer.com/dynamicsnavdev/threads/1437227862482944):

You can find all occurrences where Ishandled pattern disables other events by using this regex:

`if IsHandled then(?=(?:(?!^    end;).)*(^\s+OnTest|^\s+OnCheck|^\s+OnAfter|^\s+OnSet|^\s+OnCalc|^\s+OnMove|^\s+OnInsert|^\s+OnDrill|^\s+OnEvaluate|^\s+OnBefore|^\s+OnModify|^\s+OnDelete|^\s+OnHandle|^\s+OnPost|^\s+OnSubstitute|^\s+OnDelegate|^\s+OnCreate))`

I run it on baseApplication (19.0.29894.30693) and got 698 hits
![image](https://user-images.githubusercontent.com/16342128/139601457-4b580f67-4e57-498b-b58b-0bfc4d121968.png)

Best Regards, 
Gintautas

**Comment by hhfiddelke** [comment]
I made a small modification to your Search expression to also respect "if not IsHandled"
`if (not|) IsHandled then(?=(?:(?!^ end;).)*(^\s+OnTest|^\s+OnCheck|^\s+OnAfter|^\s+OnSet|^\s+OnCalc|^\s+OnMove|^\s+OnInsert|^\s+OnDrill|^\s+OnEvaluate|^\s+OnBefore|^\s+OnModify|^\s+OnDelete|^\s+OnHandle|^\s+OnPost|^\s+OnSubstitute|^\s+OnDelegate|^\s+OnCreate))`
I ran the test on complete source of BC19.0 downloaded from Docker where Notepad++ found 1712 entries and 2141 entries with my modified version.

What we did not check here are the triggers that will be called during Validate/Modify/Insert or Delete and also not the events that are called in a function that is called after the "IF IsHandled"- Statement. So i would think you have to multiply the found quantity by 4 or 5 in minimum. at the end a quantity of missing events a developer is able to check nor  he will check.

**Comment by gintuoklis** [comment]
thanks @hhfiddelke, 
I further adjusted your script, since it did not work nicely for me. include spaces within the match, and made it as non-capturing group. 

`if(?> not | )IsHandled then(?=(?:(?!^    end;).)*(^\s+OnTest|^\s+OnCheck|^\s+OnAfter|^\s+OnSet|^\s+OnCalc|^\s+OnMove|^\s+OnInsert|^\s+OnDrill|^\s+OnEvaluate|^\s+OnBefore|^\s+OnModify|^\s+OnDelete|^\s+OnHandle|^\s+OnPost|^\s+OnSubstitute|^\s+OnDelegate|^\s+OnCreate))`

it's down to 1032 matches now

**Comment by AlexanderYakunin** [comment]
Hello, is this request to fix issue in "Job Queue - Send Notification"? Or more generic ask to fix it all?

**Comment by hhfiddelke** [comment]
To me it's a generic issue, you will not be able to fix without loosing functionality also in this specific case, because calling OnAfterRun after the encapsulation of the RecordLink- Creation before with a  "If not IsHandled then begin..." is not an option.
Because RecordLink might not be filled during OnBeforeRun.

**Comment by gintuoklis** [comment]
Hey @AlexanderYakunin, 

First of all, I hope you will take closer evaluating event requests with IsHandled pattern, not to make things even more complicated than it is now. 

Then it comes to this code on "Job Queue - Send Notification" I used it just an example because it short & clear. If you ask me how to fix it, I would move this code (event + recordlink update) to separate function. Thus, isHandled would affect only single function, and leave OnAfterRun there as it is. Yes, it leaves a chance that OnBefore subscriber does not update RecordLink (as @hhfiddelke mentions), but you could handle this case in OnAfter.. event aswell. 

In general, isHandled should be used on functions that has single task only. Thus, handling such a functions could be seen as function override in C#. 

Based on our regex you have 1032 cases like this. I don't think you can refactor everything at once. Perhaps you could incorporate it when you refactor base application. I see you already did a good job on System Application, where we don't have any case like that. 

Best Regards, 
Gintautas

**Comment by hhfiddelke** [comment]
> In general, isHandled should be used on functions that has single task only. Thus, handling such a functions could be seen as function override in C#.
This does not realy help, because every record modification or validate in the "single" task may cause other triggers end events to be called without notice. And a function call in a this 'single' task may also contain events that will not be called if IsHandled.
Sorry, but the only secure way is to remove IsHandled, but i would think then the AppStore would become very empty.

And the big difference between C# and BC in function override is that you are normaly the only one that uses the overridden functionality in your program. In BC others may modifiy the program flow via plugins (events/triggers), that have to be called in the right order. This will fail also in C# if the overriden base code contains the call to a plugin that isn't called anymore by your overriding function.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
