### ISSUE TITLE
[Event Request] codeunit 427 ICInboxOutboxMgt – New Event “OnBeforeInsertICOutboxJnlLine”

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/ALAppExtensions#15054]
Hello
Could we please have a new publisher “OnInsertICOutboxJnlLine” in all “OnInsertICOutboxJnlLine” functions in codeunit 427 ICInboxOutboxMgt, including de from JnlLine and the outboxJnlLine?
This kind of event already exists for sales & purchase Doc (ex: OnBeforeICInboxSalesHeaderInsert(ICInboxSalesHeader, ICOutboxPurchHeader);) that is useful when we need to have some new data to exchange in IC.

Example of existing code in the same codeunit :
```
procedure CreateOutboxSalesDocTrans(SalesHeader: Record "Sales Header"; Rejection: Boolean; Post: Boolean)
...
OnBeforeICOutboxTransactionCreatedSalesDocTrans(SalesHeader, SalesLine, ICOutBoxSalesHeader, OutboxTransaction, LinesCreated, Post);
OnInsertICOutboxSalesDocTransaction(OutboxTransaction);
end;
```

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by YvesDesrumaux** [comment]
Hello,
The expected Event has been add in v19.1 (see below). Thanks a lot
```
[IntegrationEvent(false, false)]
local procedure OnInsertOutboxJnlLineOnBeforeICOutboxJnlLineInsert(var ICOutboxJnlLine: Record "IC Outbox Jnl. Line"; TempGenJournalLine: Record "Gen. Journal Line" temporary)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
