### ISSUE TITLE
Codeunit 4514 "SMTP Message" - OnBeforeAddFrom

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#15231]
I previously requested this event (https://github.com/microsoft/ALAppExtensions/issues/14708) and appreciate how quickly it was implemented.

However what I failed to realize is that codeunit 4514 "SMTP Message" is not accessible externally (Access = Internal), and therefore we can't subscribe to that event.

What, if anything, can be done to make the event accessible?

**Comment by mazhelez** [comment]
Hi @complord 

Indeed, the event isn't visible as the codeunit itself is internal.

We'll try to process the issues as soon as possible. 

If you feel inpatient and confident, try and contribute a new solution yourself :)

**Comment by complord** [comment]
Hi @mazhelez,

As I am both impatient and confident ;), and I will look at contributing.

**Comment by complord** [comment]
Question:

Would it be allowed for codeunit 4514 "SMTP Message" to trigger an event in codeunit 9520 "Mail Management"?

Codeunit 4514
```
    [TryFunction]
    procedure AddFrom(FromName: Text; FromAddress: Text)
    var
        EmailAccount: Codeunit "Email Account";
        MailManagement: Codeunit "Mail Management"
        InternetAddress: DotNet InternetAddress;
    begin
        MailManagement.OnBeforeSMTPAddFrom(FromName, FromAddress);  //MODIFIED
        if EmailAccount.ValidateEmailAddress(FromAddress, false) and InternetAddress.TryParse(FromAddress, InternetAddress) then begin
            InternetAddress.Name(FromName);
            Email.From().Add(InternetAddress);
        end else
            Error(FromEmailParseFailureErr, FromAddress);
    end;
```

Codeunit 9520
```
    [IntegrationEvent(false, false)]
    procedure OnBeforeSMTPAddFrom(var FromName: Text; var FromAddress: Text)
    begin
    end;

```

**Comment by darjoo** [comment]
Hi @complord,

We'd prefer not to have a dependency on Base App from this app if possible. And it looks like the SMTPConnector.Codeunit.al shouldn't be internal & the event OnBeforeAddFrom could be there instead for subscribing purposes.

However, I'd like to ask what is the scenario you need this for? Because the only time this would be used is when the message is being built with the provided from name & email. It also looks like an old event which we ended up leaving in but isn't used anywhere. 
My assumption here is that you're trying to replicate the send as from the old SMTP Mail Setup?

**Comment by darjoo** [comment]
If being able to just subscribe to OnBeforeAddFrom is enough, I'll make the following changes to allow that to happen.

- [ ] Make SMTPConnector.Codeunit.al external
- [ ] Move OnBeforeAddFrom, from SMTPMessage to  SMTPConnector.Codeunit.al so that it can be subscribed to.
- [ ] Telemetry to know if the event actually changed them.

**Comment by darjoo** [comment]
I've made the changes and will port this to be released with 19.3 :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Comment by IceOnly** [comment]
@darjoo  How does the solution looks like?

I think the event destroyes the integrity of the Mail module.
The "Send From" in the "Sent Email" will be set to the orginal Mail Address not the changed one. Also in the Email Editor.

GetAccounts should fire the same event to set the Email Address to the overriden one and there should be unit test to check if every place there the mail from the account is used is overriden correctly.

**Comment by complord** [comment]
I have submitted a pull request with changes that address the integrity concern.

https://github.com/microsoft/ALAppExtensions/pull/15762
