### ISSUE TITLE
Make Sharepoint functions available for SaaS (follow up to #8336)

### ISSUE THREAD

**Issue by redIT-LoPf** [microsoft/ALAppExtensions#15273]
With the issue #8336, the standard funtionalitiy (Save in Excel to SP) has been enabled for SaaS. But we still are not able to use the standard functionality to upload our own files to SP like in versoin <= BC14.

These modifications are needed to use our old solution on BC SaaS:

1. Remove OnPrem Scope from table 2000000114

2. codeunit 9510 "Document Service Management"
Create an overload function to pass a TempBlob instead of a file name
procedure SaveFile(var TempBlob: Codeunit "Temp Blob"; TargetName: Text; Overwrite: Boolean): Text

3. codeunit 9510 "Document Service Management" 
Create a publisher function "OnAfterFindDocumentServiceRec" to modify parameters in function “SetProperties” (for example to change to path/location/repository on SP)
    begin
        with DocumentServiceRec do begin
            if not FindFirst then
                Error(NoConfigErr);

            OnAfterFindDocumentServiceRec(DocumentServiceRec); //New

    [IntegrationEvent(false, false)]
    local procedure OnAfterFindDocumentServiceRec(var DocumentServiceRec:Record "Document Service")
    begin
    end;

**Comment by pri-kise** [comment]
@redIT-LoPf  What is missing you in the current Wrapper Codeunit `codeunit 9560 "Document Sharing"`? 

This codeunit provides at least a way to pass a blob value instead of a filepath.

**Comment by redIT-LoPf** [comment]
@pri-kise As I understand, Document Sharing is based on the OneDrive intergration which is personal for each user. My need is to upload documents in a public SP folder.

**Comment by redIT-LoPf** [comment]
Any news on this request? Will it be accepted? If yes, when will it be available?

**Comment by JesperSchulz** [comment]
Turns out the scope of this work exceeds what can be done as an extensibility-enhancement issue logged here on GitHub. We cannot just flip a few code properties to make things work the way we want to.

There is a logged idea on this topic too though: https://experience.dynamics.com/ideas/idea/?ideaid=e9dfd7a3-1840-e911-867a-0003ff68b621. The reply to that idea of the team owning this functional area is the following:

_Thank you for your feedback. We are considering adding it to our longer term roadmap.
 
Your help is greatly appreciated,
Mike Borg Cardona
Program Manager, Microsoft_ 

As mentioned in the issue #8336, we do have improvements to cloud file-handling planned and we're adding to that story with every release. When we'll get to this particular request, I cannot answer. As always, we need to prioritize according to what will deliver most value - this request hasn't fully made the cut yet.

I'm sorry about the back and forth on this topic. It falls between different teams and for a while, I though we could just revive the old functionality. But that competes with our new story, and hence cannot be done.

Let me try to push for a more detailed plan though. And to get confirmation, that our new and old story indeed cannot / should not peacefully co-exist.

I'll keep this issue open a little longer, until I receive a definite "no go" on this one.

**Comment by JesperSchulz** [comment]
Closing issue, as this does take more coordination to fix. It's not done by simply exposing a few existing procedures. But work is on our roadmap! Also, a new PR was just created, which enables connecting to the SharePoint API: #18635.
