### ISSUE TITLE
[Extensibility Request] Action "Card" on page "Returns-Related Documents"

### ISSUE THREAD

**Issue by ThomasKlockenbusch** [microsoft/ALAppExtensions#15488]
Please make the action "Card" accessible. 

![image](https://user-images.githubusercontent.com/95849274/145392120-ab870bc2-9bef-40b0-8a2a-74cdc63994ac.png)

Action 

![image](https://user-images.githubusercontent.com/95849274/145392132-a6ecf368-38ab-4ef7-bc61-180e38809e14.png)

I don´t know if the code should be on the OnAction Trigger or better in a codeunit with an event to open other document types.

Thx

**Comment by AlexanderYakunin** [comment]
Please explain how you would like to use this in extension?

**Comment by dnpb** [comment]
I presume he wants the code extracted into a public procedure elsewhere, logically on the source table.

**Comment by DavidFeldhoff** [comment]
Thanks for stepping in @dnpb and your comment in the other issue.
But it's not what we're mainly trying to do:
It plays together with this issue
https://github.com/microsoft/ALAppExtensions/issues/15486

We want to extend the option (which has to become an enum) and then we want to react on that extended enum value in this piece of code. Of course it can be extracted to a codeunit procedure or something like that, but our main point is that we want to react to new values. We can do this if Microsoft adds for example an OnBefore Handler with IsHandled or a publisher in the case-else-part where we can open other pages instead of the sales/purchase order or something like that. That's what we (Thomas and me) are requesting for. Can you make that happen?
/David

**Comment by dnpb** [comment]
well, 'please make the action accessible' is not the clearest way to word 'please make the enum `case` extensible' :-)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
