### ISSUE TITLE
Send Remittance Advice Error "A call to MailKit.Net.Smtp.SmtpClient.Send failed with this message: No recipients have been specified."

### ISSUE THREAD

**Issue by RhipeDynamics** [microsoft/ALAppExtensions#15586]
Hi Support,

When sending Vendor Remittance Advice we are getting an error "A call to MailKit.Net.Smtp.SmtpClient.Send failed with this message: No recipients have been specified."

We did a bit of digging and found that it is searching for customers and trying to use the customer's email address rather than vendor's. If the Customer with the same number is not found, it will print the above error, else it might even send the vendor's remittance to the customer.

This is happening in version 19.1.3.xxxxx

Please review

Thanks,
Ilija, Moiz.

**Comment by dnpb** [comment]
This is not a support channel I'm afraid.

**Comment by RhipeDynamics** [comment]
Just looking for a place to report Errors

**Comment by dnpb** [comment]
If it's affecting a released build, you should report via Partner Source. If it's in a preview build, you could try reporting it on Yammer, but it's not guaranteed the right people from MS will see it there. Issues in released builds also should go via Partner Source, not Yammer or anywhere else, so that they can be fixed by MS in updates for affected releases too.

Does that help?

**Comment by dnpb** [comment]
When reporting the error you should also specify how you triggered the sending of the remittance advice emails, via what page, button, options, etc. - so that someone can replicate it and fix if required.

e.g. if using the UK Send Remittance Advice extension, this shouldn't be an issue, as I've never seen the problem and know it calls the correct function to send emails to vendors. You should specify how you send, what wrong function is called, by whom, etc.

**Comment by RhipeDynamics** [comment]
> e.g. if using the UK Send Remittance Advice extension, this shouldn't be an issue, as I've never seen the problem and know it calls the correct function to send emails to vendors. You should specify how you send, what wrong function is called, by whom, etc.

I'm sending the Remittance advice from the Vendor Ledger Entry and the solution is completely standard, just the AU version. It started happening last Friday when the customer got upgraded to version 19.1.xxxxx

**Comment by dnpb** [comment]
What you are seeing might be related the problem(s) discussed on https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1519281109762048

But we don't know since you didn't specify where you found the problem during your "digging"!

In any case the bug should be raised to MS somewhere they are guaranteed to see it, not here which is just for extensibility (and you're not extending, but using a totally standard version)

**Comment by RhipeDynamics** [comment]
Again **I'm sending the Remittance advice from the Vendor Ledger Entries page**,

Thanks for directing me to Yammer, I'll pick it up for there

**Comment by dnpb** [comment]
Putting it in bold doesn't make it any clearer. Not everyone will be familiar with the AU version and whether it has region-specific functionality. And my point was that if you had dug and identified where the wrong function was being called or such, you could simply tell us.
