### ISSUE TITLE
Event “OnAfterCheckWhseActivLine” - codeunit “Whse.-Activity-Register”

### ISSUE THREAD

**Issue by foodware365** [microsoft/ALAppExtensions#15651]
We are using the event “OnAfterCheckWhseActivLine” - codeunit “Whse.-Activity-Register”.

![image](https://user-images.githubusercontent.com/51919856/147574810-3c8d80d8-5cfb-4347-8225-a7e85ac04304.png)

When each line is checked we also run our checks using the event in 2 separate extensions subscribing to this event, this went wrong.
 
Problem Example:
Inventory Movement with lines:
  line 1 : Type Take
  line 2:  Type Place

The code starts checking line 1 (Take) and do the necessary checks:
   - Inside the EventSubscriber its doing a FindSet on the record from line 1 and then it loops thru the lines and does the intended 
      check on the lines. 
   - At the end of the EventSubscriber the record is now pointing to line 2 and changing/replacing the initial record.
As a result other subscribers on the event will only check line 2.  This is risky because of the parameters of the event subscriber (var).

Improvement is to change the event to not use it in the repeat until and use the parameter as var.

**Comment by Stepanenko-Vadim** [comment]
We cannot remove var from parameters, since it can be a breaking change for other scenarios, since there are legitimate scenarios why someone would need this parameter as a var, obsoleting it is not an option also. 
So the solution is to be mindful when using events and modifying parameters passed by var. You can always copy to another record if you intend to modify it in a way that will disrupt the rest of the code.
