### ISSUE TITLE
[Extensibility Request] table 370 "Excel Buffer"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#15825]
Please increase field length to 2048 in table 370 **"Excel Buffer"** field **"Cell Value as Text"**
There are many cases where the data stored in an Excel cell is greater than 250 chars.

```
 field(5; "Cell Value as Text"; Text[2048])
```

**Comment by panas78** [comment]
Its critical because as already stated in many cases data are greater than 250 chars.
Nevertheless i don't understand why you must obsolete the field and create a new one since "Excell Buffer" is exactly that a **buffer** so no db schema is affected by this change.

**Comment by AlexanderYakunin** [comment]
This table is not marked as TableType = Temporary, therefore this is normal table. But we have field for you case:

        field(17; "Cell Value as Blob"; Blob)
        {
            Caption = 'Cell Value as Blob';
            DataClassification = SystemMetadata;
        }

Can you use this?

**Comment by panas78** [comment]
We will use Cell Value as Blob... although 
many tables do not have TableType = Temporary but they always used as buffers.

My suggestion (if that's possible) is to check the use of the table as buffer and if that's the case  then make the change to field length and also make TableType = Temporary.

**Comment by StanPesotskiy** [comment]
@panas78 unfortunately increasing a field length is a destructive change, because some partners could use this field as a parameter in methods of their extensions. If we increase the length it can lead to an overflow error if not a compilation error.
A similar problem with the candidates for temporary buffer status. We did it last year and marked several tables as temporary but still there were a few cases when such a buffer table contained data in a tenant and blocked the upgrade.
