### ISSUE TITLE
[Event Request] Page 232 Apply Customer Entries OnApplyCustomerEntriesOnFindRecord 

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15879]
Please Add an Event OnApplyCustomerEntriesOnFindRecord in Page 232 Apply Customer Entries

```
trigger OnFindRecord(Which: Text): Boolean
    var
        Found: Boolean;
        IsHandled: Boolean;
    begin
        OnApplyCustomerEntriesOnFindRecord(Rec, Which, Found, IsHandled);
        if IsHandled then
            exit(Found);
        exit(true);
    end;
```

```
[IntegrationEvent(true, false)]
    local procedure OnApplyCustomerEntriesOnFindRecord(CustLedgerEntry: Record "Cust. Ledger Entry"; Which: Text; var Found: Boolean; var IsHandled: Boolean)
    begin
    end;
```

Thank You!

**Comment by Stepanenko-Vadim** [comment]
We cannot add an empty trigger, since in will break default behavior of this page, so we cannot add such event

**Comment by akontos** [comment]
Please Check the Code. It won't break anything. You already did that in page 554 "Analysis by Dimensions"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by dcenic** [comment]
@akontos We had to remove this event and the OnFindRecord trigger, because just having that trigger on the page, introduces a severe performance regression that affected over 400 live users on Business Central Online. If you need custom code in OnFindRecord and OnNextRecord on "Apply Vendor Entries" and "Apply Customer Entries", we suggest that you make a copy of these pages and implement those triggers in your copy of the page. Also, extend places in Business Central where these pages are invoked from, and invoke your copy of the page. We removed all 4 events that were requested in:
https://github.com/microsoft/ALAppExtensions/issues/15879
https://github.com/microsoft/ALAppExtensions/issues/15880
https://github.com/microsoft/ALAppExtensions/issues/15881
https://github.com/microsoft/ALAppExtensions/issues/15882
