### ISSUE TITLE
[Scope Change] page 2616 "Printer Management" - extensions are not possible

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/ALAppExtensions#15988]
Please could you change the scope of the page so that we can implement another kind of Printers.
The property "Extensible" is set to true, but we get an error message while creating PageExtension : "The application object or method 'Printer Management' has scope 'OnPrem' and cannot be used for 'Cloud' development."
Then, it is not possible to add new setup action. :(

**Comment by JesperSchulz** [comment]
The Printer Management page uses the virtual table Printer (2000000039) as source table and this table is marked with Scope OnPrem. When creating a page extension in AL, you get access to the source table (Rec) which is why the AL compiler does not allow to extend a page that has an OnPrem source table within a Cloud extension.
As the table is a virtual table, we cannot simply change the scope from within the application. I will forward your request to our platform team, but I am not sure they want to change the scope of this platform table. Let's see.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
