### ISSUE TITLE
[Extensibility Request] Page 9802 "Permission Sets" - Protected variables

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16425]
Hello, we need the following currently global variables defined as protected for our page extension. Can you please check that? Thank you!

    protected var
        CanManageUsersOnTenant: Boolean;
        [InDataSet]
        IsPermissionSetEditable: Boolean;
        UsePermissionSetsFromExtensions: Boolean;

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this?

**Comment by MarkoMilosavljevic** [comment]
Hello Alexander, 

we need var CanManageUsersOnTenant as protected, to use the same variable value for Enabled property for 2 custom Actions which we add to Page extension, and also for one standard Action (RemoveObsoletePermissions), which we modify and transfer in Page extension. After the additional check, I realize that we do not need var IsPermissionSetEditable, and I apologize for that one. And we need var UsePermissionSetsFromExtensions to define Visible property in the standard Action (RemoveObsoletePermissions), which we modify and transfer in Page extension.

**Comment by AlexanderYakunin** [comment]
Hello!

I need to understand the purpose of your changes first. What kind of extension you are doing, why you need access to internal implementation in security system. We cannot make such changes in permission subsystem without security review.

**Comment by miljance** [comment]
Hi,

I would like to provide the clarification as Marko is working on converting one of our solution according to Business Central Universal code initiative.
The goal at this point is to transfer all of the modifications to the extension. Along the way the page "Permission Sets" is being processed. As this solution was not compatible with concepts from Business Central Universal code initiative an Action has to be moved to the Page Extensions. This actions is actually trying to replace the action "Remove Obsolete Permissions". The action "Remove Obsolete Permissions" uses boolean variables "UsePermissionSetsFromExtensions" and "CanManageUsersOnTenant" in order to manage visibility and whether action is enabled. The new Action on a Page Extension should replicate the behaviour of "Visibility" and "Enabled" properties. 
The background for this new action is that user defined permission sets are used, permissions for objects types other than TableData are also being assigned (Pages, Codeunits, Reports, Queries and  XMLPorts)  and objects may be deleted for OnPrem solution. Currently the standard action only affects table data that is marked as obsoleted but not deleted.

This problem however be solved in different ways:
1. **Disable the standard action and introduce the new action on a page extension.** In this case the variables "UsePermissionSetsFromExtensions" and "CanManageUsersOnTenant" can either be marked as protected or a variables on a page extension can be used.
2. **Introduce an Event (potentially with Handled pattern) inside of an action** in order to be able to delete not only Table Data that are marked as obsolete but also other object types that no longer exist and also do that for removed objects.
3. **Microsoft can adapt the current action** so that it process also other objects types and also removed objects. Sounds unlikely to happen as the focus is on new permission objects and the ideas to make permission sets more secure does not seem to get the traction we would like it to get: https://experience.dynamics.com/ideas/idea/?ideaid=0a1a522c-e685-e911-80e7-0003ff68897c
4. **We as an ISV can change our legacy** and abandon using user defined permissions and setting permissions on specific object types. This scenario is also not that likely to happen that soon but may happen in the future according to the Business Central Universal code initiative guidelines.

@AlexanderYakunin I would definitely would like to hear you opinion on this topic and what your (official?) suggestion would be.

 @MarkoMilosavljevic Can you confirm this writing so that it does not sound as I have hijacked someone elses topic?

**Comment by MarkoMilosavljevic** [comment]
Confirm :-)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.
