### ISSUE TITLE
Table 12104 "Withhold Code" - field 5 "770 Code" lenght to increase

### ISSUE THREAD

**Issue by gpintaudi** [microsoft/ALAppExtensions#16558]
Hi,
as per new Italian regulatory update on 2022 Withholding Tax Export, field "770 Code" can be used with 2-digit values.
Actually field 5 "770 Code" is Text[1]

Can you please increase field lenght to be compliant with the above regulatory update?

Thanks

**Comment by gpintaudi** [comment]
Hi @AlexanderYakunin, this issue is still in status Open. 7 months has been passed without an answer.
Could you please let me know your plan for this issue?

**Comment by AlexanderYakunin** [comment]
We are not working on Regulatory changes. This is another team, and they have this request in their backlog. Please let me know which legal update you are talking about, and I will check with them. Going forward please use support requests to query about legal updates if there is any urgency. This forum is not suitable for that.

**Comment by gpintaudi** [comment]
In this [link](https://www.agenziaentrate.gov.it/portale/documents/20143/4115385/CU_istr_2022.pdf/b299f3e2-fe89-daeb-4af8-18580e367f8f) you can find istructions, in italian, for 2022 declaration (page 75-76 you can see codes can be 2 digit).
Next declaration is expected in January 2023.
Morover, you can take into consideration that in technical specification, this field is exported in a non-positional record. So potentially in future it can be higher than 2 chars.
![image](https://user-images.githubusercontent.com/64265795/197960480-54033025-56a4-4ca8-86c8-3a8e922bf168.png)

**Comment by AlexanderYakunin** [comment]
Hello! 

Thank you for this information!

We investigated this case and see that this field is not used anywhere except table and page in current implementation. Our Regulatory Features team is willing to investigate it further as we may miss something important in this declaration export. In order to get it done we need to have technical support experts working on this case, please open service request instead of this GitHub requests, using one of possible methods:

•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
