### ISSUE TITLE
FastTab in "Item Card" always Collapsed - BC OnPremise 19.0

### ISSUE THREAD

**Issue by Michel-up** [microsoft/ALAppExtensions#17044]
On opening "Item Card" page: "Planning" "Item Tracking" and "Warehouse" FastTabs are always Collapsed, Eventhough the FastTabs were Expanded before closing the page.

Other FastTabs save the state (Collapsed/Expanded) when closing and opening the "Item Card", but it seems these 3 FastTabs dont.

![2022-04-05_131721](https://user-images.githubusercontent.com/92575139/161742546-60920c66-8a9f-483c-8bf8-115fbf029a38.png)

**Comment by dnpb** [comment]
This was discussed on Yammer. It'll be because they have conditional visibility. This doesn't seem related to AL extensibility in any case.

**Comment by Michel-up** [comment]
can you please elaborate, why does these 3 fasttabs have conditional visibility? can we overwrite this conditional visibility?

**Comment by dnpb** [comment]
I don't know; I didn't develop the base application... You could probably override the Visible property in an extension, but it might be the case that having an explicitly set value, even if constant (instead of conditional), would defeat the user's last remembered expand/collapse state.

The Yammer thread I mentioned is here. MS quoted the internal reference 417407
https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1512967933386752

Anyway, to me (as Just Another User) it does seem like a platform issue, rather than one for extensibility in AL or the base apps.

**Comment by Michel-up** [comment]
when you say Platform issue, you mean i should post this issue in another place?
its odd when you have a page with 9 fasttabs, where 6 of these fasttabs saves the last state of the user expand/collapse, while the other 3 doesn't? i think all fasttabs should behave the same

**Comment by RomanZanizdra** [comment]
Hi @Michel-up.
I've checked our internal issue and it is marked as fixed. So, the fix is available in 19.6 or 20.1. Please verify when you will be updated. I'll close your request for now, feel free to open a new one if something will be wrong.
