### ISSUE TITLE
Missing SumIndexFields for Service Line Table 5902 Primary Key

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#17176]
From NAV 14, we could see several SumIndexFields for the primay key of Service Line table 5902.  It seems that they are missing for the later BC versions.

NAV 14.
![image](https://user-images.githubusercontent.com/49729094/162538043-8c5ab90c-dc74-4a66-aa98-c94337ac7f3f.png)

BC 19 for the same table - 
![image](https://user-images.githubusercontent.com/49729094/162538186-ea73534c-7b10-4869-9d93-2bbd741a5b07.png)

Is it possible?   Thanks very much.

**Comment by RadoArvay** [comment]
Why do you need them there?

**Comment by AlexanderYakunin** [comment]
There is no need for SIFT on primary key, we even have special code cop rule to prevent it. 

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0222

**Comment by dnpb** [comment]
Some elaboration on why not would be nice - the warning could link to the relevant BC page, which should be updated with info on why it's not useful anymore - I guess because the Classic database engine benefited from SumIndexFields on PKs but SQL Server for some reason does not. I can't quickly find any info on why this isn't needed/desirable anymore. It would be nice to.

**Comment by RadoArvay** [comment]
Record selectivity on PK index and amount summary (number of records that is calculated from) are identical.
You could define SumIndexFields but you should set the SIFTMaintanance property (or how it is called) to false value.
