### ISSUE TITLE
[Question and/or Event Request] Codeunit 44 Report Management/Codeunit 2000000005 - Access to RunMode or ReportAction

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#1731]
Dear ALAppExtensions team,

First off my question: Is there any problem in subscribing directly to codeunit 2000000005 Reporting Triggers rather than codeunit 44 ReportManagement?
For example in `SubstituteReport` there is also a parameter `RunMode` that indicates how a report is called, but this parameter is not passed on to publisher `OnAfterSubstituteReport`.
I suspect that the events from the Reporting Triggers codeunit are not supposed to be used, and we are supposed to use the events from codeunit 44 instead, but I couldn't find any information on this.
Could you clarify this?

If we are not supposed to subscribe to the events in the Reporting Triggers codeunit directly, then could you add a new parameter or a new event that provides access to the `RunMode` of a report?

**Comment by CanuckNav74** [comment]
I would further strongly suggest to Microsoft that codeunit 44 OnAfterSubstituteReport has the same parameter signature as codeunit 2000000005 SubstituteReport. 

The limitations of codeunit 44's implementation of SubstituteReport is very concerning.

I'm currently upgrading a NAV 5.0 client to BC SaaS and one of the requirements is to route to a custom report based on record values for the report's pertinent dataitem record. Since  codeunit 44 OnAfterSubstituteReport lacks a var recordref parameter, I cannot do that and thus forces me to subscribe to codeunit 2000000005 instead. 

I understand that extensions shouldn't subscribe to events in object ID 2000000000 range, but I currently have no choice right now. 

Microsoft absolutely needs to revisit their Codeunit 44 OnAfterSubstituteReport  implementation if they ever decide to "close the doors" on codeunit 2000000005 for AL extension developers to event-subscribe to.

**Comment by JesperSchulz** [comment]
Thank you for your feedback. Codeunit 44 is planned for refactoring in the nearer future, where we will consider your feedback. Solution coming up! Stay tuned :)

**Comment by JesperSchulz** [comment]
The signatures have been aligned. The updated codeunit 44 will ship with the June update.
