### ISSUE TITLE
[bug] Any report's Preview does not take into account changes made by user on the request page

### ISSUE THREAD

**Issue by PaulFurlet** [microsoft/ALAppExtensions#17870]
Simple test case:
** Having created two or more Sales Orders (in my case I took Danish demo data)
![image](https://user-images.githubusercontent.com/17279234/167196734-5a171b4d-5daf-4fb5-b057-abee2fe3a1ab.png)
** Select Print/Send -> Print Confirmation
** the request page shows prefiltered Sales Header No. as selected (I have 101002)
![image](https://user-images.githubusercontent.com/17279234/167196928-f6599498-6c2d-4080-a01e-3395eb01b23b.png)
** Change filter for No, to 101005 or any other (does not matter)
![image](https://user-images.githubusercontent.com/17279234/167197081-5af33554-e36b-4d02-9803-d62314d281a3.png)
** click Preview
** you will get the result that was set before user's interaction. e.g. OnOpenPage trigger code still taken into account
![image](https://user-images.githubusercontent.com/17279234/167197215-a57ed61f-c1c1-4fe8-ad21-0a60c037747a.png)

Changing variables added to the request page (e.g. some booleans, enums, codes, you name it) has no effect for the Preview.
When you do Print - all seem to be ok.

Business Central 20.0 (Platform 20.0.37114.40159 + Application 20.0.37253.38055)
the same behavior noticed on BC17.3

**Comment by dnpb** [comment]
Yes, I had some trouble because `OnOpenPage` is still fired even if not running the request page. That happens in this case as 1st MS run the report to get the request page options, then again 2nd later to actually produce the report with the saved options.

However, I think it is intentional, given that diagrams here show it as always being run, even in 'headless request page' mode. Strange, but for once seemingly documented ;-)
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-triggers?tabs=current%2Crdlc

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
