### ISSUE TITLE
[extensibility-bug] Changing source table in page "Feature Management" is a breaking change in BC21

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#18080]
Hi, 
we have discovered that in BC21 the page "Feature Management" has now a different source table ("Feature Key Buffer").
Our CI-Pipeline has run into an error with BC21 because the publishers OnFeatureManagementOnBeforeValidateEventEnabledFor & OnFeatureManagementOnBeforeActionEventSchedule have now a different record as rec variable:

```
src/codeunit/FeatureWarningsMgt.Codeunit.al(4,76): error AL0284: The type of the parameter 'rec' on the event subscriber 'OnFeatureManagementOnBeforeValidateEventEnabledFor' does not match the expected type 'Record "Feature Key Buffer"'.
src/codeunit/FeatureWarningsMgt.Codeunit.al(4,107): error AL0284: The type of the parameter 'xRec' on the event subscriber 'OnFeatureManagementOnBeforeValidateEventEnabledFor' does not match the expected type 'Record "Feature Key Buffer"'.
src/codeunit/FeatureWarningsMgt.Codeunit.al(10,72): error AL0284: The type of the parameter 'rec' on the event subscriber 'OnFeatureManagementOnBeforeActionEventSchedule' does not match the expected type 'Record "Feature Key Buffer"'. at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.7\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
```

Changing the source table should be a breaking change and not be allowed in pages.

**Comment by AndreBreitenbach** [comment]
Some additional Information: This error occurs with BC 21.0.20723. 
With BC 21.0.20423 everything was fine ;)

**Comment by pschwambornMC** [comment]
sure, we have 2 subscribers:
```
    [EventSubscriber(ObjectType::Page, Page::"Feature Management", 'OnBeforeValidateEvent', 'EnabledFor', true, false)]
    local procedure OnFeatureManagementOnBeforeValidateEventEnabledFor(var rec: Record "Feature Key"; var xRec: Record "Feature Key")
```
and
```
    [EventSubscriber(ObjectType::Page, Page::"Feature Management", 'OnBeforeActionEvent', 'Schedule', true, false)]
    local procedure OnFeatureManagementOnBeforeActionEventSchedule(var rec: Record "Feature Key")
```

**Comment by StanPesotskiy** [comment]
@pschwambornMC 
Our gate should have an additional rule to check for. 
If we did it according to the process, the old page would be marked as obsolete and a new page with another source would become visible instead, so your code would never fail because the page would not be used. Would it be better option?

Anyway, it doesn't help you right now. 
Are you able to redefine the subscribers or you would prefer this change to be reverted and reimplemented as I have described above, so your subscribers would die silently and you would add two new that would subscribe to the new page?

**Comment by pschwambornMC** [comment]
I think setting the page to obsolete and creating a new one is the only way to not produce a breaking change here and I would like to see changing a source table of a page cause an error in your/our build process when checking against the previous version. That was my original concern with this issue.

**Comment by StanPesotskiy** [comment]
This request is converted to a slice for the modern dev team to add the rule for catching and stopping change of the source table on a page.

**Comment by nav-lab** [comment]
Not sure why you close this ticket in this way… do you plan to fix or you will release a broken page? This is a case where YOUR pipeline should fail…

**Comment by demiliani** [comment]
Sorry, not sure why you close this ticket in this way… do you plan to fix in a next minor or you will release a broken page? This is a case where YOUR pipeline should fail…

**Comment by AndreBreitenbach** [comment]
> Sorry, not sure why you close this ticket in this way… do you plan to fix in a next minor or you will release a broken page? This is a case where YOUR pipeline should fail…
@demiliani 
We just got an answer that this breaking change will not be reverted! We don't find that particularly funny right now.

**Comment by AlexanderYakunin** [comment]
Dear partners! We still have no information what you are doing with these subscribers. Can you explain, maybe we can find solution together?

We have obsoletion process for ALL of us and you know you need to upgrade your applications timely. In this case, if we obsolete old Feature Management page and introduce new version, we will remove old page after 1 year and it will break ALL partners and customers. Do you consider this issue?

**Comment by AndreBreitenbach** [comment]
@AlexanderYakunin 
My colleague Philipp Schwamborn already explained our problems with our upgrade process in our pipeline in our private yammer conversation because of this breaking change in BC21Insider. 

As you write in your post above: Obsoletion process is for ALL of us. And yes, we know that we have to check all of our apps against next versions, to see obsolete stuff timely. That is the reason (beside others) why we implemented an upgrade process in our pipeline and check against "NextMajor".
