### ISSUE TITLE
Control Names Should Reflect Field Names

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/ALAppExtensions#181]
I understand that the UI simplification is ongoing, but here are some problems that it's causing for us (and probably other extension developers). When Microsoft recaptions a page field (e.g., Ship-to Code on the Sales Invoice page is now just Code, as it is located in the Ship-to section of the page), it breaks our extensions. Our addafter was set to "Ship-to Code", as that's what the field has always been named (and it's named that in 2016, 2017, and earlier builds of 2018). Presumably, Microsoft is going to continue this trend, which is great, but it's wreaking havoc on pageextensions. If you are recaptioning a field on a page, could you please set the control Name to the field name? It's a problem for new extension developers, too. To take that same example, when you are adding a control to the Sales Invoice page, how would someone know that addafter(Code) is referring to the Ship-to Code? "Code" works fine in the UI, but it's not a good control name. We publish our extensions for NAV 2016 and 2017 too, so it would be ideal if the control names could be consistent across NAV versions (even though you might change the captions for simplification).

This is impacting our extensions on the following pages (so if you could revert the control Names on these pages at a minimum, I would appreciate it):
Customer Card
Sales Invoice
Sales Order
Sales Quote
Sales Return Order

**Comment by ikoletic** [comment]
Dev comments below:
1. When we change the field's caption it doesn't lead to extension break as it follows from the github request. When we change the field's name then it can be the reason of extension break. But these cases are quite rare I suppose and we have an effective process for such cases. So I don't see the problem here.

2. The second problem mentioned in the github request is that it difficult to understand what field is going to be reflected on the page because we have several fields with the same caption. While developing extension system refers on the field name but not the caption. Below is a screenshot illustrating extension of the page "Sales Invoice" which has several "Code" caption fields. We see the reference on the field's name but not the caption.
![untitled](https://user-images.githubusercontent.com/24272853/48422645-69ef4d00-e75f-11e8-9200-7f3009be82f6.png)
