### ISSUE TITLE
[Request for external] COD 2000000 PaymJnlManagement - Functions

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/ALAppExtensions#1846]
Could all functions in COD 2000000 PaymJnlManagement be made external please?
They are already all global.

```
TemplateSelection
OpenJournal
CheckTemplateName
OpenJnlBatch
TemplateSelectionFromBatch
CheckName
SetName
LookupName
GetAccount
CalculateTotals
SetUpNewLine
ShowCard
ShowEntries
ConvertToDigit
DecimalNumeralZeroFormat
TextZeroFormat
PrintTestReport
Mod97Test
ModifyPmtDiscDueDate
SetApplID
```

Version: BE Dynamics NAV 13.5 (29614)

**Comment by JesperSchulz** [comment]
Sure, I'll process this one and your other requests right away :-)

**Comment by fvet** [comment]
@SirBETE , did you see those appearing in a BC 14 version?

**Comment by SirBETE** [comment]
> @SirBETE , did you see those appearing in a BC 14 version?

Not in BC14CU0, nor CU2.
So think this will be for BC15?

**Comment by SirBETE** [comment]
@JesperSchulz Sorry to disturb you, but is there a reason why none of these functions are set to external in BC15CU0 ...?

**Comment by JesperSchulz** [comment]
I just checked. They are all external in version 15! Remember, that the new default in al is "external". Unless otherwise specified through the [Scope('OnPrem')] property, the functions are usable by cloud extensions.

Sample:
![image](https://user-images.githubusercontent.com/19796701/70545933-aa8de580-1b6e-11ea-8287-6ef5fa9c419f.png)

**Comment by SirBETE** [comment]
Ahn! ok :D 💡! 
I get it! Thanks! :)
