### ISSUE TITLE
[Exposure Request] Table 30112 Shopify Shop Orders

### ISSUE THREAD

**Issue by Vert1** [microsoft/ALAppExtensions#18681]
Hi, please make the below tables externally available, as we would like to query and add our own processing logic to Shopify order imports

```
table 30118 "Shpfy Order Header"
{
    Access = Internal;
```
```
table 30119 "Shpfy Order Line"
{
    Access = Internal;
    Caption = 'Shopify Order Line';
```
```
codeunit 30161 "Shpfy Import Order"
{
    Access = Internal;
    Permissions = tabledata "Sales Line" = rim;
    TableNo = "Shpfy Orders to Import";

```

**Comment by pri-kise** [comment]
@Vert1 Please check the following yammer post.
https://www.yammer.com/dynamicsnavdev/threads/1762140027789312

> As source code of Shopify Connector is on GitHub we would like to reuse pattern we have for System App:
> 
> Prioritize submitting improvement over extensibility.
-  For example, if your customer needs to export multiple translations of a product to Shopify, instead of asking for making some objects extensible – submit PR that implements this feature.
- If extensibility is really necessary – for example to orchestrate multiple extensions dealing with various sales channels – please create PR directly. Remember to write the proper justification of scenario.
>
> We will not process extensibility requests for connector registered as Issues on GitHub.

**Comment by AlexanderYakunin** [comment]
See above, closing
