### ISSUE TITLE
[Exposure Request] Codeunit 30195 Shopify Inventory API

### ISSUE THREAD

**Issue by Vert1** [microsoft/ALAppExtensions#18680]
Hi, please make the OnAfterCalculationStock event externally available

```
internal procedure GetStock(ShopInventory: Record "Shpfy Shop Inventory") Stock: Decimal
    ...
                    Events.OnAfterCalculationStock(Item, ShopifyShop, ShopLocation."Location Filter", Stock);
                end;
            end;
        end;
```

**Comment by pri-kise** [comment]
@Vert1 Please check the following yammer post.
https://www.yammer.com/dynamicsnavdev/threads/1762140027789312

> As source code of Shopify Connector is on GitHub we would like to reuse pattern we have for System App:
> 
> Prioritize submitting improvement over extensibility.
-  For example, if your customer needs to export multiple translations of a product to Shopify, instead of asking for making some objects extensible – submit PR that implements this feature.
- If extensibility is really necessary – for example to orchestrate multiple extensions dealing with various sales channels – please create PR directly. Remember to write the proper justification of scenario.
>
> We will not process extensibility requests for connector registered as Issues on GitHub.

**Comment by AlexanderYakunin** [comment]
See above, closing
