### ISSUE TITLE
[Exposure Request] Codeunit 30195 Shopify Inventory API

### ISSUE THREAD

**Issue by Vert1** [microsoft/ALAppExtensions#18694]
Hi, in the existing Shopify inventory API codeunit, we use ItemAvailMgt to calc available quantities. This factors in all planned purchase and sales orders when determining the available quantity to show on Shopify for a given date.

We would like the functionality for different inventory calculations to be used. It would be good to add a setup field on the Shopify Shop table called 'Inventory Calculation Method' with the following options:
- Available Inventory - follows the existing logic 
- Location Inventory - only considers inventory in the relevant location as per item ledger entry 
- Location inventory + BOM components- considers inventory in the relevant location, but also adds inventory available to assemble as per the item's BOM

internal procedure GetStock(ShopInventory: Record "Shpfy Shop Inventory") Stock: Decimal
    ...
                    ItemAvailMgt.CalcAvailQuantities(Item, true, GrossRequirement, PlannedOrderRcpt, ScheduledRcpt, PlannedOrderReleases, ProjAvailableBalance, ExpectedInventory, QtyAvailable);
                    Stock := ProjAvailableBalance;

**Comment by AndreiPanko** [comment]
@Vert1 we are planning to enable extensibility for Shopify Connector by next major. If you need extensibility for this specific scenario sooner and ready to submit PR yourselves, please reach out to ShopifyBCSupport@microsoft.com and we can discuss further.

**Comment by AndreiPanko** [comment]
[Allow extensibility of the new Shopify Connector Extension](https://experience.dynamics.com/ideas/idea/?ideaid=ea059be1-9912-ed11-b5cf-0003ff45e42e#)

**Comment by AndreiPanko** [comment]
**Shopify connector becomes extensible: Stock calculation**

Shopify Connector has been non-extensible, but we're changing that. We're offering a few points of extensibility. We'll keep the number of points to a minimum so that we can follow the rapid development on the Shopify side without introducing breaking changes. We are opening for extensibility for specific scenarios, based on feedback from our partners and customers starting with Stock calculation. For more details, please follow this [repository](https://github.com/microsoft/ALAppExtensions/tree/main/Apps/W1/Shopify) on GitHub. Note that even though extensibility is limited, you can submit improvements directly.

Here are examples of different calculations: [ALAppExtensions/extensibility_examples.md at main · microsoft/ALAppExtensions (github.com)](https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/Shopify/extensibility_examples.md). You can implement your formula as well.
