### ISSUE TITLE
[Event Request] Сodeunit "Gen. Jnl.-Post Line" fuction PostDtldEmplLedgEntries

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#18911]
Please add the event in function same as exists for customer and vendor:

`

    procedure PostDtldEmplLedgEntries(GenJnlLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; EmplPostingGr: Record "Employee Posting Group"; LedgEntryInserted: Boolean) DtldLedgEntryInserted: Boolean
    begin
        if GenJnlLine."Account Type" <> GenJnlLine."Account Type"::Employee then
            exit;
        if DtldEmplLedgEntry.FindLast() then
            DtldEmplLedgEntryNoOffset := DtldEmplLedgEntry."Entry No."
        else
            DtldEmplLedgEntryNoOffset := 0;

        DtldCVLedgEntryBuf.Reset();
        if DtldCVLedgEntryBuf.FindSet() then begin
            if LedgEntryInserted then begin
                SaveEntryNo := NextEntryNo;
                IncrNextEntryNo();
            end;
            repeat
                InsertDtldEmplLedgEntry(GenJnlLine, DtldCVLedgEntryBuf, DtldEmplLedgEntry, DtldEmplLedgEntryNoOffset);
                IsHandled := false;
                OnPostDtldEmplLedgEntriesOnBeforeUpdateTotalAmounts(GenJnlLine, DtldCVLedgEntryBuf, DtldEmplLedgEntry, IsHandled);
                if not IsHandled then
                    UpdateTotalAmounts(TempDimPostingBuffer, GenJnlLine."Dimension Set ID", DtldCVLedgEntryBuf);              
                // new event --
                // include sender
                OnPostDtldEmplLedgEntriesOnAfterUpdateTotalAmounts(GenJnlLine, DtldCVLedgEntryBuf, DtldEmplLedgEntry);
                // new event ++
            until DtldCVLedgEntryBuf.Next() = 0;
        end;

        // new event --
        OnPostDtldEmplLedgEntriesOnBeforeCreateGLEntriesForTotalAmounts(EmplPostingGr, DtldCVLedgEntryBuf);**
        // new event ++

        CreateGLEntriesForTotalAmounts(
          GenJnlLine, TempDimPostingBuffer, DummyAdjAmount, SaveEntryNo, EmplPostingGr.GetPayablesAccount, LedgEntryInserted);

        // new event --
        OnPostDtldVendLedgEntriesOnAfterCreateGLEntriesForTotalAmounts(TempGLEntryBuf, GlobalGLEntry, NextTransactionNo);
        // new event ++

        DtldLedgEntryInserted := not DtldCVLedgEntryBuf.IsEmpty;
        DtldCVLedgEntryBuf.DeleteAll();
    end;

`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.

**Comment by elecsach** [comment]
> Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
> 
> Build ID: .

Please what is the latest on this

**Comment by JesperSchulz** [comment]
> > Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
> > Build ID: .
> 
> Please what is the latest on this

@elecsach, this is a resolved issue from 2022. What do yo mean by "What is the latest on this"? Also, why would you ask that question as an issue on the Visual Studio Code team?

**Comment by elecsach** [comment]
I have added a new field in the Employee Posting Group table(Table 5221)
with the following details:

Field No. Field Name Data Type Length Description
50000 Receivables Account Code 20

There is a journal that I automatically generate from a custom built
application that uses this
new field so that when posting the journal instead using the default
account field in the
Employee Posting Group it uses the newly defined account field(Receivables
Account);

Beloaw is the modification to the codeunit 12 in ver 14 of D365 BC which I
want to implement
int D365 BC ver 23.

//<<<<<<<<<<<<<<<Tenecee>>>>>>>>>>>>>>>>
IF GenJnlLine."Employee Receivables" THEN
  CreateGLEntriesForTotalAmounts(

GenJnlLine,TempInvPostBuf,DummyAdjAmount,SaveEntryNo,EmplPostingGr.GetReceivablesAccount,LedgEntryInserted)
//<<<<<<<<<<<<<<<Tenecee>>>>>>>>>>>>>>>>
ELSE
  CreateGLEntriesForTotalAmounts(

GenJnlLine,TempInvPostBuf,DummyAdjAmount,SaveEntryNo,EmplPostingGr.GetPayablesAccount,LedgEntryInserted);

**Comment by elecsach** [comment]
I have added a new field in the "Employee Posting Group" table(Table 5221)
with the following details:
Field No.            Field Name                    Data Type     Length
   Description
50000                 Receivables Account    Code             20

There is a journal that I automatically generate from a custom built
application that uses this
new field so that when posting the journal instead using the default
account field in the
"Employee Posting Group", it uses the newly defined account
field(Receivables Account);

Below is the modification to the function "PostDtldEmplLedgEntries" in
codeunit 12 in ver 14 of D365 BC which I want to implement
in D365 BC ver 23:

//<<<<<<<<<<<<<<<Tenecee>>>>>>>>>>>>>>>>
IF GenJnlLine."Employee Receivables" THEN
  CreateGLEntriesForTotalAmounts(

GenJnlLine,TempInvPostBuf,DummyAdjAmount,SaveEntryNo,EmplPostingGr.GetReceivablesAccount,LedgEntryInserted)
//<<<<<<<<<<<<<<<Tenecee>>>>>>>>>>>>>>>>
ELSE
  CreateGLEntriesForTotalAmounts(

GenJnlLine,TempInvPostBuf,DummyAdjAmount,SaveEntryNo,EmplPostingGr.GetPayablesAccount,LedgEntryInserted);

**Comment by JesperSchulz** [comment]
If events are missing, please create a new event request here on GitHub, and our team will look into providing it 😊 We're not monitoring closed event requests.
