### ISSUE TITLE
Question: In the sales order API order date is actually the document date

### ISSUE THREAD

**Issue by CarlOhlsson** [microsoft/ALAppExtensions#19134]
I just got question from a customer that something was strange with the order dates they were reading into power bi from business central. They claim the order date sent back from the API was not at all the order date when they looked on the sales order inside of BC. I look a look at your API here on github and found the following, you are using document date and call it order date. Both me and the customer find this really strange and confusing. 

Is this a mistake or as designed? 

Link to the API page itself: https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/APIV2/app/src/pages/APIV2SalesOrders.Page.al

```
field(orderDate; "Document Date")
{
    Caption = 'Order Date';

    trigger OnValidate()
    begin
        DocumentDateVar := "Document Date";
        DocumentDateSet := true;

        RegisterFieldSet(FieldNo("Document Date"));
    end;
}
```
Internal work item: [AB#524051](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524051)

**Comment by joakimbeng** [comment]
I agree! To me this is a bug as there is no way to get the real "Order Date" from the API apparently

**Comment by onbuyuka** [comment]
This is by design. When APIs first created, in order to keep the interface consistent for the Graph services, Document Date caption was named Order Date. Changing this would unfortunately be a breaking change. 
If you need this field to be named Document Date, I suggest copy pasting the standard API page into a [custom one](https://www.bing.com/search?pglt=41&q=business+central+custom+api&cvid=790f5e3ab4a948bcb1bdaecef43da501&gs_lcrp=EgZjaHJvbWUqBggAEAAYQDIGCAAQABhAMgYIARAAGEAyBggCEAAYQDIGCAMQABhAMgYIBBAAGEAyBggFEAAYQDIGCAYQABhAMgYIBxAAGEAyBggIEAAYQDIHCAkQRRj8VdIBCTEzODU4ajBqMagCALACAA&FORM=ANNAB1&PC=LCTS).
