### ISSUE TITLE
Shopify Connector Sales invoice not stamped on Shopify order

### ISSUE THREAD

**Issue by LIDDHendrikTeixeira** [microsoft/ALAppExtensions#19540]
I created from a dev store a simple order with 1 item and it has shippng.
order comes into BC correctly.
this is for a location that is advanced warehouse.
ship the item via the warehouse shipment.
back on the sales order you have item line shipped but not the transport.
ship from SO the g/; transport line.
then set the qty to invoice on both lines and invoice them.
sales order invoices however the sales invoice number does not get stamped on the shopify order.
this also makes the order not fulfulled.

**Comment by AndreiPanko** [comment]
Thank you for reaching out. 

If you are Microsoft partner, you can submit support request on behalf of your Business Central online customers. Start at the [Business Central administration center](https://docs.microsoft.com/dynamics365/business-central/dev-itpro/administration/tenant-admin-center) where you can easily submit a support request in the Power Platform admin center.
To submit support requests on behalf of your customer, you must be a [delegated admin](https://docs.microsoft.com/dynamics365/business-central/dev-itpro/administration/delegated-admin) on the customer tenant. Your company must also have the Advanced or Premier [support plan](https://partner.microsoft.com/support/partnersupport).

The described cases though look like expected behavior:
1. The **Sales Invoice No.** field in the Shopify Sales Orders page is used when an imported Shopify Order is already fulfilled. For example, it contains only gift card, then in Business Central instead of Sales Order, system creates Sales Invoice. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/shopify/synchronize-orders#to-create-sales-documents. It doesn't contain link to posted sales invoice.

2. To send information about fulfilment to Shopify you need to run the **Sync Shipments to Shopify** task. For more informations, see https://docs.microsoft.com/en-us/dynamics365/business-central/shopify/synchronize-orders#synchronize-shipments-to-shopify.

Kind regards,
Andrei Panko
PM, Microsoft

**Comment by AndreiPanko** [comment]
Thank you for reaching out. 

If you are Microsoft partner, you can submit support request on behalf of your Business Central online customers. Start at the [Business Central administration center](https://docs.microsoft.com/dynamics365/business-central/dev-itpro/administration/tenant-admin-center) where you can easily submit a support request in the Power Platform admin center.
To submit support requests on behalf of your customer, you must be a [delegated admin](https://docs.microsoft.com/dynamics365/business-central/dev-itpro/administration/delegated-admin) on the customer tenant. Your company must also have the Advanced or Premier [support plan](https://partner.microsoft.com/support/partnersupport).

The described cases though look like expected behavior:
1. The **Sales Invoice No.** field in the Shopify Sales Orders page is used when an imported Shopify Order is already fulfilled. For example, it contains only gift card, then in Business Central instead of Sales Order, system creates Sales Invoice. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/shopify/synchronize-orders#to-create-sales-documents. It doesn't contain link to posted sales invoice.

2. To send information about fulfilment to Shopify you need to run the **Sync Shipments to Shopify** task. For more informations, see https://docs.microsoft.com/en-us/dynamics365/business-central/shopify/synchronize-orders#synchronize-shipments-to-shopify.

Kind regards,
Andrei Panko
PM, Microsoft

**Comment by LIDDHendrikTeixeira** [comment]
thank you for the reply.
