### ISSUE TITLE
Non-Payment period

### ISSUE THREAD

**Issue by jmadrigalTCN** [microsoft/ALAppExtensions#2003]
Could you please set a publication in Codeunit 10700 in Procedure AdjustToNonPaymentPeriod to know when a Due date is changed for this reason?

LOCAL AdjustToNonPaymentPeriod(VAR NonPaymentPeriod : Record "Non-Payment Period";DueDate : Date;ForwardCalculation : Boolean) : Date
PreviousFromDate := NonPaymentPeriod."From Date";
NonPaymentPeriod."From Date" := DueDate;
IF NonPaymentPeriod.FIND('=<') AND (DueDate <= NonPaymentPeriod."To Date") THEN
  IF ForwardCalculation THEN
    DueDate := NonPaymentPeriod."To Date" + 1
  ELSE
    DueDate := NonPaymentPeriod."From Date" - 1
ELSE
  IF PreviousFromDate <> 0D THEN
    NonPaymentPeriod."From Date" := PreviousFromDate;
EXIT(DueDate)

**Comment by AlexanderYakunin** [comment]
Please explain if you need event? If so please be specific about event name, parameters and location.

**Comment by jmcouque** [comment]
I need the even to know when BC has changed a due date, because some customers want to charge a fee to those that the due date has been delayed.
My idea is this one:

The Name could be:  "OnAdjustToNonPaymentPeriod"
In the Codeunit 10700 (Due Date Adjust), in then procedure "AdjustToNonPaymentPeriod", this code could be the one to use:

xlDateInicial := DueDate; // New code
PreviousFromDate := NonPaymentPeriod."From Date";
NonPaymentPeriod."From Date" := DueDate;
IF NonPaymentPeriod.FIND('=<') AND (DueDate <= NonPaymentPeriod."To Date") THEN
  IF ForwardCalculation THEN
    DueDate := NonPaymentPeriod."To Date" + 1
  ELSE
    DueDate := NonPaymentPeriod."From Date" - 1
ELSE
  IF PreviousFromDate <> 0D THEN
    NonPaymentPeriod."From Date" := PreviousFromDate;

// New code (Init)
IF DueDate <> xlDateInicial THEN
  OnAdjustToNonPaymentPeriodF;
// New code (End)

As far as I'm concerned, with this is enough.

Thank you ever so much.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
