### ISSUE TITLE
[Request for Modification] Page 391 "Extended Text List" - UsageCategory

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#20644]
Can you set the property UsageCategory as follows:

```
page 391 "Extended Text List"
{
    Caption = 'Extended Text List';
    CardPageID = "Extended Text";
    DataCaptionFields = "No.";
    Editable = false;
    PageType = List;
    SourceTable = "Extended Text Header";
    UsageCategory = Lists; <-- NEW PROPERTY
}
```

**Comment by JesperSchulz** [comment]
We may have to revert this, as reported on the BaseApp contribution pilot (access only when member of repo): https://github.com/microsoft/BusinessCentralApps/issues/379:

🕮 Describe the issue
With BC 22 you added the UsageCategory List to the page 391 "Extended Text List".
This should be removed again, since this page is only useable if there are filters applied for the "Table Name" and the "No.".

Otherwise there will be extended texts with no reference to any other master data.

🔧 To Reproduce
Steps to reproduce the behavior:

1. Search for Extended Text List
2. Open the Page
3. Insert a new record -> This record can't be used at any places.

Except on Standard Texts with "No." empty (that isn't possible via UI -> caused by NotBlank property on Standart Texts)

📣 Expected behavior
This page shouldn't be searchable via the UI

**Comment by JesperSchulz** [comment]
This change will get reverted with 23.0.
