### ISSUE TITLE
[Event Request] Codeunit 151 System Initialization Impl. - Procedure InitCompany - OnAfterLoginWithoutNoIsolatedEvent

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#20656]
Please add an Event OnAfterLoginWithoutNoIsolatedEvent in Procedure InitCompany in Codeunit 151 System Initialization Impl.
We need an Event which is called at company open and is not a isolated event. We want to implement a basic initialization which has to be run before the extension is usable for the customer. If this throw's an (unexpected) error, It is okay for that case that the client not open and the customer has to contact the System Administrator (bether than some unexpected extension behavior happens which no one notice)

```
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Company Triggers", 'OnCompanyOpenCompleted', '', false, false)]
    local procedure InitCompany()
    var
        SystemInitialization: Codeunit "System Initialization";
    begin
        InitializationInProgress := true;
        SystemInitialization.OnAfterLogin();
        OnAfterLoginWithoutNoIsolatedEvent() <--ADDED
        InitializationInProgress := false;
    end;

    /// <summary>
    /// Integration event for after the login with has no Isolation Level
    /// Subscribe to this event in order to execute additional initialization steps.
    /// </summary>

```

```
    [IntegrationEvent(false, false, false)]
    internal procedure OnAfterLoginWithoutNoIsolatedEvent()
    begin
    end;
```

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot implement this event, and I suspect this is not a right way to do this task. Adding Foundation tag to this request

**Comment by darjoo** [comment]
As Alexander mentions, we cannot implement this. We specifically added it to be isolated because we want to be able to ensure that customers are able to log in without any extensions potentially causing a problem.
Why can't the extension have checks that prevent it from working if it has not been initialized?

Overall, I'm closing this as we know we will not be implementing a non-isolated event. But we can continue the conversation. Just @ me in your reply.
