### ISSUE TITLE
Lookup in Gen. Journal Line delivers wrong result and is slow - FieldGroup cannot be modifed

### ISSUE THREAD

**Issue by BHoepfner** [microsoft/ALAppExtensions#20742]
Our customer is using Business Central 20.4 (Platform 20.0.44266.44359 + Application 20.4.44313.44365) and is experiencing severe problems with the lookup in the Gen. Journal Line. 

On the one hand, the lookup sometimes delivers the wrong result. In this example the customer manually entered the customer no. 3038542, however, not customer 3038542 was focused, but customer 2516152 as the string "3038542" appears in this customer's Phone No. So in case you don't pay attention while entering the customer no. and simply push tab or enter, not customer 3038542 is selected, but customer 2516152!

![image](https://user-images.githubusercontent.com/111738633/197737062-d0c04ec7-8a28-4856-8093-7af703b216eb.png)

On the other hand, the lookup is extremely slow in our customer's database. Regardless of whether you enter the customer no. manually or paste it into the field "Account No.", a wildcard search is performed considering all fields in the Field Group. This is causing loading times of 5-10 seconds every time a customer no. is entered!

As it is not possible to remove fields from Field Groups, as a workaround we created a new field "Account No. (Rapid Entry)" without a table relation so that there is no lookup and validate the original "Account No." with the value of this field. Our customer is able to work with this solution for the time being, but we would of course prefer a proper solution, for example being able to remove unneeded fields in the Field Group.

**Comment by BHoepfner** [comment]
In the meantime our customer has informed us that the same problem is happening in the customer list. Before we apply the same individual solution, we would prefer a solution in the BC standard. Would you please give me an update on this matter?

**Comment by AlexanderYakunin** [comment]
@BHoepfner - if you have customer issue and need solution short term, you need to create service requests using technical support. In my opinion your current issue is By Design and we need platform (Server and AL Compiler) changes to change this behavior. I cannot answer the question how fast it can be fixed for this scenario. 

This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by BHoepfner** [comment]
Hello @AlexanderYakunin,

I have created a support ticket, thank you.
