### ISSUE TITLE
[Event Request] Codeunit 9802 : procedure LogUsage - OnAfterLogTableUsage(TempTablePermissionBuffer)

### ISSUE THREAD

**Issue by EHeirbaut** [microsoft/ALAppExtensions#20833]
Dear ALAppExtensions team,

We would like to request adding an event publisher OnAfterLogTableUsage in Codeunit 9802 "Log Activity Permissions" with the following signature:

  local procedure LogTableUsage(TypeOfObject: Option; ObjectId: Integer; Permissions: Integer; PermissionsFromCaller: Integer)
    var
        NullGuid: Guid;
    begin
...
        end;
        TempTablePermissionBuffer.Modify();
         //>>New Event
        OnAfterLogTableUsage(TempTablePermissionBuffer);
        //<<New Event
    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterLogTableUsage(Var TempTablePermissionBuffer: Record "Tenant Permission" Temporary )
    begin
    end;

**Comment by JesperSchulz** [comment]
Since this event request is for the System Application, we would need a justification for why this event is needed. Which scenario are you trying to support?

**Comment by JesperSchulz** [comment]
The beginning of the procedure states the following:
        // Note: Do not start any write transactions inside this method and do not make
        // any commits. This code is invoked on permission checks - where there may be
        // no transaction.
I am hence very reluctant to add an event in this function, as that can lead to problematic side effects.

**Comment by RHaest** [comment]
Hi Jesper, thanks for your reply. This event is related to https://github.com/microsoft/ALAppExtensions/issues/20832, we need to be able to read the results of the recording for the other user. Since the recording is stored in a temp instance it's not possible to do that directly in the table. Right now, when we use the dotnet component (which is currently still allowed for onprem) we can do that and can read recording results during the recording. With the universal code initiative, this is no longer allowed / possible so we are looking for ways to provide the same functionality. A possible (limited) other solution would be that we add an event after the Stop button but that would omit a lot of the functionality we currently have. I understand your reluctance, so if there are any other ways I'm happy to consider! Thanks

**Comment by JesperSchulz** [comment]
I hope to find time to complete work on this this week. I'll do my best.

**Comment by JesperSchulz** [comment]
I think we can move forward with this request for the 22.1 release in May. I'll do one final internal code review and in it goes!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53793.
