### ISSUE TITLE
[Enum Request] - 98 "General Ledger Setup" - Field 60 "Local Cont. Addr. Format"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20867]
Hello,

we ask you to transform the Option field

60 "Local Cont. Addr. Format"

on Table 98 "General Ledger Setup" to "Enum", in order to allow us to extend it with custom values.

Thank you !

**Comment by AlexanderYakunin** [comment]
Unfortunately, we cannot convert this field to enum due to differences between country option values. it cannot be done without significant refactoring and we have no resources for this work right now. 

Please explain which values you need and for which country (or countries). It can help to find solution. Or close it if you can make you own field to cover your requirements (and hide our field from the page). This is not difficult here.
