### ISSUE TITLE
[Extensibility requests] Change function visibility from internal to external in codeunit 30162 "Shpfy Order Events"

### ISSUE THREAD

**Issue by rkirsten** [microsoft/ALAppExtensions#21507]
Could you please set the protection level to external for the event:

```
    [InternalEvent(false)]
    /// <summary> 
    /// Raised After NewShopify Order.
    /// </summary>
    /// <param name="ShopifyOrderHeader">Parameter of type Record "Shopify Order Header".</param>
    internal procedure OnAfterNewShopifyOrder(var ShopifyOrderHeader: Record "Shpfy Order Header")
    begin
    end;
```
To be able to query more information after order synchronization, it would be good if there was an event to rely on to. Furthermore, the info of the shpfy order ID would be good, so that one can directly access the right resource via API.

E.g.

```
    [InternalEvent(false)]
    /// <summary> 
    /// Raised After NewShopify Order.
    /// </summary>
    /// <param name="ShopifyOrderHeader">Parameter of type Record "Shopify Order Header".</param>
    internal procedure OnAfterNewShopifyOrder("Shopify Order Id": BigInteger)
    begin
    end;
```

**Comment by pri-kise** [comment]
@rkirsten check out the following issue https://github.com/microsoft/ALAppExtensions/issues/18694

@AndreiPanko mentioned, that they 

> [..] are planning to enable extensibility for Shopify Connector by next major. If you need extensibility for this specific scenario sooner and ready to submit PR yourselves, please reach out to [ShopifyBCSupport@microsoft.com](mailto:ShopifyBCSupport@microsoft.com) and we can discuss further.

Therefore right now, this repo is probably not the right place for new events for the shopify app.

**Comment by AndreiPanko** [comment]
**Shopify connector becomes extensible: Stock calculation**

Shopify Connector has been non-extensible, but we're changing that. We're offering a few points of extensibility. We'll keep the number of points to a minimum so that we can follow the rapid development on the Shopify side without introducing breaking changes. We are opening for extensibility for specific scenarios, based on feedback from our partners and customers starting with Stock calculation. For more details, please follow this [repository](https://github.com/microsoft/ALAppExtensions/tree/main/Apps/W1/Shopify) on GitHub. Note that even though extensibility is limited, you can submit improvements directly.

Here are examples of different calculations: [ALAppExtensions/extensibility_examples.md at main · microsoft/ALAppExtensions (github.com)](https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/Shopify/extensibility_examples.md). You can implement your formula as well.
