### ISSUE TITLE
[feature-request]: Please integrate Media-Datatype to Codeunit TempBlob

### ISSUE THREAD

**Issue by BjEic** [microsoft/ALAppExtensions#21608]
Hi,

Please integrate Media-Datatype to Codeunit TempBlob in To-/FromRecord and To-/FromRecordRef

**Comment by AlexanderYakunin** [comment]
Hello! Can you please provide more details about this ask?

**Comment by pri-kise** [comment]
@AlexanderYakunin the Codeunit "Temp Blob" does not check right now, that the source field is of type blob (https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/BLOB%20Storage/src/TempBlobImpl.Codeunit.al). Therefore one might use the procedures FromRecordRef with a FieldNo of a Field of type Media.

The issue is mostly a feature request for the System Application. 
@JesperSchulz will feature requests for the system applications be tracked here too?

Maybe this issue can be tagged with something like "help wanted" / "good first issue", if microsoft does not plan to implement this feature, but someone of the community can implement this feature...

**Comment by JesperSchulz** [comment]
We currently don't accept feature requests through ALAppExtensions. If it is a feature request for the Microsoft product group, a BCIdea should be created. If you'd like to create a PR for the system application, go right ahead and create one. In the repo, no issue is needed (yet).
