### ISSUE TITLE
Extend for codeunit 6224 "XML DOM Management"

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#22574]
Please add the next functions to codeunit 6224 "XML DOM Management"

```
    procedure GetRootNode(pXMLDocument: XmlDocument; var pFoundXMLNode: XmlNode): Boolean
    var
        lXmlElement: XmlElement;
    begin
        pXMLDocument.GetRoot(lXmlElement);
        pFoundXMLNode := lXmlElement.AsXmlNode();
    end;


    procedure FindNodeText(pXMLRootNode: XmlNode; pNodePath: Text): Text
    var
        lXmlNode: XmlNode;
    begin
        if pXMLRootNode.AsXmlElement().IsEmpty() then
            exit('');
        if pXMLRootNode.SelectSingleNode(pNodePath, lXmlNode) then
            exit(lXmlNode.AsXmlElement().InnerText());
    end;

    procedure FindNodeTextNs(pXMLRootNode: XmlNode; pNodePath: Text; pXmlNsMgr: XmlNamespaceManager): Text
    var
        lFoundXMLNode: XmlNode;
    begin
        if pXMLRootNode.SelectSingleNode(pNodePath, pXmlNsMgr, lFoundXMLNode) then
            exit(lFoundXMLNode.AsXmlElement().InnerText());
    end;
```

**Comment by JesperSchulz** [comment]
Sounds fair, but since the code you are referring to is in the BaseApp, you'd have to suggest and fix this code in the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f. Please create a new issue, once you have gained access.

This repository is only for extensibility requests or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

**IMPORTANT:** Microsoft is not going to address the reported issue for you. You will have to get the issue approved, and then push a pull request with the suggested changes yourself. If you would like Microsoft to address the issue, please create a support request.
