### ISSUE TITLE
Sharepoint Client authority Exception

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#22673]
We're trying out the sharepoint client from SystemApp, but we're getting an exception, here an excerpt from the eventlog:
Message System.ArgumentException in AcquireTokenByAuthorizationCodeAsync (action id: 099c3d7f-584c-457a-9e57-f0550c68473a): 'authority' should be in URI format.  (Parameter 'authority')

The webclient opens the OAuth page and closes it, but seems to crash in the GetLists()-function

``` cal
procedure TestSharepointClient()
    var
        SharePointList: Record "SharePoint List";
        SharePointClient: Codeunit "SharePoint Client";
        SharePointAuth: Codeunit "SharePoint Auth.";
        SharePointAuthorization: Interface "SharePoint Authorization";
    begin
        SharePointAuthorization := SharePointAuth.CreateAuthorizationCode('<Azure Tenant ID>', '<Client ID>', '<Client Secret>', '00000003-0000-0ff1-ce00-000000000000/.default');
        SharePointClient.Initialize('<Sharepoint Url>', SharePointAuthorization);
        SharePointClient.GetLists(SharePointList);
    end;
```

I've been trying in the BC22 public preview
Version: DE Business Central 22.0 (Platform 22.0.54512.0 + Application 22.0.54157.54529)

**Comment by pri-kise** [comment]
@jwikman was involved in some change for the sharepoint authorization. https://github.com/microsoft/ALAppExtensions/pull/21591
Maybe he can help in this specific topic.

**Comment by JulianTillmann** [comment]
@jwikman 
thanks for you  reply. I've tried using a guid with  and without the curly brackets. what would the correct usage be?

**Comment by JulianTillmann** [comment]
now I'm getting a HttpRequestException  "Exceeded maximum number of requests (2)"

**Comment by JulianTillmann** [comment]
also the login page is opening every time. will this be a problem when using the sharepoint client in a task scheduler context?

**Comment by jwikman** [comment]
Are you running OnPrem/Container or SaaS?

**Comment by jwikman** [comment]
Ok. BC22 Public Preview should have the latest fixes I added, so that should be good.
I've never seen the `Exceeded maximum number of requests (2)` error. I have no clue on that, sorry... 

Reg. the "login page opening every time": After my addition earlier this year, the authentication logic tries to fetch an access token from the token cache inside BC (using stored Refresh Tokens). If that fails, the authentication window is opened. Often the browser has cached tokens as well, so that window might just flash open and close. But if nothing cached in client either, the user must logon again.
The refresh token in BC should be usable for up to 90 days, but shorter times could be configured in AAD.

I'm using the same approach in one of our AppSource apps. And if the user authenticates once, it can be used in Job Queue for several months. I'm catching the authentication error and uses notifications for the user to re-authenticate when logged on the next time.

The best thing to have if you want to run in a Job Queue, obviously, is Service to Service authentication with the Client Credentials Flow. But that requires certificates, and System App does currently only support Client Credentials Flow with certificates that are password protected. And I think that implementing this without password do not comply with security best practices, so I'll wait until that is supported before implementing this in the SharePoint Authorization module. This is requested in https://github.com/microsoft/ALAppExtensions/issues/22261.

**Comment by jwikman** [comment]
> BC22 Public Preview sandbox container and the sharepoint is a CDX, so the webclient is in private mode

Try a SaaS sandbox instead, and see if that helps.
And make sure to add `https://businesscentral.dynamics.com/OAuthLanding.htm` as Redirect URI on the App Registration.

**Comment by JulianTillmann** [comment]
okay, if the AcquireTokenWithClientCredentials is not yet possible I can stop my testing for now. 

Don't know what you mean by "requires certificates"? certificates where? We had implemented an OneDrive connection via GraphAPI with Oauth2 AcquireTokenWithClientCredentials and this works on containers without SSL

**Comment by JulianTillmann** [comment]
also, when I got your attention: 
did you not have an issue with uploading files that are greater than 4MB? but I'm guessing your using the sharepoint API and not GraphAPI, right?

**Comment by jwikman** [comment]
It is a requirement from SharePoint, we discovered while trying to implementing this. Using an access token that is created from ClientId + ClientSecret only (with the Client Credentials Flow) is not accepted by SharePoint.
You can read more at https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#setting-up-an-azure-ad-app-for-app-only-access

I've created a draft PR (https://github.com/microsoft/ALAppExtensions/pull/22404/files) for Client Credentials with a certificate that is not password protected, but I don't want to publish that until we get proper support for password protected certificates. But you can copy that code and implement your own authentication to be used with the SharePoint Module if you are OK with certificates without password - we've tested and got it to work.

**Comment by jwikman** [comment]
> also, when I got your attention: did you not have an issue with uploading files that are greater than 4MB? but I'm guessing your using the sharepoint API and not GraphAPI, right?

The SharePoint module is using the SharePoint API, from what I understand.

A colleague of mine tested with a 19.5Mb file earlier, and that worked. He will test again with even larger files to see if we can hit any limits.

**Comment by JulianTillmann** [comment]
okay, thanks for all the info! :-) 

We'll take another look when the client credential is officially implemented

**Comment by jwikman** [comment]
Just tested upload/download with a 120Mb file - all fine. 👍
