### ISSUE TITLE
Data Compression Bug - GZipDecompress

### ISSUE THREAD

**Issue by UrbMigle** [microsoft/ALAppExtensions#23120]
The GZip decompression do not work the same in BC 22 as it's been working in BC 21. In previous version it would decompress file that was compressed using deflate (FlateDecode) algorithm and now it fails.

Minimal repro steps:
 
![image](https://user-images.githubusercontent.com/65913191/233966072-d5b56b1e-49e3-4115-a9f8-42be83f05ad0.png)

Decompression breaks in codeunit 421 “Data Compression Impl.”, line 41.
 
![image](https://user-images.githubusercontent.com/65913191/233966134-d04ed127-e2c1-4d7b-82ff-e04421e3ec51.png)

The error that is shown:
 
![image](https://user-images.githubusercontent.com/65913191/233966152-dd30245b-e871-48c9-bdc8-687e9285c183.png)

There is a theory, it might've happened because .NET is now running on 6.0.

[Here ](https://coniun-my.sharepoint.com/:u:/r/personal/migle_urbonaite_companial_com/Documents/Example%20file/file?csf=1&web=1&e=p6R6z5) a file that was decompressed without a problem in BC 21.6, but fails in BC 22 can be found.

**Comment by pri-kise** [comment]
@UrbMigle Thanks for reporting this.
Have you created a support case for this issue, too?
The github team has limited capacity and if a customer is impacted by this issue you should created a support case to get this prioritised.

It's always easier if you provide your minimal example as text instead of images, then this can be checked more easily.

**Comment by UrbMigle** [comment]
Support case is still in progress, waiting for support advocate to contact me.

Ok, I'll have in mind in the future to provide examples as text :)

**Comment by donmikele75** [comment]
@UrbMigle : Do you have any updates? We are using GZipDecompress to deflate PDF ObjectStreams - this functionality is broken with BC22...

**Comment by UrbMigle** [comment]
@donmikele75  Unfortunately not. Support case is not getting any attention as well :(
We were using this functionality for the same exact purpose :)

**Comment by JesperSchulz** [comment]
We'll take a look. We've got an open support case for this.

**Comment by donmikele75** [comment]
Any news?

**Comment by JesperSchulz** [comment]
We finally found some time to look into this case, and indeed this turns out to be a side-effect of the upgrade to .NET core. The data you are trying to pass is not GZIP, it is ZLib (0x68 0xDE header). Hence, if you use the IsGZIP check in Data Compression you will see that it (correctly) returns false. In the .NET framework, it must have been more relaxed around what it supported, but now it is strict.

That is of course unfortunate, but the code now works as it was designed to work. To decode this, you will need to use ZLibStream instead. You would need new methods for ZLib (and maybe also for raw DeflateStream).

We would of course accept a PR adding ZLib capabilities in the Compression module.
