### ISSUE TITLE
[Code Defect] codeunit 80 "Sales-Post" - ProcessPosting

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#23174]
Is it a bug? Or is variable name misnamed? Is the variable meaning related to "parent" or "child" code? Can anyone explain it to us how it was meant?

In document posting routines (sales/purchase), there is `ProcessPosting` method with `ErrorOnCommit` variable:
```al
local procedure ProcessPosting(...)
var
	ErrorOnCommit: Boolean;
begin
	ErrorOnCommit := true;
	OnSetCommitBehavior(ErrorOnCommit);

	if ErrorOnCommit then
		ProcessPostingLinesCommitBehaviorIgnore(...)
	else
		ProcessPostingLines(...);
end;
```
Two methods are called from inside, one of them has attribute `CommitBehavior::Ignore`:
```al
[CommitBehavior(CommitBehavior::Ignore)]
local procedure ProcessPostingLinesCommitBehaviorIgnore(...)
begin
	ProcessPostingLines(...);
end;

local procedure ProcessPostingLines(...)
begin
...
end;
```
Is the '_if_' condition in `ProcessPosting` method OK? Shouldn't be the order of called methods inversed? Like:
```al
	if ErrorOnCommit then
		ProcessPostingLines(...);
	else
		ProcessPostingLinesCommitBehaviorIgnore(...)
```

**Comment by aldobriansky** [comment]
It is the naming issue. The CommitBehavior attribute was originally set to Error, hence the name of the ErrorOnCommit variable. Later, it was decided to go milder way and just ignore commits during posting to prevent potential half-baked transactions due to possible commits in event subscribers. The attribute value was changed from Error to Ignore, but the name of the variable wasn't corrected accordingly. I'll fix it shortly. Thanks for pointing out on this!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11127.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57956.
