### ISSUE TITLE
Usage of "±" - Char(177) as a Field Delimiter in all Reports

### ISSUE THREAD

**Issue by PiGlic** [microsoft/ALAppExtensions#23203]
Hi,

first of all I am aware that this is not a small thing and can not be changed just now 😅

In the Standard Reports their is a Visual Basic Function for Setting and Getting the Report Header:
![image](https://user-images.githubusercontent.com/36172313/236164658-e08ea328-19b7-4735-912b-062c34ed7aa6.png)
(Scrennshot from SalesShipment.rdlc)
I checked the base app for Char(177) and found a total of 83 layout files that use this delimiter

This Code Snippet is also Documented as an Example in the Mircosoft Docs:
https://learn.microsoft.com/en-us/dynamics-nav/how-to--print-report-header-information-on-multiple-pages
![image](https://user-images.githubusercontent.com/36172313/236165802-89c29bb2-b218-48d6-bd04-723f142ddb60.png)

I therefore assume that partners and also end customers have copied the corresponding code line and are currently using it.

Within the ASCII table there are own control characters for delimiting data:
- ASCII Code 30 - Record Separator (RS)
- ASCII Code 31 - Unit Separator (US)

Wouldn't it make more sense to split the data with one of these characters? Since ± is currently used as a separator, it can no longer be used within the database because I run the risk that the data is separated incorrectly in reports.

Furthermore, the character ± is used to represent tolerances (e.g. for cut surfaces or lengths). The chance that an end user uses this character in the database is therefore relatively high.

Now to the real question:
- Is it possible to change the code in question in a future Global update? This would make the Plus–minus sign usable again for the end user.

If this is not possible, I would like to move this issue to the Microsoft Docs repo and clarify where in the docs the current behavior is documented.  So that the character "±" is technically used for separation  and that it can cause problems within the reports when it should be printed.

**Comment by pri-kise** [comment]
@PiGlic have you tested on report with the "ASCII Code 31 - Unit Separator (US)"? I would expect that everythings works the same, but it should be tested at least.

I totally agree with you that a char separation isn't the best option.
Personally I would still prefer some kind of List Type instead of using char separator.

But using the correct char for unit separation seems to be at least a little bit better.

I created an a new idea for XmlPorts to support this special char, too: https://experience.dynamics.com/ideas/idea/?ideaid=d4eb678a-13eb-ed11-913b-0003ff459a6f

**Comment by AlexanderYakunin** [comment]
Thanks for creating idea, closing.
