### ISSUE TITLE
[Information] Direct Trans. Header No. assignment in CU 5856 not pushed in Build 56000+

### ISSUE THREAD

**Issue by FedericoGalanti** [microsoft/ALAppExtensions#23237]
#22828 
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10560.

_Originally posted by @JesperSchulz in https://github.com/microsoft/ALAppExtensions/issues/22828#issuecomment-1521636280_

Hello!

As stated per your last response, this would have been pulished asap or in the next major release. I checked in code of 21.5.53619.56002 - 21.5.53619.56189 - 22.0.54157.56189 and the requested code is not yet modified.

Am I missing something? Build ID was not referring to a current Base Application build?

Thanks,
Federico

**Comment by pri-kise** [comment]
@FedericoGalanti you should check the latest insider preview versions: either 21.7 or 22.1 /22.2.
If it was added last week, then it might be available in the CU that will be provided in around 4 weeks. 
The 4 weeks is my personal experience, since microsoft freezes code changes for the next CU about 2/3 weeks before the release of a CU.
Major releases have an earlier code freeze - about 6 weeks.

**Comment by FedericoGalanti** [comment]
Hello @pri-kise !

Thank you very much for the informations. Since previous issues would bear live Build ID, I understood that the number referred to a future live build, not the insider one.

I'll then await for the major release. I will close the issue, since the question was completely answer. In case of other troubles, I'll follow the same guidelines opening a new issue.

Again, thank you very much for you time and patience.

Best regards,
Federico
