### ISSUE TITLE
Shopify Extensibility need access to ExecuteGraphQL

### ISSUE THREAD

**Issue by petegonnella** [microsoft/ALAppExtensions#23560]
codeunit 30103 "Shpfy Communication Mgt."    

internal procedure ExecuteGraphQL(GraphQLQuery: Text): JsonToken
    begin
        exit(ExecuteGraphQL(GraphQLQuery, 0));
    end;

Can a impl. function codeunit be developed which will allow third-party developers to upload third-party data to Shopify via this function using GraphQL.

Scenario,

We have multiple images per color for a product and want to associate them with variants which use that color on a product.

If this function is made available I can use stagedUploadsCreate and then upload the image. And with a combination of productUpdate and productVariantUpdate to set the image to the product and variant appropriately

Internal work item: [AB#524439](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524439)

**Comment by onbuyuka** [comment]
Please check the following yammer post of @AndreiPanko
https://www.yammer.com/dynamicsnavdev/threads/1762140027789312

As you know the Shopify Connector is made non-extensible. We plan to change it in the future, and we want to try a different model.

Motivation: we want to avoid misuse of extensibility to address bugs, minor improvements, or gaps – all of that end-user expects to be part of product. Millions of events spread across the code reduce readability and scalability, increase maintenance and upgrade costs for all parties.

As source code of Shopify Connector is on GitHub we would like to reuse pattern we have for System App:

Prioritize submitting improvement over extensibility. For example, if your customer needs to export multiple translations of a product to Shopify, instead of asking for making some objects extensible – submit PR that implements this feature.
If extensibility is really necessary – for example to orchestrate multiple extensions dealing with various sales channels – please create PR directly. Remember to write the proper justification of scenario.
We will not process extensibility requests for connector registered as Issues on GitHub.

**Comment by JesperSchulz** [comment]
Closing as per previous comment.
