### ISSUE TITLE
[extensibility request] Table 30115 "Shpfy Log Entry" remove Internal Access property

### ISSUE THREAD

**Issue by Mario-Sopena** [microsoft/ALAppExtensions#24338]
Hi,
As this Log may have huge amounts of records, when you use any of this actions and there are millions of records, it gets stuck.
![image](https://github.com/microsoft/ALAppExtensions/assets/123956717/6956b3b1-7ea3-432a-ab54-6ce1f3978e6f)

Another solution would be allowing running it in the background.

Thanks in advance

**Comment by pri-kise** [comment]
Instead of removing the Access property wouldn't it better to provide retention policy support for this table.
Similiar to the mail module.

Check out codeunit 1598 "Email Logs Delete" and `codeunit 1596 "Email Installer"`.

@Mario-Sopena feel free to create a PR for the system application to improve the shopify app for anyone.

**Comment by AndreiPanko** [comment]
We are releasing this functionality for the next major release, for more information, see https://learn.microsoft.com/dynamics365/release-plan/2023wave2/smb/dynamics365-business-central/troubleshoot-shopify-integration-issues
