### ISSUE TITLE
[Bug] - Undo of Transfer Shipment

### ISSUE THREAD

**Issue by nixpt82** [microsoft/ALAppExtensions#24386]
When we do undo of a transfer of a item with variante code in a diferent unit of measure of the Base unit.

The system gives this error:

Invoiced Quantity must have the same value as Quantity in Item Journal Line Journal Template Name='',Journal Batch Name='',Line No.='0'.

AL call stack:
"Item Jnl.-Check Line"(CodeUnit 21).RunCheck line 86 - Base Application by Microsoft
"Item Jnl.-Post Line"(CodeUnit 22).Code line 15 - Base Application by Microsoft
"Item Jnl.-Post Line"(CodeUnit 22).PostSplitJnlLine line 12 - Base Application by Microsoft
"Item Jnl.-Post Line"(CodeUnit 22).RunWithCheck line 16 - Base Application by Microsoft
"Item Jnl.-Post Line"(CodeUnit 22).OnRun(Trigger) line 3 - Base Application by Microsoft
"Undo Posting Management"(CodeUnit 5817).PostItemJnlLine line 16 - Base Application by Microsoft
"Undo Posting Management"(CodeUnit 5817).PostItemJnlLineAppliedToList line 44 - Base Application by Microsoft
"Undo Transfer Shipment"(CodeUnit 9030).PostItemJnlLine line 62 - Base Application by Microsoft
"Undo Transfer Shipment"(CodeUnit 9030).Code line 56 - Base Application by Microsoft
"Undo Transfer Shipment"(CodeUnit 9030).OnRun(Trigger) line 15 - Base Application by Microsoft
"Posted Transfer Shpt. Subform"(Page 5744).UndoShipmentPosting line 6 - Base Application by Microsoft
"Posted Transfer Shpt. Subform"(Page 5744)."UndoShipment - OnAction"(Trigger) line 2 - Base Application by Microsoft
"Transfer Order Subform"(Page 5741)."Quantity Shipped - OnDrillDown"(Trigger) line 9 - Base Application by Microsoft

**Comment by JesperSchulz** [comment]
Great catch! And thank you for reporting the issue. Unfortunately, this repository isn't the right place to report your bug.

In this repository you can create issues concerning the extensibility of Business Central, such as missing events. You can also create issues you would like to fix yourself in the code present in this repository, which are our 1st party apps.

Your bug seems to be BaseApp code though, which only can get addressed in our [BaseApp contribution pilot](https://github.com/microsoft/BusinessCentralApps). Do you want me to transfer this issue to the BaseApp pilot repository?

Note, that the transferred issue would have to get approved in triage and you would have to create a pull request yourself. GitHub is not the right place to report issues you would like Microsoft to address. For that, please create a support request.

PS: You need to be granted access to the pilot repo, if you would like to collaborate on the BaseApp with us. To get access, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

PPS: I recognize that the process on where you can report which issues is a bit messy these days. We're in between processes and hope to be able to streamline and document the right processes in the very near future.
