### ISSUE TITLE
Need to update POSTED SALES SHIPMENT

### ISSUE THREAD

**Issue by billyfuTC** [Microsoft/ALAppExtensions#249]
AL Extension Version:
0.16.19969
Server Version:
US Dynamics NAV 12.3 (23918)

We need to update the fields of header and lines for Posted Sales Shipment. Like Quantity, Location, Posting Date.
And we also need the abillity to add more lines on it for Overship.
Could you please expose the edit functionality for us?
And we also need to update the Posted Sales Shipment by API. Could you please provide us some CodeUnit to do that?

Thanks
Billy

**Comment by AlexanderYakunin** [comment]
Let me try answer your questions:
1. You can create an extension to update Sales Shipment if you provide proper permissions to this user.
2. But changes in Posted Sales Shipment do not affect actual inventory, in order to do this you need to post changes via Item Journal Line manually or using additional functionality you have designed. 
3. We do not support Overship as part of shipment process, I'd suggest to post extra shipment and link it to original one to keep track of this.
