### ISSUE TITLE
[Event Request] - Codeunit 22 "Item Jnl.-Post Line" - procedure OnPostFlushedConsumpOnBeforeTransferPOComToItemJnlLineAllocation

### ISSUE THREAD

**Issue by INNONAV** [microsoft/ALAppExtensions#24939]
**🕮 Describe the request**

For a large customer project that we need to migrate to the cloud, we need the following event/customization.

Please add the following event together with variable IsHandled for the whole customized logic

![image](https://github.com/microsoft/ALAppExtensions/assets/62563638/2785e2ed-f8ea-4261-bdfd-555087d3ecb2)

![image](https://github.com/microsoft/ALAppExtensions/assets/62563638/643e6dfb-64db-4bdc-b575-4136e361a31f)

As Text:

    [IntegrationEvent(false, false)]
    local procedure OnPostFlushedConsumpOnBeforeTransferPOComToItemJnlLineAllocation(var ItemJnlLine: Record "Item Journal Line"; OldItemJnlLine: Record "Item Journal Line"; ProdOrderComp: Record "Prod. Order Component"; QtyToPost: Decimal; var PackageBuffer: Record "Item Journal Line" temporary; var TrackingPerPackageBuffer: Record "Item Journal Line" temporary; var IsPrepared: Boolean)
    begin
    end;

**Additional context**

**Comment by AleksandricMarko** [comment]
Hello @INNONAV 

Within event request we can`t add repeat until loop just because you need it.
We can just add event publishers which you can use to skip/extend some part of code.
In current case, we can add parameters in event OnPostFlushedConsumpOnBeforeProdOrderCompReserveTransferPOCompToItemJnlLine with IsHandled pattern so you can have your own logic and skip standard one (skip whole code till OnAfterPostFlushedConsump).
If this is fine, please check which parameters you need for this purpose.
Otherwise, you should consider what is other way (maybe several different events could be solution)

**Comment by tomasevics** [comment]
Closed due to inactivity.
