### ISSUE TITLE
[Event Request] Add new events to apply filters to records before consolidating data from origin company form different environment. 

### ISSUE THREAD

**Issue by arvindbinarystream** [microsoft/ALAppExtensions#24975]
Hi team,

We will need additional integration events to do consolidation from different environment company. Also, there are few integration event that can be useful but we can not access it due to the protection level of the codeunit and it's procedures.

if possible, can it be made Public?
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/2f217f63-fe86-4251-85ac-a2507913b9bb)

Below is the additional integration event that we need.
New Event Will be

1. CodeUnit 102 "Import Consolidation from API"
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/157e2ac5-7cc2-49e9-a169-ff7438963c9e)

- Event signature will be:-
- [IntegrationEvent(false, false)]
- local procedure OnBeforeRunConsolidation(var IsHandled: Boolean; BusinessUnit: Record "Business Unit" temporary; CurrencyCode: Code[10]; AdditionalReportingCurrencyCode: Code[10]; ConsolidationProcess: Record "Consolidation Process";)
- begin
- end;

**Comment by arvindbinarystream** [comment]
Also, There's an additional issue with existing functionality that if selected Default Data Import Method is API on Business Unit Card page and **Run Consolidation** action is performed from the same window (Business Unit Card), it will always throw error. As this action always runs the report that consolidate on Database and field required to run consolidation for Database is missing because the selected method is not Database, it will never run consolidation.
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/d731b581-2e41-4dea-848d-8b3f51b99ff6)

**Comment by mynjj** [comment]
@arvindbinarystream  Thanks for the insight, we will implement this feedback to safeguard the previous report, it should be available for 23.2.

We are trying to move away from events for extensibility. Would it be ok to provide a public procedure to import the data? It seems to me that you want to be able to prepare the Consolidate codeunit with the imported data and extract parameters so you can run your own custom Consolidate process?

**Comment by arvindbinarystream** [comment]
@mynjj thanks for the response. Could you please share more details/documentation on **"move away from events for extensibility"**? and a possible approach to overcome this. For this event request, I want to handle consolidation with additional filters and run it multiple times with the filters applied. Also, need to use available events but due to the protection level I am not able to use it.

**Comment by mynjj** [comment]
Hi @arvindbinarystream, sorry for taking a bit to answer.

We will for sure change the protection level 😄  ...

So, there is no official "we are moving away from events", in fact if you want to modify the page actions we provide instead of writing your own actions, `events` are in many cases the only way we have to do it. What I meant by that (I should have been more clear) is that I am trying to avoid putting them deliberately everywhere in new code as a design choice. Keeping at bay the events we provide helps us a lot maintaining BaseApp. I wrote some reasons of why events are problematic for us at the bottom of this post if you are interested, for now I'll focus in my proposal for this case:

A _"better"_ way to provide extensibility is with interfaces. I'll provide two interfaces that the `ImportAndConsolidate` codeunit will use: `"Import Consolidation Data"` and `"Consolidation Method"`.

- `"Import Consolidation Data"` is called when extracting data used for the consolidation of a `BusinessUnit` for a given `ConsolidationProcess`. All the data imported is stored in a new `BusUnitConsolidationData` temp record, which you can extend to store custom data.

- `"Consolidation Method"` is called after the data has been imported and you want to execute the actual consolidation (posting GL Entries, etc.). You have access to the imported data, which contains the `Consolidate` codeunit which you can call after whatever modifications-filters you have and you can run it several times.

 After you implement these interfaces to suit your needs, you will be able to decide which implementation to use through an event (we need an event after all 😉 ). I'm attaching an example PTE of how you can extend using this approach. I changed a bit the existing code, I'm attaching the changes and new files so that you can understand the proposal more.

I'm giving two points of extensibility that I believe are broad enough for your needs and I'm making public some of the new procedures so that you can also use them. In the original event you also wanted the currency codes, you can get those from `Consolidate.GetGlobals`

### Why I'm trying to avoid events 

It's very hard for us to maintain BaseApp. With new code (as this one) I prefer not to introduce ad-hoc events everywhere. Instead we can work together on your extensibility requirements and come up with a better design. 

The problem with events is that they may invalidate assumptions we had about the state, and we rely on extensions being "good citizens" and doing what they need correctly. But the main problem is that once we add an event, we must maintain it for us not to break extensions, it ties the implementation to have that event. As an example, recently I had to change a problematic posting codeunit, and it was tricky to maintain the events that were expecting to receive the same data, even when the logic around it had changed.

Interfaces give us more control of what should be possible to be extended and give us some guarantees about how you are extending it. It still ties the implementation but in a way that is more manageable. Yes, it would have been easier to just add that two liner event request, but I think it's good if we can get to a better design upfront.

Please keep coming with feedback so that we are sure we are providing enough to extend this scenario 😄 what do you think? would this work?

**Comment by mynjj** [comment]
Oops, the attachments were missing:

[ConsolidationExtensibilityExample.zip](https://github.com/microsoft/ALAppExtensions/files/13334228/ConsolidationExtensibilityExample.zip)
[ConsolidationExtensibilityBaseAppChanges.zip](https://github.com/microsoft/ALAppExtensions/files/13334229/ConsolidationExtensibilityBaseAppChanges.zip)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13974.
