### ISSUE TITLE
[Event Request] codeunit 8900 "Email Impl" - OnbeforeEmailAddRelation

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#25050]
Hello, is it possible to add a new Event OnBeforeEmailAddRelation in codeunit 8900 "Email Impl" ?
We want to prevent execution for "Team Member User" as this will cause errors due to the Team Member License.

```
    procedure AddRelation(EmailMessageId: Guid; TableId: Integer; SystemId: Guid; RelationType: Enum "Email Relation Type"; Origin: Enum "Email Relation Origin")
    var
        EmailRelatedRecord: Record "Email Related Record";
        IsHandled;
    begin
        if EmailRelatedRecord.Get(TableId, SystemId, EmailMessageId) then
            exit;

        IsHandled := false;
        OnBeforeEmailAddRelation(IsHandled);
        If not IsHandled then begin
              EmailRelatedRecord."Email Message Id" := EmailMessageId;
              EmailRelatedRecord."Table Id" := TableId;
              EmailRelatedRecord."System Id" := SystemId;
              EmailRelatedRecord."Relation Type" := RelationType;
              EmailRelatedRecord."Relation Origin" := Origin;
              EmailRelatedRecord.Insert();
         end;
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeEmailAddRelation(var IsHandled: Boolean)
begin
end;
```

**Comment by ReneZiel** [comment]
Hello, we have this reported via support Ticket.
The ticket number is Ticket 2205120060001194 - Table 8909 Email Related Record Missing from Team Member License.
Support's suggestion was to request this integration event.

We received the following suggested solution.
"Moreover, if you would like an event to bypass this write, then you would need to request the change on GitHub.
We have already confirmed with the development team that we don't permit writing to this table with a Team Member license."

**Comment by stkillen** [comment]
Sorry for the late response on this issue.

However, this write shouldn't fail for a team member if they have the permission assigned. As @pri-kise mentioned above, the team member entitlement contains `rimd`. The team member has the same entitlement to this table as any other license.

**Comment by stkillen** [comment]
Closing this request as this does not seem like the right approach and we do not see a reason for this event.

As to this response:

_"We have already confirmed with the development team that we don't permit writing to this table with a Team Member license."_
 
This is not true, if you were told otherwise that's a mistake. The table **is** in license, but it's internal and we only give indirect permissions (meaning you cannot directly access the table, but the code you are mentioning here can be executed on all licenses).

We do not have any plans to make the table public or change the permissions away from indirect permissions.
