### ISSUE TITLE
Sales Order List - Create Warehouse Shipment (with release)

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/ALAppExtensions#25165]
**🕮 Describe the issue**
When I have two open sales orders and mark them in the page sales orders and use the action Create Warehouse Shipment. Only the first sales order will be released.
In the release action is the PerformManualRelese used with the input of SalesHeader
![image](https://github.com/microsoft/ALAppExtensions/assets/47736215/22db7ade-1876-4425-a2c1-27f6093addda)
In the action Create Warehouse Shipment is only the function PerformManualRelese without the input.
![image](https://github.com/microsoft/ALAppExtensions/assets/47736215/24a5d5a9-0069-47fd-bb76-0ddd7587fd61)
Same is in Create Inventory Put-away/Pick

**Comment by AlexanderYakunin** [comment]
And what is your request?

**Comment by FSchneiderYav** [comment]
That you call in the Create &Warehouse Shipment function use also 
CurrPage.SetSelectionFilter(SalesHeader);
Rec.PerformManualRelese(SalesHeader);

**Comment by FSchneiderYav** [comment]
In the Page Transfer Order is it also possible to select some lines and use Release. But only the first is released

**Comment by AlexanderYakunin** [comment]
This is product improvement suggestion, not an extensibility request. We have special portal aka.ms/bcideas to submit such suggestions. I will forward this ask to responsible team anyway but cannot promise it will be processed from here.

**Comment by FSchneiderYav** [comment]
That is not a product improvement suggestion. This is a Bug.

**Comment by AndreiPanko** [comment]
Thank you for reaching out.

Notice that create warehouse shipment called for two _released_ document will create one warehouse shipment.
Some actions only work with one record, there are some work planned:
* either block these actions when multiple records selected, see Delete action in the sales order list.
* or enable bulk processing.

The later requires more engineering work, that's why we would appreciate if you log the suggestion via aka.ms/bcideas, then with votes it is easier to prioritize and implement what is important for majority of users.

If you believe this is product defect, I suggest to report it via proper channels. For more information see https://learn.microsoft.com/dynamics365/business-central/dev-itpro/help-and-support#bugs 

Kind regards,
Andrei Panko
PM Microsoft
