### ISSUE TITLE
[Bug]: Permission missing in codeunit 7301 "Whse. Jnl.-Register Line"

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#25207]
### Describe the issue

Hello,

In codeunit 7301 "Whse. Jnl.-Register Line" there's a function DeleteFromBinContent that really deletes "Bin Content" records. But all standard permission sets and user roles don't cover this right for a simple user to delete this. So, this codeunit needs an additional permission like Permissions = TableData "Bin Content" = rd.

Best Regards
Thomas

### Expected behavior

All users with normal table access should be able to use functions of this codeunit with "Bin Content" entries which doesn't have no "Default" and no "Fixed" checkmark

### Steps to reproduce

Ship a complete inventory from a location with bins with a "Bin Content" entry that doesn't have no "Default" and no "Fixed" checkmark.  If there's no remaining quantity the function will try to delete the "Bin Content" record but isn't allowed to do so.

### Additional context

Not really necessary

**Comment by JesperSchulz** [comment]
Great catch! And thank you for reporting the issue. Unfortunately, this repository isn't the right place to report your bug.

In this repository you can create issues concerning the extensibility of Business Central, such as missing events. You can also create issues you would like to fix yourself in the code present in this repository, which are our 1st party apps.

Your bug seems to be BaseApp code though, which only can get addressed in our [BaseApp contribution pilot](https://github.com/microsoft/BusinessCentralApps). Do you want me to transfer this issue to the BaseApp pilot repository?

Note, that the transferred issue would have to get approved in triage and you would have to create a pull request yourself. GitHub is not the right place to report issues you would like Microsoft to address. For that, please create a support request.

PS: You need to be granted access to the pilot repo, if you would like to collaborate on the BaseApp with us. To get access, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

PPS: I recognize that the process on where you can report which issues is a bit messy these days. We're in between processes and hope to be able to streamline and document the right processes in the very near future.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14512.
