### ISSUE TITLE
[Bug]: CanPickSalesLine return true instead of false with a not inventory item.

### ISSUE THREAD

**Issue by renevanbeekum** [microsoft/ALAppExtensions#25214]
### Describe the issue

The routine CanPickSalesLine (replace routine IsInventoriableItem) in gifs true when the item is a not inventory type, the old routine IsInventoriableItem gifs false. This is in codeunit 7322 "Create Inventory Pick/Movement" in routine CreatePickOrMoveFromSales.

Old code:
if not IsHandled and IsInventoriableItem() then

New code:
if not IsHandled and CanPickSalesLine(SalesLine) then

Routine CanPickSalesLine calls routine CheckIfSalesLineMeetsReservedFromStockSetting and in this routine is the statement:
if not Rec.IsInventoriableItem() then
   exit(true); //Wrong, must be exit(false);

- 

### Expected behavior

No check on inventory when a not inventory item.

### Steps to reproduce

Non inventory item in sales order and post it.

### Additional context

-
Internal work item: [AB#501003](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501003)

**Comment by JesperSchulz** [comment]
Great catch! And thank you for reporting the issue. Unfortunately, this repository isn't the right place to report your bug.

In this repository you can create issues concerning the extensibility of Business Central, such as missing events. You can also create issues you would like to fix yourself in the code present in this repository, which are our 1st party apps.

Your bug seems to be BaseApp code though, which only can get addressed in our [BaseApp contribution pilot](https://github.com/microsoft/BusinessCentralApps). Do you want me to transfer this issue to the BaseApp pilot repository?

Note, that the transferred issue would have to get approved in triage and you would have to create a pull request yourself. GitHub is not the right place to report issues you would like Microsoft to address. For that, please create a support request.

PS: You need to be granted access to the pilot repo, if you would like to collaborate on the BaseApp with us. To get access, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

PPS: I recognize that the process on where you can report which issues is a bit messy these days. We're in between processes and hope to be able to streamline and document the right processes in the very near future.

**Comment by renevanbeekum** [comment]
Due to a change for an extensibility of Business Central, the code is no longer correct. It worked well before this adjustment. I don't know what the purpose was for the extensibility of Business Central adjustment, but it was not implemented properly, there I report it here. Check the extensibility adjustment and correct it.

**Comment by JakovljevicDusan** [comment]
Issue reported via different channel and hotfix included since version 23.3.
