### ISSUE TITLE
[Bug]: Send procedure in the Email Item table doesn't return the correct value

### ISSUE THREAD

**Issue by tjbakker** [microsoft/ALAppExtensions#25259]
### Describe the issue

One of the overloads of the Send procedure in the Email Item table (ID: 9500) always returns false, even when the email is send successfully.  Problem is a small programing bug: 

Current code: 

```
    procedure Send(HideMailDialog: Boolean; EmailScenario: Enum "Email Scenario"): Boolean
    begin
        Send(HideMailDialog, EmailScenario, false);
    end;
```

Expected code: 
```
    procedure Send(HideMailDialog: Boolean; EmailScenario: Enum "Email Scenario"): Boolean
    begin
         exit(Send(HideMailDialog, EmailScenario, false));
    end;
```

### Expected behavior

Send method to retrurn true if the email is send, and false if it failed. 

### Steps to reproduce

Call the Send(HideMailDialog: Boolean; EmailScenario: Enum "Email Scenario") procedure, and use the return value. 

### Additional context

not applicable.

**Comment by dannoe** [comment]
I personally would prefer to obsolete the wrong method and introduce a new one. (Because this is a breaking change in terms of logic in existing code)

**Comment by tjbakker** [comment]
> I personally would prefer to obsolete the wrong method and introduce a new one. (Because this is a breaking change in terms of logic in existing code)

It's a breaking change anyway, because this procedure worked correctly in the 22.5 and earlier versions.

**Comment by dannoe** [comment]
I didn't know that, I assumed it was a long-term bug. Ignore my comment then.

**Comment by jonsven** [comment]
Yes, this needs to be fixed. It broke a customization that we have done for a customer. We updated a field when this method returned true, but now it never does.
We solved it by changing to the new overload where the parameter Enqueue is added.

**Comment by JesperSchulz** [comment]
Great catch! And thank you for reporting the issue. Unfortunately, this repository isn't the right place to report your bug.

In this repository you can create issues concerning the extensibility of Business Central, such as missing events. You can also create issues you would like to fix yourself in the code present in this repository, which are our 1st party apps.

Your bug seems to be BaseApp code though, which only can get addressed in our [BaseApp contribution pilot](https://github.com/microsoft/BusinessCentralApps). Do you want me to transfer this issue to the BaseApp pilot repository?

Note, that the transferred issue would have to get approved in triage and you would have to create a pull request yourself. GitHub is not the right place to report issues you would like Microsoft to address. For that, please create a support request.

This case actually strikes me as something Microsoft should address... A support case sounds like the right path here.

PS: You need to be granted access to the pilot repo, if you would like to collaborate on the BaseApp with us. To get access, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

PPS: I recognize that the process on where you can report which issues is a bit messy these days. We're in between processes and hope to be able to streamline and document the right processes in the very near future.
