### ISSUE TITLE
[Refactor] Move procedures from "Outlook Synch. Type Conv"

### ISSUE THREAD

**Issue by christianbraeunlich** [microsoft/ALAppExtensions#25646]
### Describe the request

Move the code from the **Outlook Synch. Type Conv** module to a more precise codeunit in order to decouple this more general functionality from the **CRM.Outlook** module.

### Additional context

It is usually a good idea to use functions that are already available. To use them, we first have to find them. Usually we look for a good name for the codeunit that pretty much explains what we want to do. This is not easy, because we need to know that the code is in the Outlook module.

We would assume that the code we are looking for is in the "Data Type Management" codeunit. Perhaps a new codeunit, e.g. "Type Conv. Management" would be more suitable.

In this case, we want to use the **EvaluateTextToFieldRef** procedure. To find this procedure, we have searched for code that contains the following line: `case FldRef.Type of`.

Please move the code to a codeunit in the System Application and refer to it in the Outlook module if required.

**Comment by pri-kise** [comment]
@christianbraeunlich is this some requirement you'd like to fix by yourself?

If it's related to an improvement for the system application then this issue might be better at the new repository.
https://github.com/microsoft/BCApps

Additionally this issue is very general therefore I'd think the new repository would require an idea created on https://aka.ms/bcideas first.

@JesperSchulz what would you suggest here?

**Comment by JesperSchulz** [comment]
You are completely correct, @pri-kise. @christianbraeunlich, if this is an issue you'd like to address yourself, try to create an issue in the BCApps repository and have it triaged. If you want Microsoft to address this issue, you could try to create a BCIdea, but I don't think the chances for success that way are huge. Historically, refactoring projects have a hard time getting votes, unless they include some direct customer value too.
