### ISSUE TITLE
[Bug]: Selecting Questions in Contact Profiles

### ISSUE THREAD

**Issue by Thuc-Bang** [microsoft/ALAppExtensions#25854]
### Describe the issue

Our customer noticed that questions can be selected in contact profiles. If you select a question, an error message appears. 
![image](https://github.com/microsoft/ALAppExtensions/assets/159121285/41e7c6dc-fc22-4ef0-9812-6fa4b5fabfbf)

We would suggest you to implement the attached code so that the field is not editable beforehand. 
![image](https://github.com/microsoft/ALAppExtensions/assets/159121285/75669d93-c9d0-4ecf-8fe6-1a7740c50fe8)

This is how you can avoid unneccesary clicks for the customer. Could you please integrate this into the Business Central standard? The Microsoft support team asked me to post this here. Thank you very much!

### Expected behavior

The field should not be editable for questions.

### Steps to reproduce

Open the Contact Card.
Open the Contact Profiles.
Select a Question.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
I'm afraid support misinformed you 😟 I will talk to support about that.

This repository is only for extensibility requests or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

But since your request is very fair and you've already provided a solution, I will address the issue for the upcoming major release. But going forward, please don't use this repository for bug reports.

Thank you for your bug report!
