### ISSUE TITLE
[Bug] page "Error Messages Part".SetRecordID() unused parameter

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#25941]
### Describe the issue

There is a method `SetRecordID` in a `page "Error Messages Part"` with a parameter `recordID: RecordID`. But this parameter is not used anywhere. Instead of, `Rec.RecordId` is used in `ErrorMessage.SetRange("Record ID", Rec.RecordId)` statement.

### Expected behavior

```al
    procedure SetRecordID(recordID: RecordID)
    var
        ErrorMessage: Record "Error Message";
        TempErrorMessage: Record "Error Message" temporary;
    begin
-       ErrorMessage.SetRange("Record ID", Rec.RecordId);
+       ErrorMessage.SetRange("Record ID", recordId);
        ErrorMessage.CopyToTemp(TempErrorMessage);
        SetRecords(TempErrorMessage);
        CurrPage.Update();
    end;
```

### Steps to reproduce

see the code

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Sounds fair, but since the code you are referring to is in the BaseApp, you'd have to suggest and fix this code in the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

This repository is only for extensibility requests or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

Would you like me to move the issue to the contribution pilot for you?

**IMPORTANT:** Microsoft is not going to address the reported issue for you. You will have to get the issue approved, and then push a pull request with the suggested changes yourself. If you would like Microsoft to address the issue, please create a support request.

**Comment by RadoArvay** [comment]
I already have a access to contribution pilot. So I can try to do my first contribution...

**Comment by RadoArvay** [comment]
[microsoft/BusinessCentralApps/633](https://github.com/microsoft/BusinessCentralApps/issues/633)
