### ISSUE TITLE
[Event Request] Page 9807 "User Card" OnBeforeSetUserName

### ISSUE THREAD

**Issue by GMATest** [microsoft/ALAppExtensions#25958]
### Describe the request

Hello, would it be possible to add OnBeforeSetUserName event on SetUserName() procedure in page 9807 "User Card", like this:

```
    local procedure SetUserName()
    var
        IsHandled: Boolean;
    begin
        OnBeforeSetUserName(Rec, xRec, WindowsUserName, IsHandled); // New event
        if not IsHandled then
            "User Name" := WindowsUserName;

        ValidateUserName();
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetUserName(var User: Record User; var xUser: Record User; WindowsUserName: Text[208]; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

We need to modify WindowsUserName() returned value.
Internal work item: [AB#501684](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501684)

**Comment by haoranpb** [comment]
Hi @GMATest 

Thanks for opening an event request.

After reviewing the proposed event and provided context, my understanding is that you'd like to display a customized user name instead of the standard `Windows User Name` field? Would an alternative using page extensions to hide the standard field and add a customized field `My Customized User Name` be suitable for you scenario?

The standard `Windows User Name` field is designed to specifies the name of a valid Active Directory user, using the format domain\username.

I will close this issue for now, if you have follow-up questions or requests, we do not monitor closed issues, so please create a new issue where you reference this one.
