### ISSUE TITLE
Add new functionality in OnAfterGetRecord() trigger to format address in Report 1309 "Standard Sales - Return Rcpt.", Report 6636 "Purchase - Return Shipment", Report 407 "Purchase - Credit Memo", Report 408 "Purchase - Receipt", Report 1307 "Standard Sales - Credit Memo", Report 1306 "Standard Sales - Invoice", Report 1305 "Standard Sales - Order Conf."

### ISSUE THREAD

**Issue by SerhiiKorniichuk1** [microsoft/ALAppExtensions#26119]
### Describe the request

Hello, please, add new functionality in dataitem where CompanyAddr[] columns (CompanyAddr: array[8] of Text[100]) is located 

trigger OnAfterGetRecord()
var
FormatAddr: Codeunit "Format Address";
RespCenter: Record "Responsibility Center";
begin

FormatAddr.GetCompanyAddr(RespCenter.Code, RespCenter, CompanyInfo, CompanyAddr);

end;

Reports that need to be modified:

- Report 1309 "Standard Sales - Return Rcpt.", 
- Report 6636 "Purchase - Return Shipment", 
- Report 407 "Purchase - Credit Memo", 
- Report 408 "Purchase - Receipt", 
- Report 1307 "Standard Sales - Credit Memo", 
- Report 1306 "Standard Sales - Invoice", 
- Report 1305 "Standard Sales - Order Conf."

### Additional context

This is necessary to enable the ability update address due to "Responsibility Center" ect.

**Comment by JesperSchulz** [comment]
Unfortunately, this repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

For suggestions to the Business Central product group, please create a [BC Idea](https://aka.ms/bcideas).

You could choose to suggest to implement the changes yourself, but since the code you are referring to is in the BaseApp, you'd have to suggest and fix this code in the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.
