### ISSUE TITLE
Make procedures public in codeunit 9660 - "Report Layouts Impl."

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#26246]
### Describe the request

Hi

Can you please remove internal from the two following procedures in codeunit 9660 - "Report Layouts Impl."?

```
// >>>>>>>>>>
// internal procedure SetSelectedCompany(NewCompanyName: Text)
procedure SetSelectedCompany(NewCompanyName: Text)
// <<<<<<<<<<
begin
    SelectedCompany := CopyStr(NewCompanyName, 1, MaxStrLen(SelectedCompany));
end;
```

```
// >>>>>>>>>>
//internal procedure SetDefaultReportLayoutSelection(SelectedReportLayoutList: Record "Report Layout List"; ShowMessage: Boolean)
procedure SetDefaultReportLayoutSelection(SelectedReportLayoutList: Record "Report Layout List"; ShowMessage: Boolean)
// <<<<<<<<<<
var
    ReportLayoutSelection: Record "Report Layout Selection";
begin
    // Add to TenantReportLayoutSelection table with an Empty Guid.
    AddLayoutSelection(SelectedReportLayoutList, EmptyGuid);
....
```

### Additional context

We need this to be able to set new report layouts as default during install/upgrade or programatically.
Internal work item: [AB#524438](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524438)

**Comment by fvet** [comment]
@darjoo @JesperSchulz Any chance of making this available in next minor (24.2). We would like to set report layouts by code, following this blog post (https://yzhums.com/39955/) but want to avoid the code cloning path.

**Comment by JesperSchulz** [comment]
> @darjoo @JesperSchulz Any chance of making this available in next minor (24.2). We would like to set report layouts by code, following this blog post (https://yzhums.com/39955/) but want to avoid the code cloning path.

24.2 will be tight. We're code complete on that one tomorrow. 24.3 should be doable though!

**Comment by JesperSchulz** [comment]
@andersws / @fvet, given that the entire codeunit is "internal", it wouldn't help much to make the two procedures public. Exposing the entire impl. codeunit is a whole different story, which would require a larger discussion. But I assume that is the request you're giving us?

**Comment by fvet** [comment]
The functional requirement we're trying to solve, is to be able to simply mark a report layout as '**Default**' via AL code 
(similar to the 'Set Default' action on the report layouts list page) 

Like explained here, but without code cloning: https://yzhums.com/39955/

---

**Some background:** 
Using the 'DefaultRenderingLayout' option on the report is not a solution for us.

In v1 of our app, we shipped on rdlc file. Some versions later, we introduced an additional rdlc version. 

![image](https://github.com/microsoft/ALAppExtensions/assets/25268332/2b009253-70d3-4745-a388-d5e146999a7c)

This new rdlct is in fact to be used for **new** installs of our app. **Existing** customers / installs should **not** be impacted.

If we would set the 'DefaultRenderingLayout' to the new rdlc, existing customers would be impacted. That's why we'd like to set newest rdlc version as default layout for new installs only (though AL)

**Comment by fvet** [comment]
@JesperSchulz Any update if we might expect access to the requested functions ? 
I've a new request where I need to detect if a report layout is set as 'Default' or not, but am blocked here as well :(

**Comment by JesperSchulz** [comment]
> @JesperSchulz Any update if we might expect access to the requested functions ? I've a new request where I need to detect if a report layout is set as 'Default' or not, but am blocked here as well :(

I will check up on the status for you! Stay tuned.

**Comment by nhsejth** [comment]
DefaultRenderingLayout is only used by the platform if you don't add any tenant specific layout selection (used as fallback when layout selection is empty). 
The best strategy is always to set the layout selection from applikation code if you want to ensure that users use a specific layout. You can accomplish this from your extension install process if you check for missing layout selection in the tenant and then add a selection for the existing users pointing to the previous layout assuming that it's still being shipped in the new extension version. Existing users will then no notice any layout changes when they update the extension to V2 and they are free to chose a new default if they want.

We are not going to move the two requested functions out of internal scope as there are dependencies to page specific behavior. Also notice that the use case mentioned in the blog post is not following best practices as you should never set the tenant default from a specific record (in this case the Sales Header). If you want a specific layout for a customer or invoice, then use the temporary layout selection features built around the codeunit 9654 "Design-time Report Selection". You find the access functions in table 9651 "Report Layout Selection". Here you only set the layout selection for the current session using a single instance codeunit and you will not impact other others depending on the same report (think about the scenario where you print using the job queue and some sales header select a new default layout for the whole company/tenant - this will cause a high number of support calls due to incorrect / unexpected layouts being used). Notice that you should only user the selections based on layout name as the legacy functions using code key will be deprecated as they use layouts stored in the deprecated Custom Report Layout table.

If needed, we could add generic function in the Report Management Helper codeunit to set/get the default layout for a given report.
