### ISSUE TITLE
[Event Request] codeunit 30246 "Shpfy Create Sales Doc. Refund" - OnBeforeReleaseSalesDocument

### ISSUE THREAD

**Issue by dagviggobyx** [microsoft/ALAppExtensions#26342]
### Describe the request

Could you please add an event "OnBeforeReleaseSalesDocument" in procedure CreateSalesLines:

![image](https://github.com/microsoft/ALAppExtensions/assets/104152494/f85e97a4-b017-4f8f-be3d-054c2b304a48)

https://github.com/StefanMaron/MSDyn365BC.Code.History/blob/16b2d0ffb2e4e8fc51ebaffed3f3438ea065eb4d/shopify/app/Shopify%20Connector/src/Order%20Return%20Refund%20Processing/Codeunits/ShpfyCreateSalesDocRefund.Codeunit.al#L45

### Additional context

Need to manipulate the sales header after header and lines are created, but before it's released
Internal work item: [AB#527163](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527163)

**Comment by onbuyuka** [comment]
Please check the following yammer post of @AndreiPanko
https://www.yammer.com/dynamicsnavdev/threads/1762140027789312

As you know the Shopify Connector is made non-extensible. We plan to change it in the future, and we want to try a different model.

Motivation: we want to avoid misuse of extensibility to address bugs, minor improvements, or gaps – all of that end-user expects to be part of product. Millions of events spread across the code reduce readability and scalability, increase maintenance and upgrade costs for all parties.

As source code of Shopify Connector is on GitHub we would like to reuse pattern we have for System App:

Prioritize submitting improvement over extensibility. For example, if your customer needs to export multiple translations of a product to Shopify, instead of asking for making some objects extensible – submit PR that implements this feature.
If extensibility is really necessary – for example to orchestrate multiple extensions dealing with various sales channels – please create PR directly. Remember to write the proper justification of scenario.
We will not process extensibility requests for connector registered as Issues on GitHub.
