### ISSUE TITLE
[Event Request]Add new event to apply filters on Approval Entry Record that sets controller appearance on different windows as expected with business central approach.

### ISSUE THREAD

**Issue by arvindbinarystream** [microsoft/ALAppExtensions#26375]
### Describe the request

#26275

### Additional context

@haoranpb , thanks for responding on above issue. 
The reason behind asking for those integration events is that to ensure that we don't break business central behavior with our product. We are actually replacing those page controller values using page extensions and our implementation but it seems business central keep enhancing workflow process and adding new fields and actions around workflows. 
Also, these integration events are not only to set controllers on pages but also to ensure that we are restricting and allowing correct records with workflows while posting journals or during any other process that is impacted by approval workflows.

**Comment by haoranpb** [comment]
Hi @arvindbinarystream , thanks for the response!

I'm still not sure how those events can be utilized for your scenario. Can you share some examples with one or some of those events? (doesn't need to be code, description would work)

> business central keep enhancing workflow process and adding new fields and actions around workflows.

Workflow related logic should be fairly stable now, if there are changes that we rolled out that affect your implementation, can you share an example and we will look into it?


Let's keep the discussion in this issue, I will be monitoring it

**Comment by arvindbinarystream** [comment]
Hi @haoranpb, thanks for the response.

Here's the example about what we need to achieve.

1) 
In Business Central, when requester sends an approval for the journal batch (**Daily**), then the status of the approval for that journal batch is updated to the "Pending Approval" value. Which is correct.

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/085d5316-2121-4494-8a73-4b5048f1d403).

But with our product, the Journal batches are differentiated with an additional field.
And approvals for the journal batches are requested or approved based on that particular field.
Requester sends request for batch daily with **company** (additional field on which journal batch is differentiated) 000. The status of the batch should be set to "Pending Approval".
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/a13fa22a-2b79-4c7c-b19a-61ae5a34a951)

The issue here is when user selects different **company** (ex: 200), business central shows "Pending Approval" status for the batch which we need to support. (As business central check Journal batch status using RecordId.) 
That's why we need integration event 'OnFindApprovalEntryByRecordIdOnAfterSetApprovalEntryFilters' to check approval entry for journal batch with specific **company**.

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/7331a26a-fcac-42bb-b183-422b6ce43d4e)

2)
Also, when requester approves an approval request for Journal Batch, business central removes restriction from all journal lines that allows users to post journal batch. 

With our product we need to restrict user from posting journal batch based on **Company** related journal batch if it's not approved by the approver.

As of now, If approver user approves Journal batch Daily with **Company** 000, business central allows users to post Journal batch Daily with **Company** 200. Even if batch Daily with the **Company** 200 is not approved.

That's why we need integration event 'OnAllowGenJournalBatchUsageOnAfterSetGenJournalLineFilter'.

######################################

Similar to above examples we need all the requested integration events that I mentioned on https://github.com/microsoft/ALAppExtensions/issues/26275 issue.

There are few integration events that Business Central already provided previously, I need additional variables to be added on those integration events (Which I have already mentioned on the above issue), If that's not possible then you can ignore it.

**Comment by haoranpb** [comment]
@arvindbinarystream , thanks for reply.

After discussing this internally, we think the solution you are building is very different from the standard Business Central functionality. (e.g. the Approval Entry table is designed to be [DataPerCompany](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-datapercompany-property), all the flowfields in Approval Entry table won't take customized fields into account)

In general, we are trying to add fewer events going forward. My colleague has provided an explanation here: https://github.com/microsoft/ALAppExtensions/issues/24975#issuecomment-1807965838 .

In addition to the reasons mentioned in that comment. The events being requested here:
1. They are not generic enough for everyone else to use them. If other folks utilize them, it might start to cause problem for your solution because [You can't specify the order in which the subscriber methods are called](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-subscribing-to-events).
2. The whole standard Approval functionality is not designed this way, you'll have to add many customized code where any logic change in standard Approval functionality might break you.

Given all of the above, we would like to suggest that: you instead, copy paste the whole standard Approval related functionality and customized it to suit your own need. This way, you can guaranty that no code change from standard BC will affect your solution; and you can design whole the Approval functionality to tailor to your own need.
