### ISSUE TITLE
[Extensibility] table 30110 "Shpfy Gift Card" table Access is internal

### ISSUE THREAD

**Issue by LIDDHendrikTeixeira** [microsoft/ALAppExtensions#26385]
### Describe the request

We need to extend the  connector and be able to read from t he table 30110 "Shpfy Gift Card" from a outside extension however the table has access to internal.

### Additional context

To be able To read and determine from outside if any shopify gift cards have been imported and regularly read the available balance. 
Internal work item: [AB#538699](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538699)

**Comment by onbuyuka** [comment]
Please check the following yammer post of @AndreiPanko
https://www.yammer.com/dynamicsnavdev/threads/1762140027789312

As you know the Shopify Connector is made non-extensible. We plan to change it in the future, and we want to try a different model.

Motivation: we want to avoid misuse of extensibility to address bugs, minor improvements, or gaps – all of that end-user expects to be part of product. Millions of events spread across the code reduce readability and scalability, increase maintenance and upgrade costs for all parties.

As source code of Shopify Connector is on GitHub we would like to reuse pattern we have for System App:

Prioritize submitting improvement over extensibility. For example, if your customer needs to export multiple translations of a product to Shopify, instead of asking for making some objects extensible – submit PR that implements this feature.
If extensibility is really necessary – for example to orchestrate multiple extensions dealing with various sales channels – please create PR directly. Remember to write the proper justification of scenario.
We will not process extensibility requests for connector registered as Issues on GitHub.
