### ISSUE TITLE
[Bug]: table 290 "VAT Amount Line"

### ISSUE THREAD

**Issue by innonav-dev** [microsoft/ALAppExtensions#26387]
### Describe the issue

In procedure SetInvoiceDiscountAmount(NewInvoiceDiscount: Decimal; NewCurrencyCode: Code[10]; NewPricesIncludingVAT: Boolean; NewVATBaseDiscPct: Decimal):

Within calculation of "Invoice Discount Amount"

```
 if "Invoice Discount Amount" <> Round(NewRemainder, Currency."Amount Rounding Precision") then begin
     Validate(
         "Invoice Discount Amount", Round(NewRemainder, Currency."Amount Rounding Precision"));
     CalcVATFields(NewCurrencyCode, NewPricesIncludingVAT, NewVATBaseDiscPct);
     Modified := true;
     Modify();
end;
```

### Expected behavior

Instead of Currency."Amount Rounding Precision", field Currency."Invoice Rounding Precision" should be used for invoice amounts.

Our suggestion:

```
if "Invoice Discount Amount" <> Round(NewRemainder, Currency."Invoice Rounding Precision") then begin
    Validate(
        "Invoice Discount Amount", Round(NewRemainder, Currency."Invoice Rounding Precision"));
        CalcVATFields(NewCurrencyCode, NewPricesIncludingVAT, NewVATBaseDiscPct);
        Modified := true;
        Modify();
end;
```

### Steps to reproduce

Set up Currency with different rounding values before calling the procedure SetInvoiceDiscountAmount(...)

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by RadoArvay** [comment]
Why should be used this type of amount rounding?? "Invoice Rounding Precision" is meant for document rounding, not particular amounts. Or...?

**Comment by JesperSchulz** [comment]
You might be on to something here, but since the code you are referring to is in the BaseApp, you'd have to suggest and fix this code in the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

This repository is only for extensibility requests or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

Would you like me to move the issue to the contribution pilot for you?

**IMPORTANT:** Microsoft is not going to address the reported issue for you. You will have to get the issue approved, and then push a pull request with the suggested changes yourself. If you would like Microsoft to address the issue, please create a support request.

**Comment by JesperSchulz** [comment]
Please open issue in BusinessCentralApps repo, if you would like to address this issue.
