### ISSUE TITLE
[Bug]: Merge Customers with existing Sales Shipment Headers

### ISSUE THREAD

**Issue by JDEnergieversum** [microsoft/ALAppExtensions#26416]
### Describe the issue

We noticed duplicate customers in our system.
So we used the "Merge Duplicate" Feature to get rid of them.
This was working fine, until we tried to merge two customers, where one of already had a posted Sales Shipment/Invoice.
Now we are getting an Error, that we are missing the permission to modify the record.
I was using a Super user.
Table 64 -> Function UpdateIDs -> RecRef.Modify();

I think it has to be outsourced into a Codeunit and the codeunit needs the permission to Update the Record.

"Merge Duplicates Buffer"(Table 64).UpdateIDs line 19 - Base Application by Microsoft
"Merge Duplicates Buffer"(Table 64).MergeRecords line 21 - Base Application by Microsoft
"Merge Duplicates Buffer"(Table 64).MergeCustomers line 11 - Base Application by Microsoft
"Merge Duplicates Buffer"(Table 64).Merge line 12 - Base Application by Microsoft
"Merge Duplicate"(Page 702)."Merge - OnAction"(Trigger) line 2 - Base Application by Microsoft
 

### Expected behavior

We expect them to change the Customer ID to the merged one and not throw an error.

### Steps to reproduce

Create two customers.
Create a Posted Sales Shipment for the Customer.
Try to merge them, while keeping the Customer No. of the customer without the Shipment.

### Additional context

"Merge Duplicates Buffer"(Table 64).UpdateIDs line 19 - Base Application by Microsoft
"Merge Duplicates Buffer"(Table 64).MergeRecords line 21 - Base Application by Microsoft
"Merge Duplicates Buffer"(Table 64).MergeCustomers line 11 - Base Application by Microsoft
"Merge Duplicates Buffer"(Table 64).Merge line 12 - Base Application by Microsoft
"Merge Duplicate"(Page 702)."Merge - OnAction"(Trigger) line 2 - Base Application by Microsoft
 

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Sounds like you might be on to something here, but since the code you are referring to is in the BaseApp, you'd have to suggest and fix this code in the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

This repository is only for extensibility requests or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

Would you like me to move the issue to the contribution pilot for you?

**IMPORTANT:** Microsoft is not going to address the reported issue for you. You will have to get the issue approved, and then push a pull request with the suggested changes yourself. If you would like Microsoft to address the issue, please create a support request.

**Comment by JesperSchulz** [comment]
Please open an issue in the BusinessCentralApps repo.
