### ISSUE TITLE
[Event Request] codeunit 11029 "IntrastatReportManagementDE" OnAfterSetDataExchExportParameters

### ISSUE THREAD

**Issue by Kryshi** [microsoft/ALAppExtensions#26637]
### Describe the request

Please add the posibility to modify the value of the variables being written into the XML file during Intrastat File Creation in the German version. This could be either implemented in the procedure SetDataExchExportParameters as an OnAfter event exposing all the calculated global variables (VATIDNo, MessageID, CreationDate etc...) or by directly putting an event in the case statement inside local procedure OnBeforeCreateXMLNodeWithoutAttributes.

### Additional context

Our use case involves a custom field on the Company Setup that is only to be used in the Intrastat Report File Creation action. In the codeunit, there is no way to alter the calculation of the variables while creating the XML file.
Internal work item: [AB#538379](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538379)

**Comment by AndersLarsenMicrosoft** [comment]
Could you please be more specific on this request. We fail to see what is missing in this report and is there a gab with the legal requirement?

Why is there a need to add more info to the XML and what 

reactivate or create a new request (with a link to this) when you have the info

**Comment by Hilbekale** [comment]
@AndersLarsenMicrosoft: 

We have a similar issue. One of our clients has multiple companies in BC. However they need to report Intrastat based on one Registration Number of the main company. However the sub companies do have their own Registration Numbers. 

It is impossible to replace the values of the fields with an event or any other logic. We can not change the registration number in the sub companies, since it should be printed on reports. 

<img width="1255" height="653" alt="Image" src="https://github.com/user-attachments/assets/0f96fb80-03e1-459b-a428-d5af9b40762b" />

Therefore it would be actually pretty nice if it would be possible to modify at least the "Registration No." with an event.

Maybe you can reopen the issue and give me some feedback here. 

We discovered the issue while upgrading custom logic from NAV2017 to BC.

The alternative is to change all other places in which the registration number of the company information is used and that is nearly impossible.
