### ISSUE TITLE
Mark Request as shipped

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#2710]
Hi,

in my company we have a lot of requests, that are labled "ships in future update".
Some of those are available some aint.
Would it be possible to add a new label "shipped" like it was done in the Microsoft/AL?

Thanks

**Comment by ikoletic** [comment]
All the code changes are available on insider builds that gets out of branch internal teams are working on as well. Recently there was a temporary stop of insider builds shipping due to switch to AL (see Freddy's blog [here](https://freddysblog.com/2019/05/29/business-central-fall-2019-preview-availability/)).
As there are requests that are safe to go out in minor release and some that need to go out only in major, this creates additional overhead which is time better spend on handling additional requests coming from partner. Thank you for understanding.
