### ISSUE TITLE
[Scope Change] Table 2000000187 "Tenant Profile Page Metadata"

### ISSUE THREAD

**Issue by KarelKoncel** [microsoft/ALAppExtensions#27355]
### Describe the request

Please remove the scope OnPrem for table 2000000187 "Tenant Profile Page Metadata"

### Additional context

we are using it for copying profile page metadata to another profile - onPrem it work fine, but becouse Universal Code, we cannot use onPrem... 
Internal work item: [AB#551205](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551205)

**Comment by nhsejth** [comment]
It will be better to use the base app functionality to copy profile data. The "internal" tables in OnPrem scope should not be used by extensions. 
The base application have function CopyProfile  to handle this, and if that functionality is insufficient, please create a new issue for extending that functions.

**Comment by nhsejth** [comment]
Yes, the best approach is a new function in codeunit 9170 "Conf./Personalization Mgt." that can handle this copy. Keep in mind that most of the system tables are designed for internal platform use and internal use in the base application with a codeunit facade to hide the implementation.  It adds unnecessary constraints to the platform when the tables are made public and open for external use in SaaS, and we have had plenty of cases where the tables ended up being used for something unintended and then very hard to hard internally.
That's why I am a bit reluctant to open access to platform tables in general.
