### ISSUE TITLE
[Event Change Request] codeunit 30189 "Shpfy Variant API" OnBeforeSendAddShopifyProductVariant

### ISSUE THREAD

**Issue by tBrognoli** [microsoft/ALAppExtensions#27590]
### Describe the request

I would like to submit a request regarding our integration between Business Central and Shopify. We need to add additional information to the product synchronization, such as InventoryItem.CountryCodeOfOrigin and InventoryItem.HarmonizedSystemCode. To achieve this, we need to be able to add additional fields (removing the internal tag) on the InventoryItem table and to customize the request adding product variants (adding "isHandled")

````
internal procedure AddProductVariant(var ShopifyVariant: Record "Shpfy Variant"): Boolean
var
        ShopLocation: Record "Shpfy Shop Location";
        NewShopifyVariant: Record "Shpfy Variant";
        JResponse: JsonToken;
        GraphQuery: TextBuilder;
        IsHandled: Boolean;
begin
        ProductEvents.OnBeforeSendAddShopifyProductVariant(Shop, ShopifyVariant, IsHandled);
        if IsHandled then
        exit;
...
````

````
[IntegrationEvent(false, false)]
internal procedure OnBeforeSendAddShopifyProductVariant(ShopifyShop: Record "Shpfy Shop"; var ShopifyVariant: Record "Shpfy Variant"; IsHandled: Boolean)
begin
end;
````

````
table 30126 "Shpfy Inventory Item"
{
    Caption = 'Shopify Inventory Item';
    DataClassification = CustomerContent;
...
}
````

### Additional context

The Shopify connector doesn't fully respond to our customer need.
Internal work item: [AB#556907](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556907)

**Comment by onbuyuka** [comment]
We cannot add this event. IsHandled events are anti pattern, in this case it gives ability to completely bypass Microsoft code that creates and sends the request to create a variant in Shopify.

I also do not fully understand your scenario. "Shpfy Inventory Item" table is only used for importing, not exporting. But the event you are interested in is used when exporting. 

We have taken a different approach with Shopify Connector extensibility, so let's try that:

_"As you know the Shopify Connector is made non-extensible. We plan to change it in the future, and we want to try a different model._

_Motivation: we want to avoid misuse of extensibility to address bugs, minor improvements, or gaps – all of that end-user expects to be part of product. Millions of events spread across the code reduce readability and scalability, increase maintenance and upgrade costs for all parties._

_As source code of Shopify Connector is on GitHub we would like to reuse pattern we have for System App:_

_Prioritize submitting improvement over extensibility. For example, if your customer needs to export multiple translations of a product to Shopify, instead of asking for making some objects extensible – submit PR that implements this feature.
If extensibility is really necessary – for example to orchestrate multiple extensions dealing with various sales channels – please create PR directly. Remember to write the proper justification of scenario.
We will not process extensibility requests for connector registered as Issues on GitHub."_
