### ISSUE TITLE
[Bug]: Report 5692 "Calculate Depreciation" - procedure OnBeforeActivateErrorMessageHandling - incorrect first parameter name

### ISSUE THREAD

**Issue by Audrius-LT** [microsoft/ALAppExtensions#27718]
### Describe the issue

In report 5692 "Calculate Depreciation" procedure OnBeforeActivateErrorMessageHandling first parameter name varFixedAsset is incorrect.

### Expected behavior

Space needed. Instead of:
procedure OnBeforeActivateErrorMessageHandling(varFixedAsset: Record "Fixed Asset"; ...
must be:
procedure OnBeforeActivateErrorMessageHandling(var FixedAsset: Record "Fixed Asset"; ...

### Steps to reproduce

 -

### I will provide a fix for a bug

- [x] I will provide a fix for a bug
Internal work item: [AB#559871](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559871)

**Comment by JesperSchulz** [comment]
Given that this bug is in the BaseApp, this isn't the right repo to log the bug in. This repository is only for extensibility requests or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

But given the simplicity of this bug, I will create fix 😊
