### ISSUE TITLE
Codeunit 5470 Graph Collection Mgt - Item - Exposing function InsertItem for AL development

### ISSUE THREAD

**Issue by zulezmaj** [microsoft/ALAppExtensions#2920]
Can you make function InsertItem externally available in Codeunit 5470 Graph Collection Mgt - Item?

From 14.0 we are not able anymore to make page extensions of API pages in AL.

Currently I am working on API page for Items where I am using native Item Entity page as template and therefore I need function InsertItem to be available for access from AL.

**Comment by kculpepperhpc** [comment]
Was this just dropped?  No updates since 2019.  I see the AL page code:

https://github.com/microsoft/ALAppExtensions/blob/master/Apps/W1/APIV2/app/src/pages/APIV2Items.Page.al

but when I try to include the OnInsertRecord, I get this:

'Codeunit "Graph Collection Mgt - Item"' does not contain a definition for 'ModifyItem'AL(AL0132)
