### ISSUE TITLE
[Bug] Codeunit 80 ModifyTempLine / Codeunit 90 ModifyTempLine

### ISSUE THREAD

**Issue by sharkphoenix** [microsoft/ALAppExtensions#2954]
At the codeunits 80 and 90 there is a bug at the function ModifyTempLine.

In some cases you will get the wrong temprecord values and also get an error that you relate to an old entry.

Our Team made a fix of it:

Codeunit 90:
Standard was:
TempPurchLineLocal.MODIFY;
PurchLine := TempPurchLineLocal;
PurchLine.MODIFY;

New Code:
TempPurchLineLocal.MODIFY;
IF PurchLine.GET(TempPurchLineLocal.RECORDID) THEN
   PurchLine.DELETE;

  PurchLine.INIT;
  PurchLine := TempPurchLineLocal;
  PurchLine.INSERT;

Codeunit 80:
Standard:
TempSalesLineLocal.MODIFY;
SalesLine := TempSalesLineLocal;
SalesLine.MODIFY;

new Code:
TempSalesLineLocal.MODIFY;
  IF SalesLine.GET(TempSalesLineLocal.RECORDID) THEN
   SalesLine.DELETE;

  SalesLine.INIT;
  SalesLine := TempSalesLineLocal;
  SalesLine.INSERT;

**Comment by StanPesotskiy** [comment]
@sharkphoenix
Could you provide repro steps leading to the error?
With the suggested fix we have +2 additional SQL requests comparing to the original state:
GET + DELETE + INSERT instead of one MODIFY. 
Having a failing scenario would help a lot to understand how to fix it optimally. 

I would try to keep MODIFY but reread the record and replace the assignment with TRANSFERFIELDS:

```
TempPurchLineLocal.MODIFY;
PurchLine.GET(TempPurchLineLocal.RECORDID);  // to refresh the timestamp
PurchLine.TRANSFERFIELDS(TempPurchLineLocal,FALSE); // here we don't copy PK and the timestamp
PurchLine.MODIFY;
```
Would it work right and faster?

**Comment by sharkphoenix** [comment]
yeah it works :) 
in our case we modified a lot of times the line and in one special case it crashes because of the timestamp. But this fix helps. Could you add it to the next CU :)?

**Comment by jobulsin** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
