### ISSUE TITLE
[EventRequest] CU427 – function „CreateSalesDocument“ 

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#3191]
We need a new Publisher „OnAfterInsertHandledICInboxSalesLine“ in function „CreateSalesDocument“ in CU427 
![image](https://user-images.githubusercontent.com/40287548/60812577-1e782c00-a192-11e9-85b9-058ba0fa1a70.png)
Thanks

**Comment by StanPesotskiy** [comment]
@AndreBreitenbach 
There is already event OnBeforeHandledICInboxSalesLineInsert(HandledICInboxSalesLine,ICInboxSalesLine); just before INSERT.
![image](https://user-images.githubusercontent.com/41332028/60873851-b5e78880-a23f-11e9-8f3f-04680b537c8e.png)

Would it work for you? 
You requested many OnAfterXInsert events, though OnBeforeXInsert would allow you to update the record before INSERT,  while after INSERT you will have to do MODIFY to update the record. 
What is the reason that you prefer OnAfterInsert in COD427?

**Comment by AaronSchwarz** [comment]
@StanPesotskiy 
I'm the developer that needs to use these requested Events, and was asked by @AndreBreitenbach to clarify.

Our need is not to modify the inserted Rec, but update/copy attached information (e.g. Extended Texts) in different tables from the Source-Rec to the new Rec. This Information is linked via RecordID. If there were changes to the PK of the new Rec before Insert (Insert-Trigger, or OnBeforeInsert-Event), our data gets lost.

But you are correct, at the moment all events asked for in CU427 would work with an OnBeforeInsert, because so far the PK is always complete before Insert by TRANSFERFIELDS or additional code to fill the PK.

**Comment by StanPesotskiy** [comment]
Thanks, @AaronSchwarz 
Then we will implement all these typical events in cod427 as OnBeforeInsert so it will help you and may cover future needs.
