### ISSUE TITLE
[Refactoring] Codeunit 80 - OnRunOnBeforeFinalizePosting

### ISSUE THREAD

**Issue by boych83** [microsoft/ALAppExtensions#3308]
Hello,

we need new event or refactoring existing one. 
This is related to [Issue-1205](https://github.com/microsoft/ALAppExtensions/issues/1205) where this event was requested.

We have solution which needs to add new entries to same transaction but we are unable to do that if option that executes function **MakeInventoryAdjustment()** is enabled.

When subscribing to **_OnRunOnBeforeFinalizePosting_** event handler parameter **_GenJnlPostLine_** is not aware of additional entries which are done through **MakeInventoryAdjustment()**

Solution:
- add new similar even handler to **_OnRunOnBeforeFinalizePosting_** before calling **MakeInventoryAdjustment()**
- fully updated parameter _**GenJnlPostLine**_ on existing event handler

<br>

```
...
 <-- new Eventtrigger

MakeInventoryAdjustment;
UpdateLastPostingNos(SalesHeader);

OnRunOnBeforeFinalizePosting(
SalesHeader,SalesShptHeader,SalesInvHeader,SalesCrMemoHeader,ReturnRcptHeader,GenJnlPostLine,SuppressCommit);

FinalizePosting(SalesHeader,EverythingInvoiced,TempDropShptPostBuffer);
```

**Comment by RomanZanizdra** [comment]
Hi @boych83 . There are two questions for you:
1) Is this request still relevant and actual for you?
2) If 1=true then could you be a little bit more precise in description on how you want to get required result because I missed if the two points from your description should come together or enough one of them. And what does it mean "fully updated parameter GenJnlPostLine on existing event handler"?

**Comment by RomanZanizdra** [comment]
Hi @boych83 , any update from your side.

**Comment by boych83** [comment]
Hi @RomanZanizdra,

this is no longer relevant to use since we redesigned our solution with other events for v.16.0.X.X.

BR,
Bojan
