### ISSUE TITLE
Non-overridable Application Version / Country in COD9015 

### ISSUE THREAD

**Issue by AskeHolst** [Microsoft/ALAppExtensions#368]
We use the ApplicationVersion procedure in COD9015 to find the country the app is installed on to provide a country relevant first time experience. It works fine for now taking the first part of the ApplicationVersion, e.g. 'DK Dynamics NAV 13.0' means we are on a DK install.
But as ApplicationVersion can be changed by a subscriber there is no guarantee this will always be valid, a random app could change the version to be anything.

I would like to have either a (new) safe/clean ApplicationVersion procedure without any subscribers interfering or an ApplicationCountry procedure returning just the country, again without any subscribers.

**Comment by SKeiler** [comment]
We have an similar Problem. With our ISV we have added our Version Information via the Application Version Event. But another ISV which our customers use too use this Application Version to activate the correct Interface mapping, which doesn't work correctly because of our Version Information additions.  

The existing function should be renamed in OrginalApplicationVersion() without Events and there should be a second function, whichs calls the OrginalApplicationVersion() and hold the Events.

**Comment by IhorHandziuk** [comment]
Thank you for your request and suggestion, function OrginalApplicationVersion() will be available in the future update
