### ISSUE TITLE
Table 1103 : Increase G/L Account Range Field Lenght

### ISSUE THREAD

**Issue by Hamdi-Amine** [microsoft/ALAppExtensions#3924]
Hello Team,
We need to increase the lenght of G/L Account Range field  in table 1103 : Cost Type.
The new length must be 250 .
Actualy, when we select G/L Accounts , the system only take 50 caracters of G/L Account Range.
![image](https://user-images.githubusercontent.com/23724827/63708570-5449a080-c824-11e9-8a00-af12755037a7.png)
Thanks.

**Comment by StanPesotskiy** [comment]
An account range fits inside 42 chars - 'Acc1..Acc2'. The problem happens only if user wants to enter a wider filter inside the range field. 
Changing field's length is considered now to be a breaking change due to a chance that partner's extensions work relying on the current data schema. 
This is more of a design change request and should have been handled via the Ideas site (https://experience.dynamics.com/ideas/)
