### ISSUE TITLE
Opening new company with hyperlink not working

### ISSUE THREAD

**Issue by TimothyWatkins** [microsoft/ALAppExtensions#4114]
There seems to be an issue when opening a newly created company when using the hyperlink function.
Attached (rename txt files to al) is a simple page extension on the customer list calling a new create company page (50100).
The new tab opens with the correct link (new company and page) but simply hangs and does not open. 
(Refreshing the page works or copying and pasting the link works.)
Look forward in hearing a resolution for this issue

[Page 50100 - xxx Create New Company.txt](https://github.com/microsoft/ALAppExtensions/files/3572914/Page.50100.-.xxx.Create.New.Company.txt)
[Page 21 - Customer List.txt](https://github.com/microsoft/ALAppExtensions/files/3572915/Page.21.-.Customer.List.txt)

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - can you help?

**Comment by RomanZanizdra** [comment]
Hi @TimothyWatkins.
I've just tried your objects in SaaS and it didn't work for me at all. Company was created but the new tab was not even opened. I made some changes and split company creation and run link into two separate actions. The company has been created for several minutes. Right after "working on it" banner disappeared from my screen I run the link for the new company and it works perfectly for me.
The next thing i did was performing the same your (creating company and run link at one run) actions for my local instance and it also worked perfectly, company was created and link opened.
So my thoughts on this is that there are no any issues with the HYPERLINK command, i suppose it's because of the time which is required to create the new company. I think the approach for creating a new company and opening it should be changed somehow. Does it make sense for you?

**Comment by TimothyWatkins** [comment]
Yes, you're probably right. We have since however updated our code to use the sessionSetting.RequestSessionUpdate function which is a smoother option and allows the change of company in the same tab. We no longer use the Hyperlink command to open the new company.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
