### ISSUE TITLE
GZip Support

### ISSUE THREAD

**Issue by LutzRose** [microsoft/ALAppExtensions#4156]
With the [C/AL Open Library](https://github.com/microsoft/cal-open-library) there was a GZip support.
In version 15 there is no corresponding module?

**Comment by megel** [comment]
What is the status? We need GZip support too for our products.

**Comment by Diessner** [comment]
Gzip support is needed for app source readiness in our product.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by johalbert** [comment]
We need Gzip support as well to increase web service performance.

**Comment by megel** [comment]
@JesperSchulz any progress for this request?

**Comment by JesperSchulz** [comment]
Please allow me to forward your issue to the engineers, who made the [Data Compression](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Data%20Compression) module. They will get back to you asap!

**Comment by JesperSchulz** [comment]
And sorry about the delayed response. I had set up a too restrictive mail rule which ate all of my notifications :-(

**Comment by dcenic** [comment]
If you want to open a GZip archive stream and read its entries, you can do so by:
DataCompression.OpenZipArchive(GzipInStream, false);
If you want to create an archive in Gzip format - we don't support that in Data Compression module. Please keep in mind that we never had a wrapper for GZipStream .NET class in BaseApp - we use GZipStream .NET class directly in a few places in BaseApp.

If you would like to get the ability of compressing a stream by using GZip compression with Data Compression module, please log an idea on our ideas forum https://aka.ms/BusinessCentralideas

**Comment by JesperSchulz** [comment]
Actually, we do have a .NET wrapper as well: Codeunit 3036 DotNet_GzipStream. It will also allow you to do a few things with GZip!
And instead of creating an Idea (which may take time to get accepted and implemented), you are more than welcome to create a pull request right in this repo and add the functionality the [Data Compression](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Data%20Compression) module you are missing! We will process those PRs as quickly as we can.

**Comment by haweg** [comment]
The wrapper DotNet_GzipStream would be perfect, I used that one together with DotNet_CompressionMode to decompress Gzip streams in BC14. But in BC15 I can't find either of those .NET wrappers. Am I missing something?

DataCompression.OpenZipArchive(GzipInStream, false) unfortunately throws an error when it's used with Gzip Streams:
![grafik](https://user-images.githubusercontent.com/23580125/68777079-6a9c1700-0631-11ea-826f-bcebf4f8e418.png)
This makes kind of sence I guess (?) since Gzip files lack the EOCD signature.

**Comment by JesperSchulz** [comment]
That is odd! That wrapper should only have been removed, if the new module fulfills the requirements which the wrapper fulfilled. That is an honest mistake. I will create a bug right away to address the shortcomings! Our apologies!

And again, if you need even more functionality, please don't hesitate to contribute to the module! We'd be happy to bring in your code to make the module more capable.

**Comment by dcenic** [comment]
The fix is checked in and will be available in the next minor release of Business Central 15. Data Compression will have these methods:
DataCompression.GZipCompress(InputStream: InStream; CompressedStream: OutStream);
DataCompression.GZipDecompress(InputStream: InStream; DecompressedStream: OutStream);
DataCompression.IsGZip(InputStream: InStream): Boolean;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
