### ISSUE TITLE
[External] Codeunit 419 - CreateFileNameWithExtension

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4264]
Following the advice of @AlexanderYakunin, 

> please always open new issue if you cannot find something what should be implemented

#1297 has been closed for a while now, but we cannot find the solution in the latest docker images. Can you please verify?

- [ ] Solved in BC14

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
I was going through old, open issues and stumbled over this one. I'm afraid I totally missed this one. 

I just checked: the function is exposed in version 15 and newer, but is still local in version 14 and below. As we're not running any SaaS solution on versions lower than 15, I would believe this issue is by now redundant (as you could just expose the function in an on premises installation yourself)? If you'd still like to get the function exposed in version 14, please let me know! Normally we do not backport to that version, but since I left you hang to dry, I would make an exception for you in this case. Would you still like CreateFileNameWithExtension to be made public and external?

My apologies!

**Comment by fvet** [comment]
Thanks for your suggestion, but the function is indeed not to be backported to earlier versions.
