### ISSUE TITLE
Codeunit 7010 New Function

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/ALAppExtensions#432]
Hi, we need a new function in Codeunit 7010.
We need this because we need to use the local functions in CU 7010. We also need a similar function in CU 7000.
![image](https://user-images.githubusercontent.com/41729653/49020468-d0795f80-f190-11e8-9575-b0293d102763.png)
**Parameters:**
VAR purchasePriceRL : Record "Purchase Price"
itemNoL : Code[20]
variantCodeL : Code[10]
qtyL : Decimal
uOML : Code[10]
locationCodeL : Code[10]
VendorNoL : Code[20]
startingDateL : Date

**Variables**
currencyExchangeRateL	Record	Currency Exchange Rate	
vendorL	Record	Vendor	
UnitofMeasureManagementl	Codeunit	Unit of Measure Management	

_thanks in advance_

**Comment by grobyns** [comment]
Hi,

Can you explain what the scenario is where you need this function?
As a workaround for now, can you try to create a temporary purchase header and temporary purchase line with the correct values to call FindPurchLinePrice. You should be able to retrieve the Purchase Price record from the OnAfterFindPurchLinePrice event. 
I would suggest you use manual binding for the subscriber so that it is only called in your scenario.

br/Gert

**Comment by grobyns** [comment]
Closing for now. Please re-open if you have more info.

br/Gert

**Comment by LFlamme** [comment]
Hi,
sorry for the late reply, I didn´t notice i got an answer.

We have new tables, where we want to get prices, without going through the whole process. so this solution would make it possible for us to use local functions and global variables.
