### ISSUE TITLE
[BC15 | Module "Temp Blob"] Important but missing functions in the new module "Temp Blob"

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/ALAppExtensions#4322]
The TempBlob lacks some important functions, which were available before and can no longer be done now. Here is an enumeration of what is simply missing:

In the standard TempBlob there were some functions available which simply don't exist anymore. These are for example the following:

- WriteAsText
- ReadAsText
- ReadAsTextWithCRLFLineSeparator
- StartReadingTextLines
- StartWritingTextLines
- MoreTextLines
- ReadTextLine
- WriteTextLine
- GetHTMLImgSrc
- TryGetImageFormatAsTxt
- GetImageType
- TryDownloadFromUrl
- TryGetXMLAsText
- GetXMLAsText

Would it be possible to make these functions available again? This would be very helpful and would make it much easier to use.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by darjoo** [comment]
@IhorHandziuk @GiorgosPa for your visibility as well.

**Comment by darjoo** [comment]
@FSharpCSharp, I took a look and see that the following have moved into various places

GetHTMLImgSrc - Codeunit 4112 "Image Helpers"
TryGetImageFormatAsTxt - This has always been a local function, but is also now in Codeunit 4112 "Image Helpers"
GetImageType - Codeunit 4112 "Image Helpers"
TryGetXMLAsText - Codeunit 6224 "XML DOM Management"

For the remaining, Ihor and Georgios will know better.

**Comment by GiorgosPa** [comment]
@FSharpCSharp 
Write/Read functions were removed because they were misused and abused heavily.
For example in order to read a Blob as Text people came up with the following code:

```
TempBlob.Blob := SomeTable.SomeBlob
TempBlob.ReadAsText
```
instead of:
```
SomeTable.SomeBlob.CreateInStream
InStream.ReadText
```
Only the method `ReadAsTextWithCRLFLineSeparator` is kept but it is moved on `Codeunit "Type Helper"`, renamed to `ReadAsTextWithSeparator` and it now accepts Streams

Syntax:
`procedure ReadAsTextWithSeparator(InStream: InStream; LineSeparator: Text) Content: Text`

As for `GetXMLAsText`, it is not needed in AL as there is a native XML type. The most common use of that the resulted text was to be passed into the the function `LoadXMLDocumentFromText`. Now this would look like this:

```
TempBlob.CreateInStream(InStream);
Xml := XmlDocument.Create(Instream);
```

**Comment by FSharpCSharp** [comment]
@GiorgosPa 
Thanks for the clues. I understand that you are making changes to the application. But from my point of view these are also "Breaking Changes", which should also be explained there. If this had been communicated a bit better, several programs would not break now.

Personally, I find the reasons partly undecided and very flimsy.

I also don't really like the way you deal with criticism. To simply close the topic, but without doing anything, be it a better documentation or something similar, is personally incomprehensible to me. Sometimes I wish that Microsoft didn't simply deny all reasonable requests, underpinned by very strange arguments.

**Comment by GiorgosPa** [comment]
@FSharpCSharp I am updating the breaking changes document, there will be a pull request soon, I though it would be better to give you a reply sooner than later.
