### ISSUE TITLE
Base NAV fields on table 5900 - ambiguous

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4359]
There are two fields on table 5900 - "Actual Response Time (Hours)" and "Service Time (Hours)".  Please see the first attachment.  
We would like to hide them by using page extension to extend Service Order page 5900.   However, it shows symbol is ambiguous.   Please see the 2nd attachment.  

![image](https://user-images.githubusercontent.com/49729094/65726891-2dc99000-e084-11e9-9c21-83af68b9de4f.png)

![image](https://user-images.githubusercontent.com/49729094/65727080-bba57b00-e084-11e9-825b-209d6896a676.png)

Is there any way to get around the error?   Thanks.

**Comment by Teming** [comment]
We got it!  "Service Time (Hours)" was moved to a different spot on the page.  When converted with the tool to al, it first made the base NAV original field "Service Time (Hours)" as Visible = false.  Then it redefined it to the new location again.  That's why it became ambiguous.  Just rename the field name solves the issue.  Thanks.

**Comment by qutreson** [comment]
Hi @Teming, can you share more information with us about you ended up in this situation? 
The table "Service Header" defines two fields, which are then used as the source for some page fields in the "Service Order" page.  Did you have some modifications on these objects that you exported from C/SIDE, converted into a delta, converted to AL using the txt2al and then ended up in this situation with an ambiguous reference? If yes, can you share with us the .TXT files you exported in order to generate the delta so that we can investigate if we have a bug there?

**Comment by qutreson** [comment]
@Teming, if you can consistently reproduce the cause of your issue, please create an issue on [microsoft/AL](https://github.com/microsoft/AL/issues) repository.
