### ISSUE TITLE
[Event Request] Table 5870 OnBefore/OnAfterInitFromTable

### ISSUE THREAD

**Issue by SteveyN** [microsoft/ALAppExtensions#4646]
In table 5870 BOM Buffer, there are several InitFrom[table] functions, (like InitFromItem, InitFromRes)

Can we get 
`OnBeforeInitFromTable(var Rec : Record "BOM Buffer"; var Item : Record "Item"; var IsHandled: Boolean)`
and
`OnAfterInitFromTable(var Rec : Record "BOM Buffer"; Item : Record "Item")`

In each of these InitFrom functions?

**Comment by AlexanderYakunin** [comment]
Why do you need both? If you want to oveload this function using OnBefore, why do you need OnAfter?

**Comment by StephenNorfolk-DC** [comment]
We need to OnBefore to make any changes before the checks that conditionally populate fields: 
For example: our solution uses the Prod Bom No. from a specific Item Variant instead of the Item, it falls back to the Prod Bom on the Item.

The OnAfter is just in case we want to assign any additional fields, or perform additional checks, _after_ the rest of the fields have been assigned

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
