### ISSUE TITLE
Cannot be used for 'Extension' development.AL(AL0296) V15

### ISSUE THREAD

**Issue by TimothyWatkins** [microsoft/ALAppExtensions#4650]
Upgrading our extensions to v15 has broken a couple of features we use.

`if not UserPermissions.IsSuper(UserSecurityId()) then`

errors with

> The type or method 'IsSuper' cannot be used for 'Extension' development.AL(AL0296)

and the same with 

`SMTPMailSetup.SetPassword(JTokenRead.AsValue().AsText());`

> The type or method 'SetPassword' cannot be used for 'Extension' development.AL(AL0296)

We have used both functions heavily in our previous releases. Is there any chance these can be opened up again for use in extensions?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
Sorry, I somehow did not get the notification that this issue was waiting for my attention. Will look into it later today!

**Comment by JesperSchulz** [comment]
Alright, so I did some digging. Behind both changes is some kind of reasoning ;-) Let me try to explain:

**1) IsSuper:** 

The SUPER role is rather misleading in SaaS. You can have a team member license, yet be a SUPER user - what that in SaaS means, is that you are not limited in your team member license; it does not mean that you are not limited at all (being an admin), as it kind of means in on-prem, where everyone would share the same license.

In other words, generally there is a misconception, that SUPER is like an Administrator with no limit in permissions, which isn't necessarily the case anymore in SaaS. To prevent this misconception, we've limited access to the IsSuper function. We're actually seeing some of our own code making that mistake (SUPER = Admin) - since we ourselves cannot figure out how to use the SUPER role properly, we thought we'd spare you the hassle...

If you could explain why you need the IsSuper function, we would or course be willing to reopen the discussion whether or not that function should be callable from Add-On extensions though! Or if you're maybe looking for something else, we could build for you!?

**SetPassword**
That change is based on a security consideration. It was a security concern that we expose functions that set or get secrets to other extensions or functionalities, as these could be manipulated to retrieve secrets that other extensions should not have access to.

Again, if you could add a word or two on why you need to set SMTP passwords on the behalf of the user, we could look into how we can assist you in your scenario.

**Comment by JesperSchulz** [comment]
Continuing discussion outside of this forum.

**Comment by ajkauffmann** [comment]
Thanks for the info, Jesper.
As for SUPER, I'm thinking like we do on-prem: if a user is SUPER, he can access all data inside the company and perform any task. Someone can als be SUPER across all companies, which doesn't make him tenant admin or similar. It's just about the access level inside the environment and companies.

I think for SAAS a real SUPER should be a full user with SUPER role assigned. I understand that the role on itself does not tell the whole story.

**Comment by TimothyWatkins** [comment]
The reason we use IsSuper is because standard does. As an example standard only allows super user to create a company. We have subsequently extended the create company wizard and reflected standard "permissions" for this, i.e. IsSuper().
In SaaS we differentiate whether it's a delegate admin (CSP) user or real super user by whether they are entitled to run scheduled task. If a user has super yet can't run scheduled tasks we assume it's a CSP super user and not a real super user.

**Comment by JesperSchulz** [comment]
ok, we'll move forward with the IsSuper request. The SetPassword request is slightly more difficult. I will have to assign looking into it to an engineer on my team. We'll get back to you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by JesperSchulz** [comment]
Reopening, as only the IsSuper part is resolved for now. Btw.: we've currently fixed this to be released with the next minor update (probably January). Is that sufficient, or do we need to hotfix?

**Comment by TimothyWatkins** [comment]
@JesperSchulz as mentioned we have already made our own IsSuper function, so no need to rush this work in, unless it can be done within a week? Would otherwise be happy to be informed of when it's been released so we can update our code to use standard.
The one of more concern for us with an "immediate" impact not being able to use SetPassword. Might there be an update on that?

**Comment by JesperSchulz** [comment]
Unfortunately the developer I assigned the bug to got sick. I have reassigned the bug and we're back on it!

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
