### ISSUE TITLE
[Event Request] COD41 TextManagement, OnAfterMakeDateFilter2

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#4666]
Please add OnAfterMakeDateFilter2, to the end of MakeDateFilter2 as the following code suggests

```
  IF OK AND (RemainderOfText <> '') THEN BEGIN
    Date1 := CALCDATE(DateFormula,Date1);
    Date2 := CALCDATE(DateFormula,Date2);
  END;

  OnAfterMakeDateFilter2(OK, PartOfText, Position, DateFilterText, Length, Date2, Date1);

  EXIT(Position);
```

Publisher: 

```
[Integration(DEFAULT,TRUE)]
[LineStart(11988)]
PROCEDURE OnAfterMakeDateFilter2@1100366000(VAR OK@1100366000 : Boolean;VAR PartOfText@1100366001 : Text;VAR Position@1100366002 : Integer;VAR DateFilterText@1100366003 : Text;VAR Length@1100366004 : Integer;VAR Date2@1100366005 : Date;VAR Date1@1100366006 : Date);
BEGIN
END;
```

**Comment by JesperSchulz** [comment]
Thank you for your request, but the code you are referring to does no longer exist in the 2019 Wave II release of Business Central. Could you update your request to reflect the latest code base? You could also implement the event yourself, as most of the Text Management codeunit was refactored into Modules, which are open sourced in this repository! By creating a PR rather than an issue, you would speed up the process!

**Comment by JesperSchulz** [comment]
The module you are looking for is most likely "[Filter Tokens](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Filter%20Tokens)".

**Comment by Nameyka-DC** [comment]
Hi, I did not realise this was an option, I will have a look at this, and Filter Tokens may just be what we need, thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
