### ISSUE TITLE
Parameter Extension in Standardfunctions

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/ALAppExtensions#467]
We have the need for many parameter extensions in standardfunctions.

Example:
Our solution needs extra filtering in all whse-functions which are related to whse-quantities. Just for filtering that extra flag before calculating the quantities.

Actually there is no possibility to do that in 2019.

How about an empty container from the type dictionary of [text,text] to transport any needed additional  parameters to external functions?
So we can grab the content of the dictionary in a publisher inside the function?

I have made an example of one function which is quite similar in most whse calculating functions:

![image](https://user-images.githubusercontent.com/42136602/49140227-084ce800-f2f4-11e8-9145-acbed9fd39e1.png)

With this attemp, any solution partner can transfer anything through the standardfunctions and can get it in his own subscriber!

**Comment by JesperSchulz** [comment]
As I've replied in one of your other threads, the idea is actually something we have in our backlog for future work, supported by our platform rather than through manual modifications of the parameter list. The effort is slightly bigger and it will be a while before you see it in the product, but as we have it in our backlog, we'd prefer not to start implementing competing solutions. Another issue with your suggestion is, that we don't have dictionaries in C/AL, only in AL - and as you know we haven't completed the move quite yet ;-) An argument table could be used, but again - that's not the solution we're looking for longer term. But rest assured, that we're working on a generic way to pass on extension parameters. It just has to be done right.

**Comment by ThomasBrendel** [comment]
As you said: Another issue with your suggestion is, that we don't have dictionaries in C/AL, only in AL 

But as you can see in my  example it is with a dictionary in C/AL ...so you should consider it again.
Or you named that construct "argument table"? Im not sure about your response.

**Comment by JesperSchulz** [comment]
The dictionary approach was brought up many times before and has been discussed back and forth for quite a while now. The problem is, that the PropertyBag/Dictionary approach is costly at runtime, and will pollute the entire codebase. The current line of thinking is leaning more towards a global Context (PropertyBag) the you can set a value to that have the lifetime of the current method call e.g. the exit from the current method will remove the value from the Context to avoid orphans. But as I wrote, we haven't picked up the actual work yet and also haven't settled on a sustainable, performant design yet. We'll get to it in time. Until then, we will try to help you on "per need" basis to the best of our ability.

About the argument table: it's an older, well-known pattern which also tries to solve your problem. But again, we never picked up on it internally, as we would prefer a platform based solution. If you're curious, you can read more about it here: https://community.dynamics.com/nav/w/designpatterns/245.argument-table.
