### ISSUE TITLE
RunOnClient - Item Picture

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4963]
What are the plans with any 'RunOnClient' code? BC15 has been shipped with approx. 100 'RunOnClient' variables, where I expected that RunOnClient was no longer supported on the Modern clients?

E.g., we've duplicated the 'Item Picture' page.
I would like to know:
- Why the item picture does not error when running the page in the webclient?
- What assembly to include in the dotnet.al file?
- Why the [RunOnClient] tag is still included in the BC 15 (webclient only)? And what would be the alternative?

```
        [RunOnClient] // >>> Is this supported in webclient?
        [WithEvents]
        CameraProvider: DotNet CameraProvider;
```

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by IhorHandziuk** [comment]
@fvet , thank you for the question. Indeed [RunOnClient] is not supported by the web client, but it _is_ supported by our Android, IOS and Windows UWP (from Microsoft Store) clients.
1) A .Net variable with [RunOnClient] property will indeed throw a runtime error if attempted to be run in the web client, _but only when the functions that require a mobile client are run_. For example, the function _IsAvailable_ on _CameraProvider_ can be run on any client, that's why "Item Picture" page doesn't throw an error on opening.
2) There is no assembly that you can include for this particular .Net variable to work in a 3d party extension (as it is an internal assembly). Generally speaking, in this cases the extension will have to call the existing code from Base application or System application. For the particular case that you provided as an example we recently developed [a module that will allow you to use the CameraProvider class](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Camera%20and%20Media%20Interaction/src).
3) As mentioned above, the [RunOnClient] property is still there as it can be used by the mobile clients.

**Comment by JesperSchulz** [comment]
When that is said, we do have some pending clean up work to do! We have quite a few client side assemblies in our code, which cannot work - e.g. the ones related to Office integration. We have that work in our backlog.
