### ISSUE TITLE
Phys. Inventory Tables 5005350-5005363 are still in the BC14CU7-NAVDACH database

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#5291]
Dear AL team,
in BC14CU7-NAVDACH the "Phys. Inventory" table 5005350-5005363 are still in the database after upgrading the data from these tables to Table-ID 5875-5887. They should have been deleted after the UpgradeProcess finished.
These giving conflicting results during an automerge as EventSubscribers to events in the tables 5005350-5005363 are still "valid".
Please have a look into this issue. Thank you.
<img width="934" alt="Screenshot 2019-12-13 at 16 43 32" src="https://user-images.githubusercontent.com/43308169/70801142-acf77600-1de0-11ea-80c7-a9f993a331fc.png">

**Comment by AlexanderYakunin** [comment]
We could not remove them due to our obsolete policy as 14.X have been our cloud offering at this time.   After release of BC 2019 Wave 2 we have 14.X as on prem version and will be able to remove these tables after upgrade to 15.X will be fully completed. Before that please remove these objects from you on prem databases if not needed.
