### ISSUE TITLE
OnOpenPageEvent is not triggered for role center page Acc. Receivables Adm. RC (9003)

### ISSUE THREAD

**Issue by shashiBssi** [Microsoft/ALAppExtensions#55]

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by JesperSchulz** [comment]
I'm afraid this is "by design". Role Center pages may not contain code and hence also don't raise events. As a workaround you may subscribe to the events of the activities page in the role center, which in this case is page 9034 - "Acc. Receivable Activities". It's an often used workaround. I hope that unblocks you. If not, please reopen issue.
