### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - function UpdateAssocOrder

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5779]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73160689-b0845980-410f-11ea-9534-51512c999845.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73160702-b7ab6780-410f-11ea-8302-dff26d154aba.png)

thanks & regards

Ashwini Tripathi

**Comment by AlexanderYakunin** [comment]
Var PurchaseOrderHeader can have different values in the loop, so probably this event should be used in different place? Please clarify what is your need.

**Comment by ashwinitripathi** [comment]
My requirement at this location is to Post Invoice without Commit. I have requirement to execute below: 

PurchaseOrderHeader.Invoice = TRUE;
PurchPost.SetDoNotCommit(TRUE);        -> which will be local function in this codeunit
PurchPost.Run(PurchOrderHeader);

**Comment by RomanZanizdra** [comment]
Hi @ashwinitripathi . The event you asked for doesn't have any sense because purchase header is got within the repeat .. until cycle and the event is outside the cycle. In fact you will get the last purchase header. If you need to post related purchase header i suggest you to get it in existing events via purchase line or dropshptbuffer.
