### ISSUE TITLE
Security Filters on posting

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#5871]
Hi,

Faced the problem of transferring security filters to AL. It is necessary to add this filter for FindLast to work without errors. I see what you processed in the InitNextEntryNo function from codeunit 12, but you also need to add a security filter for other objects. Please consider this change.

This is a simple list of objects where we change the security filter to ignored for table GLEntry.
CU 12 Gen. Jnl.-Post Line
CU 13 Gen. Jnl.-Post Batch
CU 80 Sales-Post
CU 90 Purch.-Post
CU 226 CustEntry-Apply Posted Entries
CU 227 VendEntry-Apply Posted Entries
CU 900 Assembly-Post
CU 5704 TransferOrder-Post Shipment
CU 5705 TransferOrder-Post Receipt
CU 5980 Service-Post

**Comment by RomanZanizdra** [comment]
Hi @vlkov . Could you be so kind to describe what problems did you meet with the "glentry.findlast" in the list of objects above and security filters? As i see it make sense to ignore security filters while getting the next number but in described objects findlast is more to lock the table rather than get the number, the variable is not used further. 
Could you also describe the case where you met problems or possible problems?

**Comment by RomanZanizdra** [comment]
Hi @vlkov . Any update from your side?

**Comment by RomanZanizdra** [comment]
Hi @vlkov , please be so kind to provide an update or let's close current issue for now and feel free to re-open it when you will have additional information.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
