### ISSUE TITLE
NAVDACH Report Seleciton Integatration for Issued Delivery Reminder 

### ISSUE THREAD

**Issue by JulianTillmann** [Microsoft/ALAppExtensions#591]
Issued Delivery Reminder (NAVDACH, Report 5005273) is hardcoded in Page 5005273. 

Please make it available for Report Selection (Table 77)

**Comment by JesperSchulz** [comment]
I am not sure I understand your request. Could you elaborate, so that I can route the issue to the right team?
Please note, that this repository is only for extensibility issues. If you believe you have found a general bug, I'd ask you to open a support request to CSS through the PartnerSource portal so that the issue can get resolved in all released versions. If this is a general idea for an improvement, I'd ask you to log that idea on http://aka.ms/bcideas.
For more information on "Finding the right resources and provide feedback", please go here: https://community.dynamics.com/business/b/financials/archive/2018/12/04/find-the-right-resources-and-provide-feedback.

**Comment by JulianTillmann** [comment]
I was told by the https://github.com/Microsoft/AL guys that it belongs over here. 

It think it's an extensability issue: 
In the NAVDACH localization, there is a Report called from a page. the call is hardcoded in that page and so it's not really extensible.

**Comment by GiorgosPa** [comment]
Hello in the latest DACH version the "Issued Delivery Reminder" report is not hard coded, it is using table 26100 DACH Report Selections.
