### ISSUE TITLE
[Event Request] table 1226 "Payment Export Data"

### ISSUE THREAD

**Issue by Rick37-tech** [microsoft/ALAppExtensions#5988]
Hi, we need to add some fields to SetCustomerAsRecipient.

Modifications

 ```
PROCEDURE SetCustomerAsRecipient(VAR Customer: Record 18;VAR CustomerBankAccount: Record 287);
    BEGIN
      //>>New Code
      OnSetCustomerAsRecipient(Customer,CustomerBankAccount)
      //<<New Code 
      "Recipient Name" := Customer.Name;
      "Recipient Address" := Customer.Address;
      "Recipient City" := COPYSTR(Customer.City,1,35);
      "Recipient Post Code" := Customer."Post Code";
```
Events

`LOCAL [IntegrationEvent] OnSetCustomerAsRecipient(VAR Customer: Record 18;VAR CustomerBankAccount: Record 287)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by jwinberg** [comment]
Could you please also add at least OnSetVendorAsRecipient. Need this URGENTLY for sepa payments to get more information to payment file. Most payments are done to vendors anyway?!

And at the same time migth as well add the other procedures (SetEmployeeAsRecipient, SetBankAsSenderBank etc.) so that we dont have to request ad-hoc.

**Comment by dtkb** [comment]
Can I ask why these were released taking the source account records by `var`? I wouldn't think there is any legitimate reason to modify the sources during the copy.
