### ISSUE TITLE
Region Dutch (Belgium) keyboard settings

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#6446]
In BC15.4 we use region Dutch (Belgium)
when we use the . key on numeric key-pad a point is written in stead of comma (,)
so when entering 11.11 this is changed to 1.111 instead of 11,11

when we do the same in excel, notepad,... this goes like it should 11,11, but not in BC.
can this behaviour be changed in any way?

**Comment by salgiza** [comment]
This question was raised in the Business Central Yammer last august, but it seems it was not important enough to be fixed in the next release.

https://www.yammer.com/dynamicsnavdev/#/threads/show?threadId=292748811567104

We have the same problem in Spain (we can't use numeric keyboards with BC to enter decimals), I think this bug also applies to French keyboards, and I'm sure there are several other countries with this problem (dot in the numeric keyboard, comma used as decimal separator).

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
