### ISSUE TITLE
[Event Enhancement and displacement] Codeunit 90 - OnBeforeItemJnlPostLine

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/ALAppExtensions#727]
The event "OnBeforeItemJnlPostLine" in the code unit 90 is incorrectly placed. It belongs before the block where the Tracking Specification is handled. Otherwise there are already data changes. Furthermore, the signature of the event should be adjusted, because important information is simply missing, and you don't get it with the existing event at all.

The event should be moved as follows:
![image](https://user-images.githubusercontent.com/22373356/50597262-27b4d300-0ea7-11e9-9982-0f1bf7f33876.png)

So far the event has the following parameters:

| Var |       Name        | DataType |      Subtype      | Length |
|-----|-------------------|----------|-------------------|--------|
| Yes | ItemJournalLine   | Record   | Item Journal Line |        |
| No  | PurchaseLine      | Record   | Purchase Line     |        |
| No  | PurchaseHeader    | Record   | Purchase Header   |        |
| No  | CommitIsSupressed | Boolean  |                   |        |

However, the following would be desirable, because you need some more information about the posting process.

| Var |         Name         | DataType |        Subtype         | Length |
|-----|----------------------|----------|------------------------|--------|
| No  | PurchRcptHeader      | Record   | Purch. Rcpt. Header    |        |
| No  | PurchInvHeader       | Record   | Purch. Inv. Header     |        |
| No  | PurchCrMemoHdr       | Record   | Purch. Cr. Memo Hdr.   |        |
| No  | ReturnShipmentHeader | Record   | Return Shipment Header |        |
| No  | PurchaseLine         | Record   | Purchase Line          |        |
| No  | PurchaseHeader    | Record   | Purchase Header   |        |
| No  | CommitIsSupressed | Boolean  |                   |        |
| Yes | ItemJournalLine      | Record   | Item Journal Line      |        |
| No  | QtyToBeReceived      | Decimal  |                        |        |
| No  | QtyToBeReceivedBase  | Decimal  |                        |        |
| No  | QtyToBeInvoiced      | Decimal  |                        |        |
| No  | QtyToBeInvoicedBase  | Decimal  |                        |        |

**Comment by esuarkfalo** [comment]
Here I can comment the same as in the issue 722. The answer is nearly equal because it is the same Problem. Issue 722: codeunit 80 for sales; Issue 727 (this issue): codeunit 90 for purchase.


Here the answer of the issue 722 follows (with Little changes due to purchase and this issue):


Today I have created a new docker Image. In c/side I have checked the codeunit 90 for this issue (in the docker image the codeunit is from the date of 13th January 2019). But the requested event publisher does not have the "GlobalVarAccess", But we Need at least the numbers of the posted documents if they are filled (therefore the four posted Header are included in the event). With the "GlobalVarAccess" there is no need for that anymore.
With the quantites you are Right. We can use the fields of the "ItemJnlLine" instead. So these part of the issue can be ignored.
Summary: If the event has the "GlobalVarAccess" set to "TRUE" there is no need to change anything except moving the event. But if not we need access to the posted headers (at least to the field "No." of each of these headers) instead.
