### ISSUE TITLE
Removed Event in Codeunit 41 CaptionManagement

### ISSUE THREAD

**Issue by EasyStep2Lean** [Microsoft/ALAppExtensions#734]
In NAV2018 Codeunit 41 caption management had an event to control custom Captions. It has been removed in Business Central.

![image](https://user-images.githubusercontent.com/17320737/50634023-93ea1200-0f4d-11e9-9247-9b72d4c6c3b4.png)

Can we have this please back?

![image](https://user-images.githubusercontent.com/17320737/50634089-d14e9f80-0f4d-11e9-81d6-5216aefee423.png)

**Comment by AlexanderYakunin** [comment]
Here is answer why this event have been removed:

CaptionClass Management and AutoFormat Management do not need events. These functionalities are already extendible because their properties act as expressions. If a partner wants to add a new class for example, all they need to do is put a function call in the expression does not map to any of the existing options. In this case, the function will simply return the string provided. They can put all their logic in the function.
