### ISSUE TITLE
Workdate not correct

### ISSUE THREAD

**Issue by stijn9830** [microsoft/ALAppExtensions#7371]
Hi, 
when creating a new company, for a reason I do not know, the field CompanyInfo.demo environment is set to yes.
thats the reason why the workdate is nog correct, it will take the last posting date on g/l entries.
I can not find how we can add the field on the page, without using a page extension. Even not with personalisation.
I'm working on BC160 saas, so latest CU.

Thanks,
Stijn

**Comment by stijn9830** [comment]
Sorry, i meant field 100 Demo Company
On SAAS customers, I can not find this field on the page.

**Comment by stijn9830** [comment]
When creating new company, You get a wizard on Saas environment, but can you manipulte this parameter afterwards? 
![image](https://user-images.githubusercontent.com/56073675/84161414-8c4a6900-aa6f-11ea-85bb-fa254577bd5c.png)

**Comment by dtkb** [comment]
My bad, I was looking at system table `Company`, not 'normal' table `Company Information`. I grepped through on-prem source code and can't see anywhere that sets `Demo Company`. Mysterious...

**Comment by StanPesotskiy** [comment]
There are 4 options when you create a new company:
https://docs.microsoft.com/en-us/dynamics365/business-central/about-new-company#creating-a-new-company

1. **Evaluation** - Sample Data

1. **Production** - Setup Data Only

1. **Advanced Evaluation** - Complete Sample Data 

1. **Create New** - No Data

The "Demo Company" field is set to true for **Production** and **New**. It is not supposed to be modified by users, because the evaluation companies are for demonstration only. 
But you can create an extension that would add this field to a page, where you can change it.

**Comment by dtkb** [comment]
> The "Demo Company" field is set to false for Production and New.

Surely it should be false for those, and true for the others? ;-)

**Comment by stijn9830** [comment]
Ok, Thanks. What if you made a mistake, and the company is already used by the customer, there is no way back, except making an extension?

**Comment by StanPesotskiy** [comment]
That is right. The evaluation company contains the demonstration data (customers, vendors, items, etc.) and it is not supposed to become a production company.
