### ISSUE TITLE
[EventRequest] SalesHeaderApply.Codeunit.al (codeunit 401 "Sales Header Apply")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7633]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **SalesHeaderApply.Codeunit.al** Codeunit.

**Standard Code**
![image](https://user-images.githubusercontent.com/33481576/86351046-3f7a3c80-bc81-11ea-9408-911d1c5a7499.png)

**Modified Code**
![image](https://user-images.githubusercontent.com/33481576/86351109-5ae54780-bc81-11ea-8793-f70087ab877d.png)

**Event Signature**
![image](https://user-images.githubusercontent.com/33481576/86351143-6d5f8100-bc81-11ea-9ed7-16c61dacd74e.png)

Thanks
SUD

**Comment by dtkb** [comment]
With a proper, generalised name, this would also be useful to us in order to set extra filters.

**Comment by StanPesotskiy** [comment]
Regarding your last comment. We are not populating events to all similar places. If you require an event in another object or another function, please create additional requests including all details. If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
