### ISSUE TITLE
2020 release wave 2 breaking changes

### ISSUE THREAD

**Issue by Sven-Niehus** [microsoft/ALAppExtensions#7972]
Hi,

is there an ETA for the breaking changes list for 2020 release wave 2?

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by Sven-Niehus** [comment]
Hi @StanPesotskiy,

my request is about the BREAKINGCHANGES.md file located [here](https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md). I want to know if you have an ETA for updating this document for the 2020 release wave 2.

**Comment by JesperSchulz** [comment]
Hi Sven-Niehus,

as the upcoming releases are non-breaking (or at least just about non-breaking ;-)), the document has no planned update. In the upcoming release, code may have been deprecated rather than removed, in which case you will find the description in the deprecation message (ObsoleteReason), rather than in the BREAKINGCHANGES.md document.
