### ISSUE TITLE
[Event Change] TAB 383 in Function InsertDtldCVLedgEntry

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#8295]
Hey,
please have a look at
https://github.com/microsoft/ALAppExtensions/issues/5989

Many thanks for adding parameter in BC15 and BC16. 
But ... We need parameter also in BC14, when will it be available?

Thanks in Advance
Andrea

**Comment by RomanZanizdra** [comment]
Hi @AndreaRux . We add events via github requests only for the latest prod version. If you really need the event to be downgraded to 14.x version due to customer extension development or other issues please reach out the product support channel in order to log your request as a hotfix. Then it will be implemented in required version.
I suggest to close current issue. Any objections from your side @AndreaRux ?

**Comment by AndreaRux** [comment]
no
