### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - OnAfterInitFilter

### ISSUE THREAD

**Issue by maksym-ch** [Microsoft/ALAppExtensions#83]
Hi,
We need to implement additional business logic after init filter.
The following publisher is needed to be added (before inserting temp whse. item tracking line record):
Codeunit 99000845 Reservation Management - Function InitiFilter() -
**OnAfterInitFilter(VAR ItemLedgerEntry : Record "Item Ledger Entry";ReservationEntry : Record "Reservation Entry";EntryID : Integer)**
![c 99000845 p01](https://user-images.githubusercontent.com/44081671/47207639-68b34600-d394-11e8-8a87-07d203da9c49.png)

**Comment by AlexanderYakunin** [comment]
Do you want to extend filter for ItemLedgEntry in this event?

**Comment by AndriiHrynyuk** [comment]
Hi, 
The publisher in the last BC differs from the one that was requested here. Added event publisher does not contain the first parameter. 
The business logic we are trying to implement includes additional filtering on Item Ledger Entry. That's why we need this publisher changed to be exactly like in the initial request:
`OnAfterInitFilter(VAR ItemLedgerEntry : Record "Item Ledger Entry";ReservationEntry : Record "Reservation Entry";EntryID : Integer)`
Could you please do the change mentioned?
Thanks.

**Comment by AlexanderYakunin** [comment]
Implemented event is more generic and give you access to Global variables, including CalcItemLedgEntry. This way we don't need to extend it for next partner asking for access to CalcAssemblyLine, for instance.
