### ISSUE TITLE
Bug - Codeunit 1005 - Function PostDiffBuffer

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/ALAppExtensions#838]
To allow to post Cr.Memo with Item on Job the below code in codeunit 1005 have to change:

PostDiffBuffer(DocNo : Code[20];PostingDate : Date;TemplateName : Code[10];BatchName : Code[10])
IF JobDiffBuffer[1].FIND('-') THEN
….
REPEAT
**// begin
//IF JobDiffBuffer[1].Quantity > 0 THEN BEGIN
IF JobDiffBuffer[1].Quantity <> 0 THEN BEGIN
// end**

**Comment by JesperSchulz** [comment]
Interesting. It's a little hard for us to determine whether it really is a bug, as repro steps and expected behavior are missing. But regardless, this isn't the right place to log product bugs. So let's get the issue to a team who will fix and backport it, as this repository only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
