### ISSUE TITLE
[Request for External] Page 508 and 510 ShowOrders

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8435]
Please make procedure ShowOrders in Pages 508 and 510 public and external, so we can use those procedures in our extensions and do not need to rewrite them.

Or even better implement ShowOrders, ShowInvoices, ShowReturnOrders, ShowCreditMemos, ShowPostedOrders, ShowPostedInvoices, ShowPostedReturnReceipts and ShowPostedCreditMemos
as public and external procedures in T37 and T39
with names ShowOrdersForBlanketOrderLine, ShowInvoicesForBlanketOrderLine aso.

**Comment by AlexanderYakunin** [comment]
These procedures are specific for Blanket Order line, therefore they are placed in corresponding pages. We don't want to overload T37/T39 with unnecessary code without string reason. If we make them external in P508/P510, how you are going to use it? If we should move it somewhere, why not move this to new codeunit instead of T37/T39?

**Comment by GuntherGebauer** [comment]
To move those procedures to a new codeunit would also be convenient for us

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
