### ISSUE TITLE
New Functions on PAGE 6510 

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#847]
Make Function ZeroLineExists External and Global

Make Function NextExtryNo External and Global

Make Function TestTempSpecificationExists External and Global

Make Function CalculateSums External and Global

Create New function **GetEdtableVariables**
 
![image](https://user-images.githubusercontent.com/32099690/51208362-b3c4f280-18ca-11e9-8528-35f48453ec90.png)
![image](https://user-images.githubusercontent.com/32099690/51208390-c7705900-18ca-11e9-8562-b32533d60034.png)

 Create New Function **GetVisibleVariables**
![image](https://user-images.githubusercontent.com/32099690/51208422-e0790a00-18ca-11e9-9a06-dd4f804da137.png)
![image](https://user-images.githubusercontent.com/32099690/51208444-ed95f900-18ca-11e9-930b-c5afcef873e5.png)

 Create New Function **GetVariables**
![image](https://user-images.githubusercontent.com/32099690/51208466-01d9f600-18cb-11e9-9a5a-0b2bf913b1c4.png)
![image](https://user-images.githubusercontent.com/32099690/51208476-0a323100-18cb-11e9-8d07-f9f2969ffea8.png)

Create New Function **SetVariables**
![image](https://user-images.githubusercontent.com/32099690/51208498-1ae2a700-18cb-11e9-810d-157fff97d77a.png)
![image](https://user-images.githubusercontent.com/32099690/51208511-23d37880-18cb-11e9-987e-dde74ad4c7eb.png)
[PAG6510_011519.txt](https://github.com/Microsoft/ALAppExtensions/files/2761373/PAG6510_011519.txt)

**Comment by JesperSchulz** [comment]
Please provide a scenario for what you are trying to achieve.

**Comment by JesperSchulz** [comment]
Is it somewhat related to #843?

**Comment by MatthewMcCarthy7** [comment]
It's not related to #843.

The Functions GetEditableVariables and GetVisibleVariables are both used for fields that we add.  We use the NewLotNoEditable and NewLotNoVisible to determine if our variable is visible and Editable.  We also use Inbound to determine if a Factbox should be shown.  I don’t need all the variables for Editable and Visible, but figured the function is being created might as well add all those variables into them, since we might need more later or other people might need them as well.

The making Functions ZeroLineExists, NextEntryNo, TestTempSpecificationExists, CalculateSums, and the new function GetVariables and SetVariables are used for a custom Page Action.  This Page Action Opens a RunModal page where they select an existing Lot, and they number of new Lots they would like to turn that into.  This then creates a new Entry in the Item Tracking Page for the new No. of Lots that were selected in the page.  The user can then review the new Lots created and modify what was created and then save the values.  Since everything in that page is temporary until the page is closed it limits, what we can do on page actions since we do not have access to the Temp variables stored on that page.

**Comment by MatthewMcCarthy7** [comment]
I was checking in on the status of this request.

**Comment by Bleika** [comment]
Please note that this is a typical scenario to be solved through a Reclassification Journal.

In the Warehouse (P7365->P6550) it can be easily solved but a couple of issues preventing it in "basic" Item Tracking (P393->P6510):

1) If the bug in TestTempSpecificationExists is solved (that is: check in Reclass is performed against "New Lot No." instead of "Lot No."), then you can create several lines in Page6510 with Identical "Lot No." and different "New Lot No." and the user can see them all at once. 
If not, the lot has to be split in the journal, and the Item Tracking defined separately for each line. I already requested a fix for this in #1346 

2) If variable FormRunMode is made accessible, then you can build your scenario on top of "FormRunMode::Reclass" (which allows everything to be seen and edited). I've also requested that we get a new function to expose this variable (GetFormRunMode) in #1347

**Comment by pranav4186** [comment]
The action @MatthewMcCarthy7  is talking about is going to be enabled on Item Tracking Line Page only if the user opens it from Sales or Transfer Order, so that they can create one or more new lots from the single existing on without leaving the page.
Currently we are building Reclass journal with the item tracking in the background and posting it.
This is really user-friendly as it would save them time and clicks to going through reclass journal and assigning newly generated lots back to sales or transfer order.
I am sure #1346  and #1347 would improve item tracking functionality for reclass journal but we need this functionality for Sales and Transfer order.

**Comment by Bleika** [comment]
But these are 2 seperate transactions: first you must split the lot and post your changes, so that the new lots exist in stock before you can link them to an order.
You say that you've already solved generating ReclassJnl in the background, so it seems that the problem to solve is to allow the user to "review the new Lots created and modify what was created and then save the values". 
To me it sounds like a question of timing rather than modifying the standard:
If you let the user revise the split lots BEFORE you post them (that is: with P6510 in Reclass mode), then it fits more easily within the existing design:
You (background) generate the Reclass, open P6510, let him/her revise/confirm, you close P6510 and (background) post the Reclass and leave the user with P6510 where the order is the Soure Rec an the new (revised) lots may be linked to the order (where no second editing is necessary)...
That approach doesn't increase the number of clicks needed for the task.

**Comment by pranav4186** [comment]
That is exactly we are doing. We are doing 2 separate transactions, and yes our current functionality is saving a number of clicks by posting reclass in the background when they close the page.

When User clicks this action button on Item Tracking Lines, they can select From Lot (existing) and To Lot (New Lot), how many new lots they want and quantity per lot.
After that when the user closes the P6510 we generate reclass in the background and assign new lots to P6510, so yes it is fitting more easily with the existing design.
We need requested events/functions to covert this mods to extinction. We need to access those temp variable so that we can insert new/changed lots into those temp variables and give it back to BC to execute its standard workflow. Plus these events/functions will also be useful in the future as it would increase access to temp variables of P6510.
We have it as a button because the user would not always split the lot from sales and transfer orders.
I hope now you would understand, why we are asking these events/function to Microsoft.

@JesperSchulz, please let us know if you have any update on this request.

Thank you.

**Comment by Bleika** [comment]
I hope I haven't offended you with my input - by no means it was my intention to step on your toes and obviously Microsoft is who decides.

I was just trying to point out that you can figure out visibility & editability without adding more code to to the already "messy" code of standard Item Tracking, since these properties depend on well defined conditions and are controlled through calls to SetControls. 
When extending Item Tracking, whether it be adding new attributes to LN/SN or adding new scenarios/flows, they basically must obey the same criteria as is used for SetControls.
Therefore I personally don't see any added value in fx GetVisibleVariables and GetEditableVariables.

As to GetVariables and SetVariables I also believe there are other alternatives to hold on to the newly created lot numbers (e.g. single instance codeunit).

Anyhow, I'll step out of the way.

**Comment by pranav4186** [comment]
Thank you for your inputs, We need fx GetVisibleVariables and GetEditableVariables because the controls we are adding depends on the different conditions.
We also need GetVariables and SetVariables to hold temporary variables and would also be useful for others.

**Comment by MatthewMcCarthy7** [comment]
Hello,

I was checking in on the status of this request.

**Comment by MatthewMcCarthy7** [comment]
Hello,

Is there any update on this request? This request is holding us up from being able to submit our app to Appsource.

**Comment by MatthewMcCarthy7** [comment]
This is done.  Closing Ticket
