### ISSUE TITLE
Business Central Payment functionality

### ISSUE THREAD

**Issue by ManDaMDuda** [Microsoft/ALAppExtensions#97]
**Describe the bug**
If the Bank Payment is transmitted I can not Void the payment.
**To Reproduce**
Create a Bank Payment Line and Export to File.
Click the Transmit Payment so that the Payment is transmitted.
Try to void the Payment you get Error that theare no Payments to Void.
I have maked a little search why.
Report 9200 "Void/Transmit Elec. Pmnts" by "Gen. Journal Line" OnAfterGetRecord has a Bug.
Lines:
IF UsageType = UsageType::Void THEN BEGIN
"Exported to Payment File" := FALSE;
"Check Exported" := FALSE;
"Check Printed" := FALSE;
"Document No." := '';
END ELSE
"Check Transmitted" := TRUE;
When you transmit the Bank Payment File it set the "Check Transmitted" as true. and later of you want Void the payment it checks if theare Checks available, but no Check's are theare becouse we work with Bank Payment Files and theare no Check's will be generated.
**Expected behavior**
The Payment is voided.
**Versions:**
Business Central: latest

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by ManDaMDuda** [comment]
I have created workaround for this issue. so theare no problem about delays.

**Comment by JesperSchulz** [comment]
Sounds good that you have a workaround. As this is a proper functionality bug, could I ask you to follow the below guideline so that your issue ends up in the right channels?

This GitHub repository is dedicated to handling issues with published apps and extensibility requests for the latest release of Business Central. If you run into an issue, open a support case. You can open a Support Request to CSS through PartnerSource portal or by contacting your Service Account Manager (SAM) in the local subsidiary, to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.
Another option would be to file this bug in Collaborate and include details on your Business Central build number and country. Quick link: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.
